project:
  type: book
  output-dir: docs

book:
  title: "Analisi esplorativa dei dati in psicologia"
  subtitle: "Modulo introduttivo"
  license: "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)"
  reader-mode: true
  google-analytics: G-QT5S3P9D31

  author: 
    - name: "Corrado Caudek"
      orcid: "0000-0002-1404-0420"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/utet-eda/
  repo-actions: [source, issue]
  back-to-top-navigation: true
  site-url: https://ccaudek.github.io/utet-eda/
  page-footer:
    left: |
      **Analisi esplorativa dei dati (EDA)** — Modulo del progetto UTET a supporto del manuale *Metodi bayesiani in psicologia*.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  favicon: style/gauss.png


  sidebar:
    # style: "docked"
    search: true
    collapse-level: 1

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: chapters/key_notions/introduction_key_notions.qmd
      chapters:
        # - chapters/key_notions/01_data_analysis.qmd
        - chapters/key_notions/02_key_notions.qmd
        - chapters/key_notions/03_design.qmd 
        - chapters/key_notions/04_measurement.qmd
        - chapters/key_notions/05_cognitive_models.qmd

    - part: chapters/R/introduction_r_lang.qmd
      chapters:
        
        - chapters/R/01_r_syntax.qmd
        - chapters/R/02_utility_functions.qmd
        - chapters/R/03_r_programming.qmd
        - chapters/R/04_r_packages.qmd
        - chapters/R/05_dplyr.qmd
        - chapters/R/06_quarto.qmd
        - chapters/R/07_environment.qmd

    - part: chapters/eda/introduction_eda.qmd
      chapters:
        - chapters/eda/01_project_structure.qmd
        - chapters/eda/02_data_cleaning.qmd
        - chapters/eda/03_exploring_qualitative_data.qmd
        - chapters/eda/04_exploring_numeric_data.qmd
        - chapters/eda/05_data_visualization.qmd
        - chapters/eda/06_loc_scale.qmd
        - chapters/eda/07_introduction_normal_distribution.qmd
        - chapters/eda/08_correlation.qmd
        - chapters/eda/09_propedeutic_causality.qmd
        - chapters/eda/10_causality.qmd
        - chapters/eda/11_outlier.qmd
        - chapters/eda/12_gauss.qmd

    - part: "Epilogo"
      chapters:
        - chapters/epiloque/epiloque.qmd

crossref:
  appendix-title: "Appendice"

toc: true
toc-depth: 2

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

format:
  html:
    code-fold: false
    code-summary: "Code show/hide"
    code-copy: hover
    code-link: true
    code-overflow: scroll
    code-block-bg: true
    # highlight-style: github
    # code-block-border-left: "#6C6C6C"
    theme: 
      light: 
        - cosmo
      dark: darkly
    mainfont: "system-ui"
    # max-width: 74ch
    # number-sections: true
    lang: it
    reader-mode: true
    # toc: true
    toc-title: "Sommario"
    # toc-expand: 2
    smooth-scroll: true
    footnotes-hover: true
    link-external-icon: true
    link-external-newwindow: true

  # Figure 
    fig-align: center
    fig-responsive: true
    fig-cap-location: bottom
    fig-format: png 
  
    # Matematica
    html-math-method:
      method: mathjax

  # Media
    lightbox: auto

execute:
  freeze: auto  # Skip re-executing unchanged code chunks
  echo: true  # Display code in the output document
  warning: false  # Suppress warnings in output
  message: false  # Suppress messages in output
  fig.width: 6  # Set figure width (in inches)
  fig.asp: 0.618  # Set figure aspect ratio (golden ratio for aesthetics)
  fig.retina: 2  # High resolution for retina displays
  fig.align: "center"  # Center-align all figures
  fig.show: "hold"  # Group multiple figures from a chunk
  options:
    width: 120            # allarga la console virtuale
    pillar.width: Inf      # disattiva il riassunto colonne
    tibble.width: Inf      # idem, per sicurezza

website:
  cookie-consent:
    type: express
    style: headline
    anonymize-ip: true
