# Pacchetti {#sec-r-packages}

## Introduzione {.unnumbered .unlisted}

I pacchetti R sono estensioni del linguaggio di programmazione statistica R. Questi pacchetti forniscono una raccolta di risorse che possono essere utilizzate per ampliare le funzionalità di base di R. Ogni pacchetto generalmente include:

- **Codice**: funzioni e script scritti in R (e talvolta in altri linguaggi come C++ o Fortran) che implementano specifiche analisi o strumenti.
- **Dati**: dataset di esempio o utili per testare e dimostrare le funzionalità del pacchetto.
- **Documentazione**: file descrittivi che spiegano come utilizzare il pacchetto, spesso in formato manuale o vignette (tutorial pratici).

I pacchetti R sono distribuiti e installati attraverso repository centralizzati, il più noto dei quali è CRAN (Comprehensive R Archive Network). CRAN garantisce la qualità e l’affidabilità dei pacchetti, sottoponendoli a controlli rigorosi prima della pubblicazione. 

La vasta disponibilità di pacchetti è una delle ragioni principali della popolarità di R.

::: {.callout-tip collapse=true}
## Prerequisiti

- Consultare [Introduction to Data Science: Data Wrangling and Visualization with R](https://rafalab.dfci.harvard.edu/dsbook-part-1/) [@irizarry2024introduction]
- Leggere [R for Data Science (2e)](https://r4ds.hadley.nz/).
:::


## Installare i pacchetti R

Quando installi R, vengono installati automaticamente alcuni pacchetti base. Tuttavia, hai la possibilità di aggiungere ulteriori pacchetti che trovi utili per i tuoi scopi. Questi pacchetti sono memorizzati sui server di R (mirror), e l’installazione di un nuovo pacchetto richiede una connessione internet al mirror CRAN che hai scelto durante l'installazione di R.

Per installare un pacchetto, utilizza il comando:

```R
install.packages("<nome_pacchetto>")
```

Sostituisci `<nome_pacchetto>` con il nome del pacchetto che desideri installare. Ad esempio, se vuoi installare il pacchetto **rio** (utile per importare i dati in R), puoi digitare:

```R
install.packages("rio")   # Non dimenticare le virgolette!
```

## Caricamento di un pacchetto

Ogni volta che avvii una nuova sessione di R, se desideri utilizzare un pacchetto, devi caricarlo manualmente. Questo si fa con il comando `library()`. Ad esempio, dopo aver installato **rio**, per utilizzarlo digita:

```R
library(rio)   # Nota: le virgolette non sono necessarie, ma puoi usarle se preferisci.
```

## Utilizzo delle funzioni di un pacchetto senza caricarlo

Se hai bisogno di utilizzare una funzione specifica di un pacchetto, ma sai che la userai solo una volta, puoi evitare di caricare l'intero pacchetto con `library()`. Ad esempio, invece di scrivere:

```R
library(nome_pacchetto)
funzione_specifica(x = 2, sd = 3)
```

puoi accedere direttamente alla funzione usando l’operatore `::`, come indicato di segtuito:

```R
nome_pacchetto::funzione_specifica(x = 2, sd = 3)
```

Questo approccio è utile per funzioni che usi raramente o una sola volta. Personalmente, utilizzo `::` anche quando ho già caricato il pacchetto, per ricordare ad un "me futuro" da quale pacchetto proviene una determinata funzione. Questo può rendere il codice più leggibile e comprensibile nel tempo.


## Bibliografia {.unnumbered}

