<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>19&nbsp; Introduzione alla distribuzione normale – Analisi esplorativa dei dati in psicologia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/eda/08_correlation.html" rel="next">
<link href="../../chapters/eda/06_loc_scale.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-aa873432a3c62897e6c2091c0d30a948.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"it"
  });
});
</script> 
  
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../style/custom.css">
<meta property="og:title" content="19&nbsp; Introduzione alla distribuzione normale – Analisi esplorativa dei dati in psicologia">
<meta property="og:description" content="">
<meta property="og:image" content="https://ccaudek.github.io/utet-eda/chapters/eda/07_introduction_normal_distribution_files/figure-html/fig-qi-distribution-1.png">
<meta property="og:site_name" content="Analisi esplorativa dei dati in psicologia">
<meta property="og:image:height" content="1297">
<meta property="og:image:width" content="2100">
<meta name="twitter:title" content="19&nbsp; Introduzione alla distribuzione normale – Analisi esplorativa dei dati in psicologia">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://ccaudek.github.io/utet-eda/chapters/eda/07_introduction_normal_distribution_files/figure-html/fig-qi-distribution-1.png">
<meta name="twitter:image-height" content="1297">
<meta name="twitter:image-width" content="2100">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://ccaudek.github.io/utet-eda/chapters/eda/07_introduction_normal_distribution.html">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/eda/introduction_eda.html">EDA</a></li><li class="breadcrumb-item"><a href="../../chapters/eda/07_introduction_normal_distribution.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Introduzione alla distribuzione normale</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Analisi esplorativa dei dati in psicologia</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/ccaudek/utet-eda/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Ricerca"></div>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Analisi esplorativa dei dati in psicologia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/key_notions/introduction_key_notions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fondamenti</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/02_key_notions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Concetti chiave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/03_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Campionamento, metodologia sperimentale e studi osservazionali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/04_measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">La misurazione in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/key_notions/05_cognitive_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dalla descrizione alla spiegazione</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/R/introduction_r_lang.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/01_r_syntax.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Un approccio moderno all’analisi dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/02_environment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">L’ambiente di programmazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/03_utility_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Funzioni di utilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/04_r_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Programmazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/05_dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Usare <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/06_ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Visualizzazione dei dati con ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/07_quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/R/08_r_packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Pacchetti</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/eda/introduction_eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EDA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/01_project_structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Il ciclo di vita di un progetto di analisi dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/02_data_cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Flusso di lavoro per la pulizia dei dati</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/03_exploring_univariate_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Esplorare distribuzioni univariate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/05_data_visualization_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Principi della visualizzazione scientifica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/06_loc_scale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Indicatori di tendenza centrale e variabilità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/07_introduction_normal_distribution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Introduzione alla distribuzione normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/08_correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Relazioni tra variabili</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/09_causality_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Dalla correlazione alla causalità</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/eda/11_outlier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Outlier</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni conclusive</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
  <li><a href="#sec-why-normal" id="toc-sec-why-normal" class="nav-link active" data-scroll-target="#sec-why-normal"><span class="header-section-number">19.1</span> Perché la distribuzione normale è fondamentale in psicologia</a></li>
  <li><a href="#sec-normal-distribution" id="toc-sec-normal-distribution" class="nav-link" data-scroll-target="#sec-normal-distribution"><span class="header-section-number">19.2</span> La distribuzione normale: definizione e proprietà</a></li>
  <li><a href="#sec-empirical-rule" id="toc-sec-empirical-rule" class="nav-link" data-scroll-target="#sec-empirical-rule"><span class="header-section-number">19.3</span> La regola empirica 68–95–99.7</a></li>
  <li><a href="#sec-height-example" id="toc-sec-height-example" class="nav-link" data-scroll-target="#sec-height-example"><span class="header-section-number">19.4</span> Un esempio pratico completo: altezza maschile</a></li>
  <li><a href="#sec-z-scores" id="toc-sec-z-scores" class="nav-link" data-scroll-target="#sec-z-scores"><span class="header-section-number">19.5</span> Z-scores: standardizzazione e confronti</a></li>
  <li><a href="#sec-qq-plots" id="toc-sec-qq-plots" class="nav-link" data-scroll-target="#sec-qq-plots"><span class="header-section-number">19.6</span> Verificare la normalità: QQ-plots</a></li>
  <li><a href="#sec-bridge-to-inference" id="toc-sec-bridge-to-inference" class="nav-link" data-scroll-target="#sec-bridge-to-inference"><span class="header-section-number">19.7</span> Ponte verso la modellazione bayesiana</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-eda/blob/main/chapters/eda/07_introduction_normal_distribution.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-eda/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/eda/introduction_eda.html">EDA</a></li><li class="breadcrumb-item"><a href="../../chapters/eda/07_introduction_normal_distribution.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Introduzione alla distribuzione normale</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-eda-intro-gauss" class="quarto-section-identifier"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Introduzione alla distribuzione normale</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>La distribuzione normale (o gaussiana) rappresenta il ponte concettuale tra la statistica descrittiva e quella inferenziale. In questo capitolo esploreremo perché questa distribuzione è così centrale in psicologia, come riconoscerla nei dati, e perché media e deviazione standard diventano particolarmente utili quando i dati seguono approssimativamente questa forma. Questo capitolo fornisce le basi intuitive necessarie per comprendere i test statistici e gli intervalli di confidenza che studieremo nei capitoli successivi. Gli aspetti formali della distribuzione normale verranno approfonditi nel companion sulla teoria della probabilità.</p>
</div>
</div>
</div>
<section id="panoramica-del-capitolo" class="level3 unnumbered unlisted">
<h3 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h3>
<ul>
<li><strong>Perché la distribuzione normale è importante in psicologia</strong>: collegamenti con test, questionari e fenomeni naturali.</li>
<li><strong>Proprietà visive fondamentali</strong>: la regola empirica 68-95-99.7 e il suo significato pratico.</li>
<li><strong>Z-scores e standardizzazione</strong>: come confrontare valori su scale diverse.</li>
<li><strong>Verifica della normalità</strong>: QQ-plots come strumento diagnostico.</li>
<li><strong>Ponte verso l’inferenza</strong>: come la normale prepara ai concetti inferenziali.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Prerequisiti
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Leggere il capitolo <a href="https://openintro-ims.netlify.app/explore-numerical">Exploring numerical data</a> di <a href="https://openintro-ims.netlify.app">Introduction to Modern Statistics (2e)</a> di Mine Çetinkaya-Rundel e Johanna Hardin.</li>
<li>Leggere il capitolo <em>Distributions</em> di <em>Introduction to Data Science</em> <span class="citation" data-cites="irizarry2024introduction">(<a href="#ref-irizarry2024introduction" role="doc-biblioref">Irizarry, 2024</a>)</span>.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Preparazione del Notebook">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Attenzione</span>Preparazione del Notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"code"</span>, <span class="st">"_common.R"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">source</span>()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"pacman"</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(ggbeeswarm, dslabs, gridExtra, patchwork) </span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-why-normal" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="sec-why-normal"><span class="header-section-number">19.1</span> Perché la distribuzione normale è fondamentale in psicologia</h2>
<p>Prima di analizzarne le proprietà matematiche, è importante comprendere <strong>perché la distribuzione normale occupi una posizione centrale nella ricerca psicologica</strong>, in particolare nell’ambito della psicometria e della valutazione standardizzata.</p>
<section id="la-distribuzione-normale-nella-psicometria" class="level3" data-number="19.1.1">
<h3 data-number="19.1.1" class="anchored" data-anchor-id="la-distribuzione-normale-nella-psicometria"><span class="header-section-number">19.1.1</span> La distribuzione normale nella psicometria</h3>
<p>Gran parte dei test psicologici standardizzati è progettata in modo tale che i punteggi, all’interno della popolazione di riferimento, seguano <strong>approssimativamente una distribuzione normale</strong>. Questa scelta non è casuale, ma risponde a precise esigenze teoriche e pratiche.</p>
<p>Esempi rilevanti includono:</p>
<ul>
<li><strong>Test di intelligenza (QI)</strong>, calibrati per avere una media pari a 100 e una deviazione standard di 15, così da facilitare il confronto tra individui e gruppi;</li>
<li><strong>Misure di personalità</strong>, come le dimensioni del modello dei Big Five, che in popolazioni non cliniche tendono a distribuirsi in modo simmetrico intorno a un valore centrale;</li>
<li><strong>Questionari clinici</strong>, quali il <em>Beck Depression Inventory</em> (BDI) o lo <em>State-Trait Anxiety Inventory</em> (STAI), ampiamente utilizzati per la valutazione dei sintomi affettivi;</li>
<li><strong>Batterie neuropsicologiche</strong>, impiegate per misurare funzioni cognitive come memoria, attenzione e funzioni esecutive, spesso normalizzate su campioni rappresentativi.</li>
</ul>
<p>In tutti questi casi, l’assunzione di normalità consente di <strong>interpretare i punteggi individuali in termini relativi</strong>, collocandoli rispetto alla popolazione di riferimento mediante percentili, punteggi <span class="math inline">\(z\)</span> o punteggi standardizzati. Questo rende possibile un confronto informativo e clinicamente rilevante tra soggetti, contesti e momenti di valutazione diversi.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simuliamo la distribuzione del QI</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>qi_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">QI =</span> <span class="fu">seq</span>(<span class="dv">55</span>, <span class="dv">145</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">densita =</span> <span class="fu">dnorm</span>(QI, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">15</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(qi_data, <span class="fu">aes</span>(<span class="at">x =</span> QI, <span class="at">y =</span> densita)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">100</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">100</span>, <span class="at">y =</span> <span class="fl">0.02</span>, <span class="at">label =</span> <span class="st">"Media = 100"</span>, </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribuzione dei punteggi di QI"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Media = 100, Deviazione Standard = 15"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Punteggio QI"</span>, </span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densità"</span>) </span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-qi-distribution" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qi-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-qi-distribution-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;19.1: Distribuzione teorica dei punteggi di QI nella popolazione"><img src="07_introduction_normal_distribution_files/figure-html/fig-qi-distribution-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qi-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.1: Distribuzione teorica dei punteggi di QI nella popolazione
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fenomeni-naturali-e-biologici" class="level3" data-number="19.1.2">
<h3 data-number="19.1.2" class="anchored" data-anchor-id="fenomeni-naturali-e-biologici"><span class="header-section-number">19.1.2</span> Fenomeni naturali e biologici</h3>
<p>Numerose variabili biologiche e comportamentali mostrano una <strong>distribuzione approssimativamente normale</strong> quando osservate in popolazioni sufficientemente ampie. Tra gli esempi più comuni rientrano:</p>
<ul>
<li><strong>Misure antropometriche</strong>, come altezza, peso o circonferenza cranica;</li>
<li><strong>Tempi di reazione</strong>, in particolare in compiti cognitivi semplici e ben controllati;</li>
<li><strong>Errori di misurazione</strong>, tipici degli esperimenti di laboratorio;</li>
<li><strong>Variabilità interindividuale</strong> in molti processi psicologici di base, quali velocità di elaborazione, attenzione o memoria di lavoro.</li>
</ul>
<p>Questa regolarità non è casuale. Quando una variabile osservata è il risultato dell’azione combinata di <strong>numerosi fattori in larga parte indipendenti</strong> — genetici, ambientali e casuali — ciascuno dei quali contribuisce con un effetto relativamente piccolo, la distribuzione complessiva tende a convergere verso la forma normale. Questo principio, formalizzato nel <strong>Teorema del Limite Centrale</strong>, rappresenta uno dei pilastri teorici della statistica moderna e costituisce il fondamento di molte tecniche di inferenza utilizzate in psicologia.</p>
</section>
<section id="la-distribuzione-normale-come-modello-fondamentale-nella-modellazione-bayesiana" class="level3" data-number="19.1.3">
<h3 data-number="19.1.3" class="anchored" data-anchor-id="la-distribuzione-normale-come-modello-fondamentale-nella-modellazione-bayesiana"><span class="header-section-number">19.1.3</span> La distribuzione normale come modello fondamentale nella modellazione bayesiana</h3>
<p>Anche nell’ambito dell’<strong>inferenza bayesiana</strong>, la distribuzione normale occupa una posizione centrale, sebbene con ruoli e interpretazioni in parte differenti rispetto all’approccio frequentista. La sua importanza deriva sia da considerazioni matematiche sia da esigenze di modellazione pratica.</p>
<p>In particolare:</p>
<ul>
<li><strong>Priors e likelihood</strong>: la distribuzione normale è spesso impiegata come <em>prior coniugato</em> per molti parametri di interesse e come <em>likelihood</em> per dati continui. Questa scelta consente, in numerosi casi, di ottenere posteriori in forma chiusa o comunque facilmente trattabili dal punto di vista analitico.</li>
<li><strong>Regolarizzazione bayesiana</strong>: l’uso di <em>prior</em> normali (ad esempio nella regressione ridge bayesiana) introduce una forma naturale di regolarizzazione, che riduce la varianza delle stime e contribuisce a prevenire il sovradattamento.</li>
<li><strong>Modelli gerarchici</strong>: la distribuzione normale è fondamentale per modellare la variabilità tra gruppi attraverso effetti casuali, costituendo il nucleo di molte strutture gerarchiche e multilevel.</li>
<li><strong>Approssimazioni della distribuzione a posteriori</strong>: numerosi metodi di inferenza approssimata, come la <em>Laplace approximation</em> o la <em>Variational Bayes</em>, assumono che la distribuzione a posteriori sia ben approssimabile da una normale, sfruttandone le proprietà di concentrazione e simmetria.</li>
</ul>
<p>Comprendere a fondo le proprietà della distribuzione normale è quindi essenziale per costruire <strong>modelli bayesiani robusti</strong>, interpretare correttamente i <em>prior</em> coniugati e implementare algoritmi di inferenza efficienti. Nel contesto bayesiano, la normale non rappresenta tanto un’“assunzione da verificare”, quanto piuttosto una <strong>scelta di modellazione flessibile e matematicamente conveniente</strong>, da adottare consapevolmente in funzione del problema di ricerca.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>La normale come modello, non come legge assoluta
</div>
</div>
<div class="callout-body-container callout-body">
<p>È cruciale ricordare che <strong>i dati reali raramente seguono perfettamente una distribuzione normale</strong>. La distribuzione normale rappresenta un <em>modello matematico</em> che approssima in modo utile molti fenomeni reali. L’obiettivo non è quindi trovare dati “perfettamente normali”, ma valutare se l’approssimazione normale è sufficientemente buona per gli scopi specifici della nostra analisi.</p>
</div>
</div>
</section>
</section>
<section id="sec-normal-distribution" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="sec-normal-distribution"><span class="header-section-number">19.2</span> La distribuzione normale: definizione e proprietà</h2>
<p>La <strong>distribuzione normale</strong>, detta anche <strong>distribuzione gaussiana</strong> o <strong>curva a campana</strong>, è una distribuzione di probabilità continua caratterizzata da una forma <strong>unimodale</strong>, <strong>perfettamente simmetrica</strong> e definita su tutto l’insieme dei numeri reali. Essa riveste un ruolo centrale nella statistica teorica e applicata, nonché nelle scienze psicologiche e comportamentali.</p>
<p>La distribuzione normale è completamente determinata da due parametri:</p>
<ul>
<li><strong><span class="math inline">\(\mu\)</span> (mu)</strong>: la <strong>media</strong> della distribuzione, che ne individua il centro e coincide con il valore di massima densità;</li>
<li><strong><span class="math inline">\(\sigma\)</span> (sigma)</strong>: la <strong>deviazione standard</strong>, che misura la dispersione dei valori intorno alla media e controlla l’ampiezza della distribuzione.</li>
</ul>
<p>Questi due parametri sono sufficienti a descrivere sia la posizione sia la variabilità della distribuzione, rendendo la normale un modello matematico particolarmente semplice e al tempo stesso estremamente versatile.</p>
<section id="rappresentazione-visiva" class="level3" data-number="19.2.1">
<h3 data-number="19.2.1" class="anchored" data-anchor-id="rappresentazione-visiva"><span class="header-section-number">19.2.1</span> Rappresentazione visiva</h3>
<p>Ecco come appare la distribuzione normale con diversi valori di <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-normal-params-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-params-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-normal-params-1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figura&nbsp;19.2: Effetto del parametro μ sulla forma della distribuzione normale"><img src="07_introduction_normal_distribution_files/figure-html/fig-normal-params-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-params-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.2: Effetto del parametro μ sulla forma della distribuzione normale
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-normal-params-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-params-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-normal-params-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figura&nbsp;19.3: Effetto del parametro σ sulla forma della distribuzione normale"><img src="07_introduction_normal_distribution_files/figure-html/fig-normal-params-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-params-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.3: Effetto del parametro σ sulla forma della distribuzione normale
</figcaption>
</figure>
</div>
</div>
</div>
<p>Come si può osservare:</p>
<ul>
<li><strong>la media <span class="math inline">\(\mu\)</span></strong> sposta la curva a destra o a sinistra lungo l’asse <span class="math inline">\(x\)</span>;</li>
<li><strong>la deviazione standard <span class="math inline">\(\sigma\)</span></strong> controlla quanto la curva è “allargata”:
<ul>
<li><span class="math inline">\(\sigma\)</span> piccolo → curva alta e stretta (dati concentrati vicino alla media)</li>
<li><span class="math inline">\(\sigma\)</span> grande → curva bassa e larga (dati più dispersi).</li>
</ul></li>
</ul>
</section>
<section id="proprietà-fondamentali" class="level3" data-number="19.2.2">
<h3 data-number="19.2.2" class="anchored" data-anchor-id="proprietà-fondamentali"><span class="header-section-number">19.2.2</span> Proprietà fondamentali</h3>
<p>La distribuzione normale presenta alcune proprietà strutturali fondamentali che ne definiscono il comportamento e ne giustificano l’uso diffuso come modello di riferimento:</p>
<ol type="1">
<li><strong>Simmetria</strong>: la distribuzione è perfettamente simmetrica rispetto alla media <span class="math inline">\(\mu\)</span>; per ogni valore a distanza <span class="math inline">\(d\)</span> dalla media esiste un valore equiprobabile a distanza <span class="math inline">\(-d\)</span>.</li>
<li><strong>Unimodalità</strong>: la distribuzione presenta un unico massimo (moda), che coincide con il punto di massima densità.</li>
<li><strong>Asintoticità</strong>: le code della distribuzione si estendono indefinitamente verso <span class="math inline">\(+\infty\)</span> e <span class="math inline">\(-\infty\)</span> senza mai intersecare l’asse delle ascisse.</li>
<li><strong>Coincidenza degli indici di posizione</strong>: in una distribuzione normale, <strong>media, mediana e moda coincidono</strong>, riflettendo l’equilibrio perfetto della distribuzione.</li>
</ol>
<p>Queste proprietà rendono la distribuzione normale un riferimento ideale per descrivere fenomeni continui caratterizzati da variabilità simmetrica attorno a un valore centrale.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Nota matematica
</div>
</div>
<div class="callout-body-container callout-body">
<p>La forma precisa della distribuzione normale è definita da una funzione matematica (la funzione di densità) che coinvolge <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma\)</span>, e alcune costanti matematiche (π, e). I dettagli di questa funzione e le sue proprietà formali saranno approfonditi nel companion sulla teoria della probabilità. Per ora, è sufficiente sapere che <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span> determinano completamente la forma della distribuzione.</p>
</div>
</div>
</section>
</section>
<section id="sec-empirical-rule" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="sec-empirical-rule"><span class="header-section-number">19.3</span> La regola empirica 68–95–99.7</h2>
<p>Una delle proprietà più note e utili della distribuzione normale è la <strong>regola empirica</strong> (o regola <em>68–95–99.7</em>), che fornisce una descrizione intuitiva di come i valori si distribuiscono attorno alla media in funzione della <strong>deviazione standard</strong>.</p>
<p>Questa regola permette di comprendere rapidamente quanta parte dei dati ci si aspetta di osservare vicino al valore centrale, senza ricorrere a calcoli complessi o a tabelle di probabilità.</p>
<section id="la-regola-in-numeri" class="level3" data-number="19.3.1">
<h3 data-number="19.3.1" class="anchored" data-anchor-id="la-regola-in-numeri"><span class="header-section-number">19.3.1</span> La regola in numeri</h3>
<p>Per <strong>qualsiasi distribuzione normale</strong>, indipendentemente dai valori specifici della media <span class="math inline">\(\mu\)</span> e della deviazione standard <span class="math inline">\(\sigma\)</span>:</p>
<ul>
<li>circa il <strong>68%</strong> delle osservazioni ricade entro <strong>una deviazione standard</strong> dalla media, nell’intervallo <span class="math inline">\([\mu - \sigma, \mu + \sigma]\)</span>;</li>
<li>circa il <strong>95%</strong> delle osservazioni si trova entro <strong>due deviazioni standard</strong> dalla media, nell’intervallo <span class="math inline">\([\mu - 2\sigma, \mu + 2\sigma]\)</span>;</li>
<li>circa il <strong>99.7%</strong> delle osservazioni cade entro <strong>tre deviazioni standard</strong> dalla media, nell’intervallo <span class="math inline">\([\mu - 3\sigma, \mu + 3\sigma]\)</span>.</li>
</ul>
<p>Queste proporzioni forniscono una guida pratica per interpretare la variabilità dei dati e per valutare quanto un’osservazione sia tipica o estrema rispetto alla distribuzione di riferimento.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-empirical-rule" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-empirical-rule-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-empirical-rule-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figura&nbsp;19.4: La regola empirica 68-95-99.7 per la distribuzione normale"><img src="07_introduction_normal_distribution_files/figure-html/fig-empirical-rule-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-empirical-rule-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.4: La regola empirica 68-95-99.7 per la distribuzione normale
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="applicazione-pratica-test-del-qi" class="level3" data-number="19.3.2">
<h3 data-number="19.3.2" class="anchored" data-anchor-id="applicazione-pratica-test-del-qi"><span class="header-section-number">19.3.2</span> Applicazione pratica: Test del QI</h3>
<p>Riprendiamo l’esempio dei punteggi di QI (media = 100, deviazione standard = 15). Applicando la regola empirica otteniamo:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Applicazione della regola empirica ai punteggi di QI</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Intervallo</th>
<th style="text-align: left;">Limiti</th>
<th style="text-align: left;">Percentuale</th>
<th style="text-align: left;">Interpretazione</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">μ ± 1σ</td>
<td style="text-align: left;">85 - 115</td>
<td style="text-align: left;">68%</td>
<td style="text-align: left;">La maggior parte delle persone</td>
</tr>
<tr class="even">
<td style="text-align: left;">μ ± 2σ</td>
<td style="text-align: left;">70 - 130</td>
<td style="text-align: left;">95%</td>
<td style="text-align: left;">Quasi tutte le persone</td>
</tr>
<tr class="odd">
<td style="text-align: left;">μ ± 3σ</td>
<td style="text-align: left;">55 - 145</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">Praticamente tutta la popolazione</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Questo significa che:</p>
<ul>
<li>circa il 68% della popolazione ha un QI tra 85 e 115;</li>
<li>circa il 95% della popolazione ha un QI tra 70 e 130;</li>
<li>solo circa il 2.5% ha un QI superiore a 130 (superdotati);</li>
<li>solo circa il 2.5% ha un QI inferiore a 70 (difficoltà cognitive).</li>
</ul>
</section>
<section id="verifica-empirica-con-dati-reali" class="level3" data-number="19.3.3">
<h3 data-number="19.3.3" class="anchored" data-anchor-id="verifica-empirica-con-dati-reali"><span class="header-section-number">19.3.3</span> Verifica empirica con dati reali</h3>
<p>Vediamo se la regola empirica si applica effettivamente a un dataset reale. Useremo ancora le altezze maschili dal dataset <code>heights</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estraiamo le altezze maschili</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> dslabs<span class="sc">::</span>heights<span class="sc">$</span>sex <span class="sc">==</span> <span class="st">"Male"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> dslabs<span class="sc">::</span>heights<span class="sc">$</span>height[index]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcoliamo media e deviazione standard</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media:"</span>, <span class="fu">round</span>(m, <span class="dv">2</span>), <span class="st">"cm</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Media: 69.3 cm</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Deviazione standard:"</span>, <span class="fu">round</span>(s, <span class="dv">2</span>), <span class="st">"cm</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Deviazione standard: 3.61 cm</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Verifichiamo la regola empirica</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>prop_1sd <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(x <span class="sc">-</span> m) <span class="sc">&lt;=</span> <span class="dv">1</span><span class="sc">*</span>s)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>prop_2sd <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(x <span class="sc">-</span> m) <span class="sc">&lt;=</span> <span class="dv">2</span><span class="sc">*</span>s)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>prop_3sd <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(x <span class="sc">-</span> m) <span class="sc">&lt;=</span> <span class="dv">3</span><span class="sc">*</span>s)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>risultati_empirici <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Intervallo =</span> <span class="fu">c</span>(<span class="st">"μ ± 1σ"</span>, <span class="st">"μ ± 2σ"</span>, <span class="st">"μ ± 3σ"</span>),</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Teorico =</span> <span class="fu">c</span>(<span class="st">"68%"</span>, <span class="st">"95%"</span>, <span class="st">"99.7%"</span>),</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">Osservato =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(<span class="fu">c</span>(prop_1sd, prop_2sd, prop_3sd) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%"</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(risultati_empirici,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Confronto tra proporzioni teoriche e osservate"</span>)</span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Confronto tra proporzioni teoriche e osservate</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Intervallo</th>
<th style="text-align: left;">Teorico</th>
<th style="text-align: left;">Osservato</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">μ ± 1σ</td>
<td style="text-align: left;">68%</td>
<td style="text-align: left;">76%</td>
</tr>
<tr class="even">
<td style="text-align: left;">μ ± 2σ</td>
<td style="text-align: left;">95%</td>
<td style="text-align: left;">95%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">μ ± 3σ</td>
<td style="text-align: left;">99.7%</td>
<td style="text-align: left;">99.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Come si può vedere, le proporzioni osservate sono molto vicine a quelle teoriche, confermando che l’altezza maschile segue approssimativamente una distribuzione normale.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Implicazione pratica
</div>
</div>
<div class="callout-body-container callout-body">
<p>La regola empirica consente di attribuire un significato immediato alla <strong>deviazione standard</strong>: essa rappresenta, in modo approssimato, la distanza dalla media entro cui si colloca circa il <strong>68% delle osservazioni</strong>. In questo modo, un parametro che appare inizialmente astratto nella sua formulazione matematica acquisisce un’interpretazione concreta e intuitiva, rendendo la deviazione standard uno strumento descrittivo molto più informativo di quanto possa sembrare a prima vista.</p>
</div>
</div>
</section>
</section>
<section id="sec-height-example" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="sec-height-example"><span class="header-section-number">19.4</span> Un esempio pratico completo: altezza maschile</h2>
<p>Integriamo i concetti presentati finora con un esempio pratico. Consideriamo il problema di descrivere la distribuzione delle altezze nella popolazione maschile adulta, modellizzabile tramite una distribuzione normale.</p>
<section id="stima-dei-parametri" class="level3" data-number="19.4.1">
<h3 data-number="19.4.1" class="anchored" data-anchor-id="stima-dei-parametri"><span class="header-section-number">19.4.1</span> Stima dei parametri</h3>
<p>Estraiamo i dati e calcoliamo media e deviazione standard:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> dslabs<span class="sc">::</span>heights<span class="sc">$</span>sex <span class="sc">==</span> <span class="st">"Male"</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> dslabs<span class="sc">::</span>heights<span class="sc">$</span>height[index]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media:"</span>, <span class="fu">round</span>(m, <span class="dv">2</span>), <span class="st">"cm</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Media: 69.3 cm</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Deviazione standard:"</span>, <span class="fu">round</span>(s, <span class="dv">2</span>), <span class="st">"cm</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Deviazione standard: 3.61 cm</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Avviso
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Nota tecnica</strong>: La funzione <code>sd(x)</code> effettua una divisione per <span class="math inline">\(n - 1\)</span> invece che per <span class="math inline">\(n\)</span> (dove <span class="math inline">\(n\)</span> è il numero di osservazioni). Questa correzione, chiamata <em>correzione di Bessel</em>, serve per ottenere una stima non distorta della deviazione standard della popolazione. Quando il numero di osservazioni è elevato, la differenza tra dividere per <span class="math inline">\(n\)</span> o per <span class="math inline">\(n-1\)</span> è trascurabile. Approfondiremo questo aspetto quando studieremo la stima dei parametri.</p>
</div>
</div>
</section>
<section id="confronto-visivo" class="level3" data-number="19.4.2">
<h3 data-number="19.4.2" class="anchored" data-anchor-id="confronto-visivo"><span class="header-section-number">19.4.2</span> Confronto visivo</h3>
<p>Possiamo ora confrontare la distribuzione osservata (in blu) con la distribuzione normale teorica (in nero):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>norm_dist <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">seq</span>(m <span class="sc">-</span> <span class="dv">4</span><span class="sc">*</span>s, m <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span>s, <span class="at">length.out =</span> <span class="dv">100</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">density =</span> <span class="fu">dnorm</span>(x, m, s))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>dslabs<span class="sc">::</span>heights <span class="sc">|&gt;</span> </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(height)) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(x, density), <span class="at">linewidth =</span> <span class="fl">1.5</span>, </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> norm_dist, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribuzione delle altezze maschili"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Densità osservata (blu) vs. normale teorica (nero)"</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Altezza (cm)"</span>, </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densità"</span>) </span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-altezza-normale" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-altezza-normale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-altezza-normale-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figura&nbsp;19.5: Confronto tra distribuzione osservata delle altezze maschili e distribuzione normale teorica"><img src="07_introduction_normal_distribution_files/figure-html/fig-altezza-normale-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-altezza-normale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.5: Confronto tra distribuzione osservata delle altezze maschili e distribuzione normale teorica
</figcaption>
</figure>
</div>
</div>
</div>
<p>La curva normale fornisce una buona approssimazione. Questo significa che possiamo descrivere efficacemente la distribuzione usando solo due numeri: media (69.3 cm) e deviazione standard (3.6 cm).</p>
</section>
</section>
<section id="sec-z-scores" class="level2" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="sec-z-scores"><span class="header-section-number">19.5</span> Z-scores: standardizzazione e confronti</h2>
<p>Quando si analizzano variabili misurate su <strong>scale diverse</strong> — ad esempio altezza in centimetri e peso in chilogrammi, oppure punteggi provenienti da test differenti — il confronto diretto dei valori grezzi risulta poco informativo o addirittura fuorviante. I <strong>punteggi standardizzati</strong>, comunemente noti come <em>z-scores</em>, forniscono una soluzione elegante a questo problema, consentendo di esprimere i dati su una <strong>scala comune</strong>.</p>
<section id="definizione-e-calcolo" class="level3" data-number="19.5.1">
<h3 data-number="19.5.1" class="anchored" data-anchor-id="definizione-e-calcolo"><span class="header-section-number">19.5.1</span> Definizione e calcolo</h3>
<p>Uno <em>z-score</em> indica di quante <strong>deviazioni standard</strong> un valore osservato si discosta dalla media della distribuzione di riferimento. Formalmente:</p>
<p><span class="math display">\[
z = \frac{x - \mu}{\sigma},
\]</span> dove:</p>
<ul>
<li><span class="math inline">\(x\)</span> è il valore osservato;</li>
<li><span class="math inline">\(\mu\)</span> è la media della distribuzione;</li>
<li><span class="math inline">\(\sigma\)</span> è la deviazione standard.</li>
</ul>
<p>Attraverso questa trasformazione, ogni osservazione viene ricollocata rispetto al centro e alla dispersione della distribuzione, rendendo i valori direttamente confrontabili.</p>
<p>In <strong>R</strong>, gli z-scores possono essere calcolati in modo semplice utilizzando la funzione <code>scale()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Z-scores delle altezze maschili</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">scale</span>(x) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Primi 10 z-scores:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Primi 10 z-scores:</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(z, <span class="dv">10</span>) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1]  1.57  0.19 -0.36  1.30 -2.30 -0.64  0.74  0.74 -0.09 -0.36</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Verifichiamo le proprietà</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Media degli z-scores:"</span>, <span class="fu">round</span>(<span class="fu">mean</span>(z), <span class="dv">10</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Media degli z-scores: 0</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Deviazione standard degli z-scores:"</span>, <span class="fu">round</span>(<span class="fu">sd</span>(z), <span class="dv">10</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Deviazione standard degli z-scores: 1</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="proprietà-fondamentali-degli-z-scores" class="level3" data-number="19.5.2">
<h3 data-number="19.5.2" class="anchored" data-anchor-id="proprietà-fondamentali-degli-z-scores"><span class="header-section-number">19.5.2</span> Proprietà fondamentali degli z-scores</h3>
<p>La standardizzazione presenta alcune proprietà chiave:</p>
<ol type="1">
<li>la <strong>media</strong> degli z-scores è sempre pari a 0;</li>
<li>la <strong>deviazione standard</strong> degli z-scores è sempre pari a 1;</li>
<li>la trasformazione preserva la <strong>forma della distribuzione originale</strong>, limitandosi a ricentrarla e riscalarla.</li>
</ol>
<p>Queste caratteristiche rendono gli z-scores particolarmente utili per confronti trasversali tra variabili diverse e per l’interpretazione relativa delle osservazioni.</p>
</section>
<section id="interpretazione-pratica" class="level3" data-number="19.5.3">
<h3 data-number="19.5.3" class="anchored" data-anchor-id="interpretazione-pratica"><span class="header-section-number">19.5.3</span> Interpretazione pratica</h3>
<p>Nel contesto di una distribuzione approssimativamente normale, gli z-scores possono essere interpretati in modo immediato:</p>
<ul>
<li><strong>z = 0</strong>: il valore coincide con la media;</li>
<li><strong>z = 1</strong>: il valore è una deviazione standard <em>sopra</em> la media;</li>
<li><strong>z = -1</strong>: il valore è una deviazione standard <em>sotto</em> la media;</li>
<li><strong>z = 2</strong>: il valore è due deviazioni standard sopra la media (circa nel <strong>2.5% superiore</strong> della distribuzione);</li>
<li><strong>z = -2</strong>: il valore è due deviazioni standard sotto la media (circa nel <strong>2.5% inferiore</strong> della distribuzione).</li>
</ul>
<p>In questo modo, gli z-scores permettono di tradurre valori grezzi in <strong>posizioni relative</strong> all’interno della distribuzione, facilitando l’interpretazione e il confronto tra individui, variabili e contesti di misurazione diversi.</p>
</section>
<section id="esempio-confronto-tra-test-diversi" class="level3" data-number="19.5.4">
<h3 data-number="19.5.4" class="anchored" data-anchor-id="esempio-confronto-tra-test-diversi"><span class="header-section-number">19.5.4</span> Esempio: confronto tra test diversi</h3>
<p>Supponiamo che uno studente abbia ottenuto i seguenti risultati:</p>
<ul>
<li><strong>QI = 115</strong>, in un test con media di popolazione pari a 100 e deviazione standard di 15;</li>
<li><strong>Punteggio di memoria = 65</strong>, in un test con media pari a 50 e deviazione standard di 10.</li>
</ul>
<p>La domanda è: <strong>in quale dei due test lo studente ha performato meglio in termini relativi rispetto alla popolazione di riferimento?</strong></p>
<p>Per rispondere, trasformiamo entrambi i punteggi in <strong>z-scores</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcolo degli z-scores</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>z_qi <span class="ot">&lt;-</span> (<span class="dv">115</span> <span class="sc">-</span> <span class="dv">100</span>) <span class="sc">/</span> <span class="dv">15</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>z_memoria <span class="ot">&lt;-</span> (<span class="dv">65</span> <span class="sc">-</span> <span class="dv">50</span>) <span class="sc">/</span> <span class="dv">10</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Z-score QI:"</span>, <span class="fu">round</span>(z_qi, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Z-score QI: 1</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Z-score Memoria:"</span>, <span class="fu">round</span>(z_memoria, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Z-score Memoria: 1.5</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (z_memoria <span class="sc">&gt;</span> z_qi) {</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Lo studente ha performato relativamente meglio nel test di memoria</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Lo studente ha performato relativamente meglio nel test di QI</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Lo studente ha performato relativamente meglio nel test di memoria</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Il punteggio di <strong>QI</strong> corrisponde a uno z-score pari a <strong>1.00</strong>, mentre il punteggio nel test di <strong>memoria</strong> corrisponde a uno z-score pari a <strong>1.50</strong>.</p>
<p>Sebbene i valori grezzi (115 e 65) non siano direttamente confrontabili a causa delle diverse scale di misura, gli z-scores consentono di esprimere entrambe le prestazioni sulla <strong>stessa scala standardizzata</strong>. In questo caso, lo studente ha ottenuto una performance <strong>relativamente migliore nel test di memoria</strong>, collocandosi più lontano dalla media della popolazione di riferimento.</p>
</section>
<section id="la-distribuzione-normale-standard" class="level3" data-number="19.5.5">
<h3 data-number="19.5.5" class="anchored" data-anchor-id="la-distribuzione-normale-standard"><span class="header-section-number">19.5.5</span> La distribuzione normale standard</h3>
<p>Quando si standardizza una variabile che segue una distribuzione normale con media <span class="math inline">\(\mu\)</span> e deviazione standard <span class="math inline">\(\sigma\)</span>, i corrispondenti <strong>z-scores</strong> seguono una <strong>distribuzione normale standard</strong>, caratterizzata da media pari a 0 e deviazione standard pari a 1. Questa distribuzione viene indicata come <span class="math inline">\(N(0, 1)\)</span> oppure, più sinteticamente, come <strong><span class="math inline">\(Z\)</span></strong>.</p>
<p>La standardizzazione non altera la forma della distribuzione: essa si limita a <strong>ricentrare</strong> i dati sulla media zero e a <strong>riscalarli</strong> in unità di deviazione standard. In questo modo, qualsiasi distribuzione normale può essere ricondotta a un’unica distribuzione di riferimento, rendendo possibili confronti diretti e calcoli probabilistici uniformi.</p>
<p>La figura seguente illustra visivamente questo processo, mostrando una distribuzione normale originale e la corrispondente distribuzione dopo la standardizzazione.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dati originali e standardizzati</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="at">originale =</span> x,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="at">standardizzato =</span> z</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> originale)) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> m, <span class="at">sd =</span> s),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribuzione originale"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"μ = "</span>, <span class="fu">round</span>(m, <span class="dv">1</span>), <span class="st">", σ = "</span>, <span class="fu">round</span>(s, <span class="dv">1</span>)),</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Altezza (cm)"</span>, <span class="at">y =</span> <span class="st">"Densità"</span>) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="at">t =</span> <span class="dv">12</span>, <span class="at">r =</span> <span class="dv">5</span>, <span class="at">b =</span> <span class="dv">5</span>, <span class="at">l =</span> <span class="dv">5</span>))</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> standardizzato)) <span class="sc">+</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Dopo standardizzazione"</span>,</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="at">subtitle =</span> <span class="st">"μ = 0, σ = 1"</span>,</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Z-score"</span>, <span class="at">y =</span> <span class="st">"Densità"</span>) <span class="sc">+</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="at">t =</span> <span class="dv">12</span>, <span class="at">r =</span> <span class="dv">5</span>, <span class="at">b =</span> <span class="dv">5</span>, <span class="at">l =</span> <span class="dv">5</span>))</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-standardization" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-standardization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-standardization-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figura&nbsp;19.6: Standardizzazione: da distribuzione normale a normale standard"><img src="07_introduction_normal_distribution_files/figure-html/fig-standardization-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-standardization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.6: Standardizzazione: da distribuzione normale a normale standard
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Collegamento con l’inferenza statistica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Gli z-scores costituiscono un elemento fondamentale dell’inferenza statistica:</p>
<ul>
<li>i <strong>test z</strong> utilizzano direttamente la distribuzione normale standard per il calcolo delle probabilità;</li>
<li>i <strong>valori-<span class="math inline">\(p\)</span></strong> sono spesso ottenuti convertendo una statistica test in uno z-score;</li>
<li>gli <strong>intervalli di confidenza</strong> si basano sulla distribuzione degli z-scores e sui relativi quantili.</li>
</ul>
<p>Una comprensione solida della distribuzione normale standard e degli z-scores fornisce quindi le basi concettuali necessarie per affrontare con maggiore consapevolezza i metodi inferenziali che verranno introdotti nei capitoli successivi.</p>
</div>
</div>
</section>
</section>
<section id="sec-qq-plots" class="level2" data-number="19.6">
<h2 data-number="19.6" class="anchored" data-anchor-id="sec-qq-plots"><span class="header-section-number">19.6</span> Verificare la normalità: QQ-plots</h2>
<p>Un metodo sistematico per valutare se i dati seguono approssimativamente una distribuzione normale è il <strong>QQ-plot</strong> (<em>Quantile-Quantile plot</em>), che confronta i quantili empirici dei dati con i quantili teorici di una distribuzione normale di riferimento.</p>
<section id="principio-di-funzionamento-del-qq-plot" class="level3" data-number="19.6.1">
<h3 data-number="19.6.1" class="anchored" data-anchor-id="principio-di-funzionamento-del-qq-plot"><span class="header-section-number">19.6.1</span> Principio di funzionamento del QQ-plot</h3>
<p>Il QQ-plot si costruisce seguendo questi passaggi:</p>
<ol type="1">
<li>si ordinano i dati in senso crescente;</li>
<li>per ogni osservazione, si calcola la sua posizione percentile empirica;</li>
<li>si determinano i corrispondenti quantili teorici di una distribuzione normale standard;</li>
<li>si rappresentano in un grafico i punti (quantile teorico, quantile osservato).</li>
</ol>
<p><strong>Se i dati seguono una distribuzione normale</strong>, i punti si disporranno approssimativamente lungo una retta diagonale.</p>
</section>
<section id="creazione-di-un-qq-plot-in-r" class="level3" data-number="19.6.2">
<h3 data-number="19.6.2" class="anchored" data-anchor-id="creazione-di-un-qq-plot-in-r"><span class="header-section-number">19.6.2</span> Creazione di un QQ-plot in R</h3>
<p>Con <code>ggplot2</code>, un QQ-plot può essere generato nel modo seguente:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dslabs<span class="sc">::</span>heights <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> height)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"QQ-plot: altezze maschili"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Quantili teorici (normale)"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Quantili osservati (dati)"</span>) </span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-qqplot-altezze" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qqplot-altezze-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-qqplot-altezze-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figura&nbsp;19.7: QQ-plot per le altezze maschili"><img src="07_introduction_normal_distribution_files/figure-html/fig-qqplot-altezze-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qqplot-altezze-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.7: QQ-plot per le altezze maschili
</figcaption>
</figure>
</div>
</div>
</div>
<p>In questo caso, i punti si allineano bene lungo la linea rossa, confermando che la distribuzione delle altezze maschili è approssimativamente normale.</p>
</section>
<section id="interpretare-deviazioni-dalla-normalità" class="level3" data-number="19.6.3">
<h3 data-number="19.6.3" class="anchored" data-anchor-id="interpretare-deviazioni-dalla-normalità"><span class="header-section-number">19.6.3</span> Interpretare deviazioni dalla normalità</h3>
<p>Il QQ-plot rivela diversi tipi di non-normalità.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-qqplot-patterns" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qqplot-patterns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="07_introduction_normal_distribution_files/figure-html/fig-qqplot-patterns-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figura&nbsp;19.8: Patterns comuni nei QQ-plots e la loro interpretazione"><img src="07_introduction_normal_distribution_files/figure-html/fig-qqplot-patterns-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qqplot-patterns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19.8: Patterns comuni nei QQ-plots e la loro interpretazione
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Come interpretare i pattern:</strong></p>
<ul>
<li><strong>Punti sulla linea</strong>: distribuzione normale ✓</li>
<li><strong>Curva a S</strong>: asimmetria (skewness)</li>
<li><strong>Punti che si allontanano agli estremi</strong>: code pesanti (più outlier del previsto)</li>
<li><strong>Punti che si avvicinano agli estremi</strong>: code leggere (meno variabilità del previsto)</li>
</ul>
</section>
<section id="test-formali-di-normalità" class="level3" data-number="19.6.4">
<h3 data-number="19.6.4" class="anchored" data-anchor-id="test-formali-di-normalità"><span class="header-section-number">19.6.4</span> Test formali di normalità</h3>
<p>Oltre ai QQ-plots, esistono test statistici formali per verificare la normalità. Il più comune è il <strong>test di Shapiro-Wilk</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test di Shapiro-Wilk</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(x)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Test di Shapiro-Wilk</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Test di Shapiro-Wilk</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Statistica W:"</span>, <span class="fu">round</span>(shapiro_test<span class="sc">$</span>statistic, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Statistica W: 0.964</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P-value:"</span>, <span class="fu">round</span>(shapiro_test<span class="sc">$</span>p.value, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; P-value: 0</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (shapiro_test<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Interpretazione: I dati non mostrano deviazioni significative dalla normalità</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Interpretazione: I dati mostrano deviazioni significative dalla normalità</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Interpretazione: I dati mostrano deviazioni significative dalla normalità</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Attenzione ai test di normalità
</div>
</div>
<div class="callout-body-container callout-body">
<p>I test formali di normalità (come Shapiro-Wilk) hanno due limitazioni:</p>
<ol type="1">
<li><strong>Con campioni piccoli</strong>: hanno poco potere, quindi anche deviazioni importanti potrebbero non essere rilevate.</li>
<li><strong>Con campioni grandi</strong>: diventano troppo sensibili, rilevando deviazioni minime che non hanno importanza pratica</li>
</ol>
<p>Per questo motivo, la valutazione visiva tramite QQ-plot è spesso più utile del test formale.</p>
</div>
</div>
</section>
</section>
<section id="sec-bridge-to-inference" class="level2" data-number="19.7">
<h2 data-number="19.7" class="anchored" data-anchor-id="sec-bridge-to-inference"><span class="header-section-number">19.7</span> Ponte verso la modellazione bayesiana</h2>
<p>I concetti introdotti in questo capitolo costituiscono i <strong>mattoni concettuali fondamentali</strong> per la costruzione, la comprensione e l’interpretazione dei modelli bayesiani che verranno sviluppati nei capitoli successivi. Lontani dall’essere nozioni puramente descrittive, essi anticipano direttamente le scelte di modellazione, di specificazione dei <em>prior</em> e di valutazione dei modelli. Riassumiamo di seguito le connessioni più rilevanti.</p>
<section id="dalle-distribuzioni-ai-prior-coniugati" class="level3" data-number="19.7.1">
<h3 data-number="19.7.1" class="anchored" data-anchor-id="dalle-distribuzioni-ai-prior-coniugati"><span class="header-section-number">19.7.1</span> 1. Dalle distribuzioni ai prior coniugati</h3>
<p>Abbiamo visto come la distribuzione normale sia completamente descritta da due parametri, <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>. Nel contesto bayesiano:</p>
<ul>
<li>la distribuzione normale può essere utilizzata come <strong>prior</strong> su parametri continui, quali coefficienti di regressione, effetti di trattamento o differenze tra gruppi;</li>
<li>l’uso di <em>prior</em> <strong>coniugati</strong> (ad esempio, una normale come <em>prior</em> combinata con una <em>likelihood</em> normale) consente di ottenere una <strong>distribuzione a posteriori</strong> della stessa famiglia, semplificando l’analisi e l’interpretazione;</li>
<li>i <em>posterior</em> rappresentano una <strong>conoscenza aggiornata</strong> alla luce dei dati osservati, e i relativi intervalli di credibilità (come il 95% HDI) possono essere interpretati direttamente come regioni di plausibilità del parametro.</li>
</ul>
<p>In questo senso, la distribuzione normale diventa uno strumento naturale per formalizzare l’incertezza sui parametri.</p>
</section>
<section id="dalla-normalità-ai-modelli-gerarchici" class="level3" data-number="19.7.2">
<h3 data-number="19.7.2" class="anchored" data-anchor-id="dalla-normalità-ai-modelli-gerarchici"><span class="header-section-number">19.7.2</span> 2. Dalla normalità ai modelli gerarchici</h3>
<p>La distribuzione normale non svolge un ruolo centrale solo come <em>likelihood</em> per i dati osservati, ma anche come <strong>meccanismo di modellazione della variabilità</strong>:</p>
<ul>
<li>nei <strong>modelli gerarchici</strong>, è comune assumere che gli effetti specifici di gruppi, soggetti o condizioni siano distribuiti normalmente attorno a un valore medio comune;</li>
<li>questi effetti sono governati da <strong>iperparametri</strong>, che regolano il grado di variabilità tra unità e determinano quanto le stime individuali vengano “attratte” verso la media di gruppo.</li>
</ul>
<p>Questo approccio realizza in modo naturale un compromesso tra <em>pooling</em> completo e stima completamente separata degli effetti, introducendo una forma di <strong>regolarizzazione intrinseca</strong> tipica della modellazione bayesiana.</p>
</section>
<section id="standardizzazione-e-interpretazione-degli-effetti" class="level3" data-number="19.7.3">
<h3 data-number="19.7.3" class="anchored" data-anchor-id="standardizzazione-e-interpretazione-degli-effetti"><span class="header-section-number">19.7.3</span> 3. Standardizzazione e interpretazione degli effetti</h3>
<p>Gli z-scores forniscono un’intuizione cruciale che si riflette direttamente nella pratica bayesiana:</p>
<ul>
<li>la standardizzazione delle variabili facilita la specificazione di <strong>prior informativi deboli</strong>, ad esempio esprimendo convinzioni del tipo: “mi aspetto effetti piccoli, entro ±0.5 deviazioni standard”;</li>
<li>nei modelli di regressione, lavorare su scale standardizzate rende i coefficienti <strong>direttamente confrontabili</strong> e i <em>prior</em> più facilmente interpretabili;</li>
<li>ciò riduce il rischio di <em>prior</em> implicitamente troppo informativi o incoerenti con la scala dei dati.</li>
</ul>
</section>
<section id="verifica-dei-modelli-e-diagnostica" class="level3" data-number="19.7.4">
<h3 data-number="19.7.4" class="anchored" data-anchor-id="verifica-dei-modelli-e-diagnostica"><span class="header-section-number">19.7.4</span> 4. Verifica dei modelli e diagnostica</h3>
<p>Strumenti come il QQ-plot e la valutazione della normalità rappresentano un primo passo verso una più ampia prospettiva di <strong>diagnostica bayesiana</strong>:</p>
<ul>
<li>anche quando una distribuzione normale è assunta nella <em>likelihood</em>, è necessario esaminare i <strong>residui posteriori</strong> per valutare l’adeguatezza del modello;</li>
<li>tuttavia, l’approccio bayesiano va oltre la verifica di singole assunzioni: mediante i <strong>posterior predictive checks</strong>, si valuta se l’intero modello (prior + likelihood) è in grado di generare dati compatibili con quelli osservati.</li>
</ul>
<p>In questo quadro, la normalità non è un dogma da accettare o rifiutare, ma una <strong>ipotesi modellistica</strong> da valutare nel contesto più ampio della capacità del modello di descrivere i dati.</p>
<p>Nel loro insieme, questi collegamenti mostrano come i concetti di distribuzione, parametro e adeguatezza del modello introdotti in questo capitolo non siano meri strumenti descrittivi, ma costituiscano il <strong>punto di partenza per una modellazione esplicita, probabilistica e coerente</strong> dei fenomeni psicologici. È su queste basi che la modellazione bayesiana può essere intesa non solo come una tecnica statistica, ma come un vero e proprio <strong>quadro concettuale per l’inferenza scientifica</strong>.</p>
</section>
</section>
<section id="riflessioni-conclusive" class="level2 unnumbered unlisted">
<h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>In questo capitolo abbiamo utilizzato la <strong>distribuzione normale</strong> come una <em>lente descrittiva</em> e come primo esempio di <strong>modello probabilistico</strong>: uno strumento compatto per riassumere dati continui e per ragionare in modo strutturato sulla loro variabilità.</p>
<p>Abbiamo visto che:</p>
<ul>
<li>quando la distribuzione normale fornisce una buona approssimazione dei dati, <strong>media</strong> e <strong>deviazione standard</strong> assumono un significato informativo preciso, descrivendo rispettivamente la posizione centrale e la dispersione, e consentendo confronti immediati tra gruppi, condizioni e contesti diversi;</li>
<li>la <strong>standardizzazione</strong> tramite z-score non è un mero artificio computazionale, ma un passaggio concettuale rilevante: porta variabili eterogenee su una scala comune, rende più interpretabili i confronti e le dimensioni d’effetto e prepara il terreno a scelte di modellazione più consapevoli, ad esempio nell’ambito della regressione;</li>
<li>la <strong>valutazione della normalità</strong> va intesa principalmente come un’attività diagnostica: strumenti come il QQ-plot permettono di individuare asimmetrie, code pesanti e valori anomali, segnali che spesso suggeriscono la necessità di trasformazioni, di modelli alternativi o di verosimiglianze più robuste.</li>
</ul>
<p>Il punto centrale è che la distribuzione normale non deve essere trattata come una “legge dei dati”, ma come una <strong>ipotesi di modellazione</strong>. È uno strumento potente quando descrive adeguatamente ciò che osserviamo, ma deve poter essere messo in discussione e sostituito quando non lo fa. Questa prospettiva è fondamentale nell’analisi esplorativa dei dati e diventerà ancora più cruciale nei capitoli successivi, quando inizieremo a costruire modelli completi e a valutarne l’adeguatezza confrontando sistematicamente <strong>ciò che il modello implica</strong> con <strong>ciò che i dati mostrano</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Cosa ci aspetta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nei prossimi capitoli vedremo come:</p>
<ul>
<li>il <strong>Teorema del Limite Centrale</strong> spiega perché, in molte situazioni, le <em>medie campionarie</em> presentano una distribuzione approssimativamente normale, anche quando i dati individuali non lo sono;</li>
<li>questa regolarità rende la distribuzione normale una descrizione utile del comportamento aggregato dei dati, soprattutto quando il campione è sufficientemente ampio;</li>
<li>la distribuzione normale emerge così come un <strong>oggetto centrale della modellazione statistica</strong>, sia nei metodi classici sia in quelli bayesiani, fungendo da approssimazione, modello o componente di modelli più generali.</li>
</ul>
<p>L’obiettivo non è giustificare automaticamente l’uso di test standard, ma comprendere <strong>perché</strong> e <strong>in quali condizioni</strong> la normalità diventa una rappresentazione informativa dei dati.</p>
</div>
</div>
</section>
<section id="esercizi" class="level2 unnumbered unlisted">
<h2 class="unnumbered unlisted anchored" data-anchor-id="esercizi">Esercizi</h2>
<div class="callout callout-style-default callout-caution callout-titled" title="Esercizi">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Attenzione</span>Esercizi
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="parte-1-comprensione-concettuale" class="level3 unnumbered unlisted">
<h3 class="unnumbered unlisted anchored" data-anchor-id="parte-1-comprensione-concettuale">Parte 1: Comprensione concettuale</h3>
<p><strong>1. Perché la distribuzione normale è importante?</strong></p>
<ol type="a">
<li><p>Perché la distribuzione normale è così ampiamente usata in psicologia? Fornisci almeno tre motivi specifici.</p></li>
<li><p>In quali situazioni reali in psicologia possiamo aspettarci che una variabile segua approssimativamente una distribuzione normale?</p></li>
<li><p>Cosa significa dire che la normale è un “modello” e non una “legge”?</p></li>
</ol>
<p><strong>2. La regola empirica</strong></p>
<ol type="a">
<li><p>Spiega con parole tue la regola 68-95-99.7.</p></li>
<li><p>Un test di ansia ha media 50 e deviazione standard 10 nella popolazione. Usando la regola empirica, determina:</p>
<ul>
<li>Entro quale intervallo cade circa il 68% dei punteggi?</li>
<li>Quale percentuale della popolazione ha un punteggio superiore a 70?</li>
<li>Un punteggio di 25 è considerato estremo? Perché?</li>
</ul></li>
<li><p>Perché la regola empirica rende la deviazione standard più interpretabile?</p></li>
</ol>
<p><strong>3. Z-scores e standardizzazione</strong></p>
<ol type="a">
<li><p>Cos’è uno z-score e come si calcola?</p></li>
<li><p>Uno studente ottiene QI = 110 (media = 100, sd = 15) e un punteggio di memoria = 58 (media = 50, sd = 8). In quale test ha performato relativamente meglio? Mostra i calcoli.</p></li>
<li><p>Dopo la standardizzazione, quali saranno la media e la deviazione standard? Perché questo è utile?</p></li>
</ol>
<p><strong>4. QQ-plots</strong></p>
<ol type="a">
<li><p>Spiega la logica di base di un QQ-plot.</p></li>
<li><p>Descrivi come apparirebbe un QQ-plot per ciascuna delle seguenti situazioni:</p>
<ul>
<li>Dati perfettamente normali</li>
<li>Dati con asimmetria positiva</li>
<li>Dati con code pesanti (più outlier del previsto)</li>
</ul></li>
<li><p>Perché i QQ-plots sono spesso più utili dei test formali di normalità?</p></li>
</ol>
</section>
<section id="parte-2-applicazioni-pratiche" class="level3 unnumbered unlisted">
<h3 class="unnumbered unlisted anchored" data-anchor-id="parte-2-applicazioni-pratiche">Parte 2: Applicazioni pratiche</h3>
<p><strong>5. Analisi di punteggi SWLS</strong></p>
<p>Considera i seguenti punteggi SWLS (Satisfaction With Life Scale):</p>
<pre><code>18, 22, 25, 21, 26, 19, 20, 23, 24, 17, 22, 27, 28, 21, 19</code></pre>
<ol type="a">
<li><p>Calcola media e deviazione standard manualmente (o con R).</p></li>
<li><p>Usando la regola empirica, determina l’intervallo entro cui dovrebbe cadere circa il 95% dei punteggi in una popolazione normale con questi parametri.</p></li>
<li><p>Calcola gli z-scores per i punteggi 17 e 28. Quale è più estremo?</p></li>
</ol>
<p><strong>6. Analisi con R</strong></p>
<p>Usa il seguente codice per generare e analizzare dati:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera dati approssimativamente normali</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>dati_normali <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera dati asimmetrici</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>dati_asimmetrici <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">3</span>, <span class="at">sd =</span> <span class="fl">0.5</span>))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Crea QQ-plots per entrambi</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> dati_normali), <span class="fu">aes</span>(<span class="at">sample =</span> x)) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Dati normali"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> dati_asimmetrici), <span class="fu">aes</span>(<span class="at">sample =</span> x)) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Dati asimmetrici"</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Verifica la regola empirica per dati_normali</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(<span class="fu">scale</span>(dati_normali)) <span class="sc">&lt;=</span> <span class="dv">1</span>)  <span class="co"># Dovrebbe essere ~68%</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(<span class="fu">scale</span>(dati_normali)) <span class="sc">&lt;=</span> <span class="dv">2</span>)  <span class="co"># Dovrebbe essere ~95%</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Test di Shapiro-Wilk</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dati_normali)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(dati_asimmetrici)</span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<ol type="a">
<li><p>Esegui il codice e interpreta i QQ-plots: quali dati sembrano più normali?</p></li>
<li><p>Le proporzioni osservate per i <code>dati_normali</code> sono vicine ai valori teorici (68%, 95%)?</p></li>
<li><p>Cosa indicano i risultati dei test di Shapiro-Wilk?</p></li>
</ol>
<p><strong>7. Confronto tra test standardizzati</strong></p>
<p>Una studentessa ottiene i seguenti risultati:</p>
<ul>
<li>Test A: punteggio = 75, con media popolazione = 60 e sd = 10</li>
<li>Test B: punteggio = 115, con media popolazione = 100 e sd = 20</li>
</ul>
<ol type="a">
<li><p>Calcola gli z-scores per entrambi i test.</p></li>
<li><p>In quale test la studentessa ha performato meglio relativamente agli altri?</p></li>
<li><p>Se entrambi i test seguono distribuzioni normali, in quale percentile approssimativo si trova la studentessa in ciascun test? (Usa la regola empirica)</p></li>
</ol>
</section>
<section id="parte-3-riflessione-e-collegamenti" class="level3 unnumbered unlisted">
<h3 class="unnumbered unlisted anchored" data-anchor-id="parte-3-riflessione-e-collegamenti">Parte 3: Riflessione e collegamenti</h3>
<p><strong>8. Verso l’inferenza</strong></p>
<ol type="a">
<li><p>Spiega come la regola empirica prepara alla costruzione di intervalli di confidenza.</p></li>
<li><p>Perché gli z-scores sono importanti per i test statistici che studieremo?</p></li>
<li><p>Se i dati non sono perfettamente normali, possiamo comunque usare metodi statistici basati sulla normalità? Quando sì e quando no?</p></li>
</ol>
<p><strong>9. Caso applicato: sviluppo di un test</strong></p>
<p>Immagina di sviluppare un nuovo questionario per misurare l’autoefficacia accademica:</p>
<ol type="a">
<li><p>Perché potrebbe essere desiderabile che i punteggi seguano approssimativamente una distribuzione normale?</p></li>
<li><p>Come useresti QQ-plots durante lo sviluppo del test?</p></li>
<li><p>Dopo aver raccolto dati su 500 studenti, il test di Shapiro-Wilk risulta significativo (p &lt; 0.001). Cosa fai? Perché?</p></li>
</ol>
</section>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="soluzioni-parte-1" class="level3 unnumbered unlisted">
<h3 class="unnumbered unlisted anchored" data-anchor-id="soluzioni-parte-1">Soluzioni Parte 1</h3>
<p><strong>1b.</strong> Situazioni in cui aspettarci normalità in psicologia:</p>
<ul>
<li>Punteggi di test standardizzati (QI, personalità)</li>
<li>Misure fisiche (altezza, tempo di reazione)</li>
<li>Errori di misurazione in esperimenti</li>
<li>Variabili influenzate da molti fattori indipendenti</li>
</ul>
<p><strong>2b.</strong> Per media=50, sd=10:</p>
<ul>
<li>68% cade in 40-60</li>
<li>Solo ~2.5% sopra 70 (oltre 2 sd)</li>
<li>Un punteggio di 25 è 2.5 sd sotto la media, molto estremo (&lt; 0.5% della popolazione)</li>
</ul>
<p><strong>3b.</strong></p>
<ul>
<li>Z-score QI: (110-100)/15 = 0.67</li>
<li>Z-score memoria: (58-50)/8 = 1.00</li>
<li>Performance migliore in memoria (z più alto)</li>
</ul>
<p><strong>3c.</strong> Dopo standardizzazione: media=0, sd=1 sempre.</p>
</section>
<section id="soluzioni-parte-2" class="level3 unnumbered unlisted">
<h3 class="unnumbered unlisted anchored" data-anchor-id="soluzioni-parte-2">Soluzioni Parte 2</h3>
<p><strong>5.</strong> Per i dati SWLS forniti:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>swls <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">22</span>, <span class="dv">25</span>, <span class="dv">21</span>, <span class="dv">26</span>, <span class="dv">19</span>, <span class="dv">20</span>, <span class="dv">23</span>, <span class="dv">24</span>, <span class="dv">17</span>, <span class="dv">22</span>, <span class="dv">27</span>, <span class="dv">28</span>, <span class="dv">21</span>, <span class="dv">19</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(swls)  <span class="co"># 22.13</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(swls)    <span class="co"># 3.42</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% dovrebbe cadere in: 22.13 ± 2*3.42 = [15.29, 28.97]</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Z-scores</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>(<span class="dv">17</span> <span class="sc">-</span> <span class="fl">22.13</span>)<span class="sc">/</span><span class="fl">3.42</span>  <span class="co"># -1.50</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>(<span class="dv">28</span> <span class="sc">-</span> <span class="fl">22.13</span>)<span class="sc">/</span><span class="fl">3.42</span>  <span class="co"># 1.72</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Il punteggio 28 è leggermente più estremo (in valore assoluto)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>7.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test A</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>z_a <span class="ot">&lt;-</span> (<span class="dv">75</span> <span class="sc">-</span> <span class="dv">60</span>) <span class="sc">/</span> <span class="dv">10</span>  <span class="co"># 1.5</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Test B  </span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>z_b <span class="ot">&lt;-</span> (<span class="dv">115</span> <span class="sc">-</span> <span class="dv">100</span>) <span class="sc">/</span> <span class="dv">20</span>  <span class="co"># 0.75</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># La studentessa ha performato meglio nel Test A (z più alto)</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Nel Test A è circa nel 93° percentile (oltre 1 sd)</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Nel Test B è circa nell'77° percentile (tra media e +1 sd)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="soluzioni-parte-3" class="level3 unnumbered unlisted">
<h3 class="unnumbered unlisted anchored" data-anchor-id="soluzioni-parte-3">Soluzioni Parte 3</h3>
<p><strong>8a.</strong> La regola empirica mostra che il 95% dei valori cade entro ±2 sd dalla media. Gli intervalli di confidenza usano questo principio: se conosciamo la distribuzione campionaria di una statistica, possiamo costruire un intervallo che “cattura” il parametro il 95% delle volte.</p>
<p><strong>9c.</strong> Con n=500, il test di Shapiro-Wilk è molto sensibile e può rilevare deviazioni minime dalla normalità che non hanno importanza pratica. Azioni consigliate:</p>
<ol type="1">
<li>Esaminare il QQ-plot (più informativo)</li>
<li>Se il QQ-plot mostra solo piccole deviazioni agli estremi, non preoccuparsi</li>
<li>Ricordare che molti metodi statistici sono robusti a piccole violazioni della normalità</li>
<li>Se le deviazioni sono sostanziali, considerare trasformazioni o metodi non parametrici</li>
</ol>
</section>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; R version 4.6.0 (2026-04-24)</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Platform: aarch64-apple-darwin23</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running under: macOS Tahoe 26.5.1</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Matrix products: default</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib </span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; locale:</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; tzcode source: internal</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; attached base packages:</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; other attached packages:</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1] gridExtra_2.3.1       dslabs_0.9.1          ggbeeswarm_0.7.3     </span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [4] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          </span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [7] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [10] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        </span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [13] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      </span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [16] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [19] brms_2.23.0           Rcpp_1.1.1-1.1        sessioninfo_1.2.4    </span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [22] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [25] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          </span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [28] tidyr_1.3.2           rio_1.3.0             here_1.0.2           </span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1] svUnit_1.0.8          tidyselect_1.2.1      vipor_0.4.7          </span></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [4] farver_2.1.2          S7_0.2.2              fastmap_1.2.0        </span></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [7] tensorA_0.36.2.1      pacman_0.5.1          digest_0.6.39        </span></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [10] timechange_0.4.0      estimability_2.0.0    lifecycle_1.0.5      </span></span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [13] magrittr_2.0.5        compiler_4.6.0        rlang_1.2.0          </span></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [16] tools_4.6.0           yaml_2.3.12           knitr_1.51           </span></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [19] labeling_0.4.3        bridgesampling_1.2-1  htmlwidgets_1.6.4    </span></span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [22] pkgbuild_1.4.8        curl_7.1.0            RColorBrewer_1.1-3   </span></span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [25] abind_1.4-8           purrr_1.2.2           grid_4.6.0           </span></span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [28] stats4_4.6.0          xtable_1.8-8          inline_0.3.21        </span></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [31] emmeans_2.0.3         scales_1.4.0          cli_3.6.6            </span></span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [34] mvtnorm_1.4-1         rmarkdown_2.31        generics_0.1.4       </span></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [37] otel_0.2.0            RcppParallel_5.1.11-2 cachem_1.1.0         </span></span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [40] stringr_1.6.0         parallel_4.6.0        vctrs_0.7.3          </span></span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [43] V8_8.2.0              Matrix_1.7-5          jsonlite_2.0.0       </span></span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [46] arrayhelpers_1.1-1    beeswarm_0.4.0        glue_1.8.1           </span></span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [49] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      </span></span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [52] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      </span></span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [55] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    </span></span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [58] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      </span></span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [61] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      </span></span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [64] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     </span></span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [67] rstantools_2.6.0      coda_0.19-4.1         nlme_3.1-169         </span></span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [70] checkmate_2.3.4       xfun_0.59             pkgconfig_2.0.3</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="bibliografia" class="level2 unnumbered unlisted">
<h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-irizarry2024introduction" class="csl-entry" role="listitem">
Irizarry, R. A. (2024). <em>Introduction to Data Science: Data Wrangling and Visualization with R</em>. CRC Press.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//ccaudek\.github\.io/utet-eda/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/eda/06_loc_scale.html" class="pagination-link" aria-label="Indicatori di tendenza centrale e variabilità">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Indicatori di tendenza centrale e variabilità</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/eda/08_correlation.html" class="pagination-link" aria-label="Relazioni tra variabili">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Relazioni tra variabili</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Analisi esplorativa dei dati (EDA)</strong> — Modulo del progetto UTET a supporto del manuale <em>Inferenza bayesiana in psicologia: Ragionare con l’incertezza</em>.</p>
</div>   
    <div class="nav-footer-center">

<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-eda/blob/main/chapters/eda/07_introduction_normal_distribution.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-eda/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Preferenze cookie</a></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>