{
  "hash": "b77961651b32cccad0b10c86817ba4ce",
  "result": {
    "engine": "knitr",
    "markdown": "# Indicatori di tendenza centrale e variabilità {#sec-central-tendency-variability}\n\n::: {.callout-note appearance=\"minimal\"}\nLa visualizzazione grafica dei dati rappresenta il punto di partenza di ogni analisi quantitativa. Grazie a rappresentazioni grafiche adeguate, è possibile individuare importanti caratteristiche di una distribuzione, come la simmetria o l'asimmetria, nonché la presenza di una o più modalità. In seguito, per descrivere sinteticamente le principali caratteristiche dei dati, è possibile utilizzare specifici indici numerici. In questo capitolo verranno presentati i principali indicatori della statistica descrittiva.\n:::\n\n## Panoramica del capitolo {.unnumbered .unlisted}\n\n- *Tendenza centrale:* scelta della misura (media, mediana, moda) in base al tipo di dati e alla presenza di valori anomali.\n- *Robustezza:* confronto tra misure sensibili (media, deviazione standard) e misure robuste (mediana, trimmed mean, MAD).\n- *Simulazioni:* dimostrazione empirica dell'effetto degli outlier attraverso esempi pratici.\n- *Variabilità:* interpretazione di range, varianza, deviazione standard e IQR per quantificare la dispersione dei dati attorno al valore centrale.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Leggere \"Most Psychological Researchers Assume Their Samples Are Ergodic: Evidence From a Year of Articles in Three Major Journals\" [@speelman2024most].\n- Studiare l'@sec-apx-sums.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Load packages\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(tidyr, viridis, vcd)\n```\n:::\n\n:::\n\n## Indici di tendenza centrale\n\nGli indici di tendenza centrale sono valori sintetici che hanno lo scopo di sintetizzare un insieme di dati individuando un valore rappresentativo, tipico o centrale attorno al quale i dati tendono a distribuirsi. Consentono di cogliere in modo immediato le caratteristiche fondamentali di una distribuzione, offrendo una descrizione sintetica ed efficace senza dover esaminare ogni singolo dato. Grazie alla loro capacità di riassumere informazioni complesse in un unico valore, gli indici di tendenza centrale costituiscono uno strumento essenziale nell'analisi statistica, sia descrittiva che inferenziale. I principali indici sono:\n\n1. *Media*: la media è la somma di tutti i valori divisa per il numero totale di valori. È spesso utilizzata come misura generale di tendenza centrale, ma è sensibile agli estremi (valori molto alti o molto bassi).\n2. *Mediana*: la mediana è il valore che divide l'insieme di dati in due parti uguali. A differenza della media, non è influenzata da valori estremi ed è quindi più robusta in presenza di outlier.\n3. *Moda*: la moda è il valore che appare più frequentemente in un insieme di dati. In alcuni casi, può non essere presente o esserci più di una moda.\n\nLa scelta dell'indice più appropriato non è mai neutra, ma dipende dalla natura dei dati e dalla domanda a cui si vuole rispondere. In presenza di valori anomali, ad esempio, la mediana fornisce una rappresentazione più fedele rispetto alla media, che risulterebbe invece distorta. Padroneggiare questi strumenti significa, quindi, non solo essere in grado di calcolare un numero, ma anche di interpretare correttamente la struttura sottostante ai dati.\n\n### Moda\n\nLa *moda* ($\\text{Mo}$) rappresenta il valore della variabile che *compare con maggiore frequenza* in una distribuzione. In altre parole, è il valore più *ricorrente* nei dati.  \n\n- Nelle *distribuzioni unimodali*, esiste una sola moda, che coincide con il valore centrale della distribuzione più frequente.  \n- Tuttavia, in alcune distribuzioni, possono emergere *più di una moda*, rendendole *multimodali*. In questi casi, la moda perde il suo significato di indicatore unico di tendenza centrale, poiché la presenza di più valori con frequenze elevate rende difficile individuare un singolo punto di riferimento.  \n\n### Mediana\n\nLa *mediana* ($\\tilde{x}$) corrisponde al valore che divide il campione in due metà: il 50% dei dati è inferiore o uguale alla mediana e il restante 50% è superiore o uguale. A differenza della media, la mediana è meno influenzata dai valori estremi, rendendola una misura particolarmente robusta in presenza di dati asimmetrici o outlier.\n\n### Media\n\nLa media aritmetica di un insieme di valori rappresenta il punto centrale o il baricentro della distribuzione dei dati. È calcolata come la somma di tutti i valori divisa per il numero totale di valori, ed è espressa dalla formula:\n\n$$\n\\bar{x}=\\frac{1}{n}\\sum_{i=1}^n x_i,\n$$ {#eq-mean}\ndove $x_i$ rappresenta i valori nell'insieme, $n$ è il numero totale di valori, e $\\sum$ indica la sommatoria.\n\n### Calcolo della media con `R`\n\nPer calcolare la media di un piccolo numero di valori in R, possiamo utilizzare la somma di questi valori e dividerla per il numero totale di elementi. Consideriamo ad esempio i valori 12, 44, 21, 62, 24:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(12 + 44 + 21 + 62 + 24) / 5\n#> [1] 32.6\n```\n:::\n\n\novvero\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(12, 44, 21, 62, 24)\nmean(x)\n#> [1] 32.6\n```\n:::\n\n\n### Media vs mediana: robustezza e scelta della misura {#sec-mean-vs-median}\n\nLa scelta tra media e mediana come misura di tendenza centrale dipende dalle caratteristiche della distribuzione dei dati e dall'obiettivo dell'analisi. Comprendere quando utilizzare l'una o l'altra è fondamentale per una corretta interpretazione statistica.\n\n### Differenze concettuali\n\nLa **media aritmetica** tiene conto di tutti i valori nella distribuzione, assegnando uguale peso a ciascuna osservazione. Questa caratteristica la rende matematicamente conveniente (ad esempio, è coinvolta nel calcolo della varianza) ma anche sensibile ai valori estremi.\n\nLa **mediana**, invece, rappresenta il valore centrale della distribuzione ordinata e non è influenzata dall'entità dei valori estremi, ma solo dalla loro posizione. Questa proprietà la rende una misura *robusta*, particolarmente utile quando la distribuzione è asimmetrica o contiene outlier.\n\n### L'effetto degli outlier: una simulazione\n\nPer comprendere concretamente l'impatto dei valori estremi, consideriamo una simulazione. Generiamo un campione di 100 osservazioni da una distribuzione normale e osserviamo cosa accade quando introduciamo progressivamente valori anomali.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Campione base da distribuzione normale\ndati_base <- rnorm(100, mean = 50, sd = 10)\n\n# Creiamo versioni con numero crescente di outlier\ndati_1_outlier <- c(dati_base[1:99], 150)  # 1 outlier estremo\ndati_5_outlier <- c(dati_base[1:95], rep(150, 5))  # 5 outlier\ndati_10_outlier <- c(dati_base[1:90], rep(150, 10))  # 10 outlier\n\n# Confronto delle misure\nrisultati <- data.frame(\n  Scenario = c(\"Nessun outlier\", \"1 outlier (1%)\", \"5 outlier (5%)\", \"10 outlier (10%)\"),\n  Media = c(mean(dati_base), mean(dati_1_outlier), \n            mean(dati_5_outlier), mean(dati_10_outlier)),\n  Mediana = c(median(dati_base), median(dati_1_outlier), \n              median(dati_5_outlier), median(dati_10_outlier)),\n  Differenza = NA\n)\n\nrisultati$Differenza <- risultati$Media - risultati$Mediana\n\nknitr::kable(risultati, digits = 2, \n             caption = \"Confronto tra media e mediana al variare della presenza di outlier\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Confronto tra media e mediana al variare della presenza di outlier\n\n|Scenario         | Media| Mediana| Differenza|\n|:----------------|-----:|-------:|----------:|\n|Nessun outlier   |  50.9|    50.6|       0.29|\n|1 outlier (1%)   |  52.0|    50.9|       1.10|\n|5 outlier (5%)   |  55.7|    51.3|       4.45|\n|10 outlier (10%) |  60.5|    51.4|       9.05|\n\n\n:::\n:::\n\n\nCome si può osservare, mentre la mediana rimane sostanzialmente stabile, la media aumenta progressivamente con l'aggiunta di valori estremi. Anche un singolo outlier (solo l'1% del campione) è sufficiente per alterare notevolmente la media.\n\nVisualizziamo graficamente questo fenomeno:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_data <- data.frame(\n  valore = c(dati_base, dati_1_outlier, dati_5_outlier, dati_10_outlier),\n  scenario = rep(c(\"Nessun outlier\", \"1 outlier (1%)\", \n                   \"5 outlier (5%)\", \"10 outlier (10%)\"), \n                 each = 100)\n)\n\n# Calcolo statistiche per ogni scenario\nstats <- plot_data |>\n  group_by(scenario) |>\n  summarise(\n    media = mean(valore),\n    mediana = median(valore)\n  )\n\nggplot(plot_data, aes(x = valore)) +\n  geom_histogram(bins = 30, fill = \"lightblue\", color = \"black\", alpha = 0.7) +\n  geom_vline(data = stats, aes(xintercept = media), \n             color = \"red\", linetype = \"dashed\", linewidth = 1) +\n  geom_vline(data = stats, aes(xintercept = mediana), \n             color = \"blue\", linetype = \"solid\", linewidth = 1) +\n  facet_wrap(~scenario, ncol = 2, scales = \"free\") +\n  labs(title = \"Confronto tra media (rosso) e mediana (blu)\\nin presenza di outlier\",\n       x = \"Valore\", y = \"Frequenza\") \n```\n\n::: {.cell-output-display}\n![Effetto degli outlier su media e mediana](06_loc_scale_files/figure-html/fig-outlier-effect-1.png){#fig-outlier-effect fig-align='center' width=85%}\n:::\n:::\n\n\nLa visualizzazione mostra chiaramente come la media (linea rossa tratteggiata) si sposti verso destra in presenza di outlier, mentre la mediana (linea blu continua) rimane ancorata al centro della massa principale dei dati.\n\n### Misure robuste: media spuntata e MAD\n\nPer mitigare la sensibilità della media aritmetica agli outlier, la statistica offre misure alternative più robuste.\n\n### Media spuntata (*trimmed mean*)\n\nLa media spuntata calcola la media escludendo una percentuale simmetrica di valori estremi. Ad esempio, con un trim del 10%, vengono rimossi il 5% dei valori più bassi e il 5% dei valori più alti prima del calcolo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Confronto tra media standard e trimmed mean\ndata.frame(\n  Scenario = c(\"Nessun outlier\", \"1 outlier (1%)\", \"5 outlier (5%)\", \"10 outlier (10%)\"),\n  Media = c(mean(dati_base), mean(dati_1_outlier), \n            mean(dati_5_outlier), mean(dati_10_outlier)),\n  `Trimmed Mean (10%)` = c(\n    mean(dati_base, trim = 0.10),\n    mean(dati_1_outlier, trim = 0.10),\n    mean(dati_5_outlier, trim = 0.10),\n    mean(dati_10_outlier, trim = 0.10)\n  )\n) |>\n  knitr::kable(digits = 2, \n               caption = \"Confronto tra media standard e trimmed mean\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Confronto tra media standard e trimmed mean\n\n|Scenario         | Media| Trimmed.Mean..10..|\n|:----------------|-----:|------------------:|\n|Nessun outlier   |  50.9|               50.8|\n|1 outlier (1%)   |  52.0|               51.1|\n|5 outlier (5%)   |  55.7|               51.6|\n|10 outlier (10%) |  60.5|               52.4|\n\n\n:::\n:::\n\n\nLa media spuntata rappresenta un compromesso efficace tra la sensibilità della media aritmetica e la robustezza della mediana.\n\n### Deviazione Mediana Assoluta\n\nPer misurare la variabilità in modo robusto, possiamo utilizzare la *deviazione mediana assoluta* (MAD), definita come:\n\n$$\n\\text{MAD} = \\text{mediana}(|X_i - \\text{mediana}(X)|)\n$$\n\nIl MAD misura la distanza tipica dei valori dalla mediana, offrendo una misura di variabilità resistente agli outlier:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Confronto tra deviazione standard e MAD\ndata.frame(\n  Scenario = c(\"Nessun outlier\", \"1 outlier (1%)\", \"5 outlier (5%)\", \"10 outlier (10%)\"),\n  `Dev. Standard` = c(sd(dati_base), sd(dati_1_outlier), \n                       sd(dati_5_outlier), sd(dati_10_outlier)),\n  MAD = c(mad(dati_base), mad(dati_1_outlier), \n          mad(dati_5_outlier), mad(dati_10_outlier))\n) |>\n  knitr::kable(digits = 2, \n               caption = \"Confronto tra deviazione standard e MAD\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Confronto tra deviazione standard e MAD\n\n|Scenario         | Dev..Standard|  MAD|\n|:----------------|-------------:|----:|\n|Nessun outlier   |          9.13| 8.90|\n|1 outlier (1%)   |         13.42| 8.83|\n|5 outlier (5%)   |         23.40| 9.24|\n|10 outlier (10%) |         31.17| 9.81|\n\n\n:::\n:::\n\n\nCome si evince dalla tabella, mentre la deviazione standard cresce sensibilmente in presenza di outlier, il MAD rimane sostanzialmente stabile, fornendo una misura più affidabile della variabilità \"tipica\" della distribuzione.\n\n### Linee guida per la scelta\n\nLa scelta della misura appropriata dipende dal contesto analitico e dagli obiettivi della ricerca:\n\n**Utilizzare la media quando:**\n\n- la distribuzione è approssimativamente simmetrica e priva di outlier;\n- è importante che ogni osservazione contribuisca alla misura finale;\n- si intendono sfruttare proprietà matematiche specifiche (es. minimizzazione degli scarti quadratici);\n- si procederà con analisi parametriche che assumono normalità.\n\n**Utilizzare la mediana quando:**\n\n- la distribuzione è marcatamente asimmetrica;\n- sono presenti outlier che non si possono rimuovere;\n- si lavora con variabili ordinali;\n- è importante una misura resistente a valori estremi;\n- si desidera un \"valore tipico\" che rappresenti il centro effettivo della distribuzione.\n\n**Utilizzare la trimmed mean quando:**\n\n- si desidera un compromesso tra sensibilità e robustezza;\n- si sospetta la presenza di alcuni outlier ma si vuole mantenere l'influenza della maggior parte dei dati.\n\n**Utilizzare MAD quando:**\n\n- si necessita di una misura di variabilità robusta;\n- la distribuzione contiene outlier;\n- si sta utilizzando la mediana come misura di tendenza centrale.\n\n::: {.callout-important title=\"Attenzione alla coerenza\"}\n\nÈ fondamentale mantenere coerenza metodologica tra le misure di tendenza centrale e di variabilità utilizzate. Se si sceglie la mediana per la sua robustezza, è coerente utilizzare MAD come misura di variabilità, anziché la deviazione standard.\n:::\n\n### Un caso pratico: distribuzione dei redditi\n\nUn esempio emblematico dell'utilità di mediana e MAD riguarda l'analisi dei redditi. Consideriamo un campione simulato di redditi familiari:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(456)\n\n# Simuliamo redditi con distribuzione log-normale (tipica dei redditi reali)\n# La maggior parte delle famiglie ha redditi moderati, poche hanno redditi molto alti\nredditi <- rlnorm(1000, meanlog = 10.5, sdlog = 0.6)\n\n# Aggiungiamo alcuni redditi molto elevati (top 1%)\nredditi_completi <- c(redditi[1:990], rlnorm(10, meanlog = 12.5, sdlog = 0.3))\n\n# Confronto misure\ncat(\"Media dei redditi:\", round(mean(redditi_completi), 0), \"€\\n\")\n#> Media dei redditi: 47136 €\ncat(\"Mediana dei redditi:\", round(median(redditi_completi), 0), \"€\\n\")\n#> Mediana dei redditi: 37848 €\ncat(\"Trimmed mean (10%):\", round(mean(redditi_completi, trim = 0.10), 0), \"€\\n\\n\")\n#> Trimmed mean (10%): 40945 €\n\ncat(\"Deviazione standard:\", round(sd(redditi_completi), 0), \"€\\n\")\n#> Deviazione standard: 40314 €\ncat(\"MAD:\", round(mad(redditi_completi), 0), \"€\\n\")\n#> MAD: 22768 €\n```\n:::\n\n\nIn questo scenario, la mediana fornisce una rappresentazione più accurata del \"reddito tipico\", poiché non è influenzata dai redditi estremamente elevati dell'1% più ricco. La media, al contrario, sovrastima sensibilmente il reddito della maggioranza della popolazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata.frame(reddito = redditi_completi) |>\n  ggplot(aes(x = reddito)) +\n  geom_histogram(bins = 50, fill = \"lightgreen\", color = \"black\", alpha = 0.7) +\n  geom_vline(xintercept = mean(redditi_completi), \n             color = \"red\", linetype = \"dashed\", linewidth = 1) +\n  geom_vline(xintercept = median(redditi_completi), \n             color = \"blue\", linetype = \"solid\", linewidth = 1) +\n  annotate(\"text\", x = mean(redditi_completi) + 10000, y = 150, \n           label = \"Media\", color = \"red\", angle = 90) +\n  annotate(\"text\", x = median(redditi_completi) - 5000, y = 150, \n           label = \"Mediana\", color = \"blue\", angle = 90) +\n  labs(title = \"Distribuzione asimmetrica dei redditi\",\n       subtitle = \"La mediana rappresenta meglio il reddito 'tipico'\",\n       x = \"Reddito (€)\", y = \"Frequenza\") +\n  scale_x_continuous(labels = scales::comma)\n```\n\n::: {.cell-output-display}\n![Distribuzione dei redditi: confronto tra media e mediana](06_loc_scale_files/figure-html/fig-redditi-1.png){#fig-redditi fig-align='center' width=85%}\n:::\n:::\n\n\n### Un'applicazione concreta: il caso Natsal\n\nCome illustrato nella @sec-mean-vs-median, la *media spuntata* rappresenta un compromesso efficace tra sensibilità e robustezza. Eliminando una percentuale simmetrica di dati estremi, offre una misura più stabile della tendenza centrale.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio applicato: Natsal\"}\n\nPer dimostrare l'applicazione pratica della media spuntata, analizziamo i dati del Progetto Natsal, contenuti nel file `sexual-partners.csv`.\n\nNegli anni '80, con l'emergere dell'AIDS, le autorità sanitarie britanniche si resero conto della mancanza di dati affidabili sui comportamenti sessuali della popolazione. In particolare, era cruciale comprendere la frequenza di cambio partner, il numero di partner simultanei e le pratiche sessuali adottate. Queste informazioni erano essenziali per prevedere la diffusione delle malattie sessualmente trasmissibili e pianificare i servizi sanitari, ma si faceva ancora riferimento ai dati di Alfred Kinsey raccolti negli Stati Uniti negli anni '40, privi di rappresentatività campionaria.\n\nA partire dalla fine degli anni '80, furono quindi avviati nel Regno Unito e negli Stati Uniti studi rigorosi sui comportamenti sessuali, nonostante forti opposizioni. In particolare, il governo di Margaret Thatcher ritirò all'ultimo momento il sostegno a un'importante indagine. I ricercatori riuscirono comunque a ottenere finanziamenti da enti benefici, dando vita al *National Sexual Attitudes and Lifestyles Survey* (Natsal). Da allora, questa indagine viene condotta ogni dieci anni, a partire dal 1990. La terza rilevazione, Natsal-3, è stata effettuata intorno al 2010.\n\nAnalizziamo i dati relativi al *numero totale dichiarato di partner sessuali di sesso opposto* nella vita per uomini e donne di età compresa tra 35 e 44 anni. I dati provengono da Natsal-3 e includono 796 uomini e 1193 donne.\n\nProcediamo all'importazione dei dati:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsexual_partners <- rio::import(here::here(\"data\", \"sexual-partners.csv\"))\n```\n:::\n\n\nEsaminiamo un campione casuale del dataset:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsexual_partners[sample(1:nrow(sexual_partners), size = 10, replace = FALSE), ]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"NumPartners\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Man\",\"2\":\"7\",\"_rn_\":\"356\"},{\"1\":\"Woman\",\"2\":\"5\",\"_rn_\":\"1329\"},{\"1\":\"Woman\",\"2\":\"1\",\"_rn_\":\"803\"},{\"1\":\"Woman\",\"2\":\"1\",\"_rn_\":\"901\"},{\"1\":\"Man\",\"2\":\"52\",\"_rn_\":\"761\"},{\"1\":\"Woman\",\"2\":\"4\",\"_rn_\":\"1247\"},{\"1\":\"Man\",\"2\":\"6\",\"_rn_\":\"339\"},{\"1\":\"Woman\",\"2\":\"5\",\"_rn_\":\"1376\"},{\"1\":\"Woman\",\"2\":\"5\",\"_rn_\":\"1361\"},{\"1\":\"Man\",\"2\":\"7\",\"_rn_\":\"373\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nLa colonna `Gender` indica il genere del rispondente, mentre `NumPartners` riporta il numero di partner sessuali di sesso opposto dichiarati.\n\nCalcoliamo la media spuntata per gli uomini:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_partners_men <- sexual_partners[sexual_partners$Gender == \"Man\", \"NumPartners\"]\nmean(sex_partners_men, trim = 0.10, na.rm = TRUE)\n#> [1] 10.6\n```\n:::\n\n\nCalcoliamo la media spuntata per le donne:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_partners_women <- sexual_partners[sexual_partners$Gender == \"Woman\", \"NumPartners\"]\nmean(sex_partners_women, trim = 0.10, na.rm = TRUE)\n#> [1] 6.01\n```\n:::\n\n:::\n\n### Proprietà della media\n\nUna proprietà fondamentale della media è che la somma degli scarti di ciascun valore dalla media è zero:\n\n$$\n\\sum_{i=1}^n (x_i - \\bar{x}) = 0.\\notag\n$$ {#eq-diffmeansumzero}\n\nInfatti,\n\n$$\n\\begin{aligned}\n\\sum_{i=1}^n (x_i - \\bar{x}) &= \\sum_i x_i - \\sum_i \\bar{x}\\notag\\\\\n&= \\sum_i x_i - n \\bar{x}\\notag\\\\\n&= \\sum_i x_i - \\sum_i x_i = 0.\\notag\n\\end{aligned}\n$$\nQuesta proprietà implica che i dati sono equamente distribuiti intorno alla media.\n\nIn R abbiamo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum(x - mean(x))\n#> [1] -7.11e-15\n```\n:::\n\n\n::: {.callout-tip title=\"Nota sulla notazione scientifica\" collapse=\"true\"}\nQuando in un terminale viene visualizzato un numero come `-7.105e-15` in notazione scientifica, esso corrisponde a $-7.105 \\cdot 10^{-15}$, che è effettivamente zero nel contesto dei calcoli numerici.  \n\nQuesta approssimazione è una conseguenza diretta della *precisione finita* dei calcolatori. I sistemi digitali, infatti, rappresentano i numeri reali attraverso una codifica in *virgola mobile* (*floating point*), che comporta inevitabili errori di arrotondamento. La ragione risiede nell'impossibilità di memorizzare numeri reali con precisione assoluta.  \n\nLo standard *IEEE 754 a doppia precisione* (64 bit), ampiamente utilizzato, suddivide la memoria in tre componenti:  \n\n- 1 bit per il segno (positivo/negativo),  \n- 11 bit per l'esponente (intervallo di scala),  \n- 52 bit per la mantissa (o significando), che definisce le cifre significative.\n\nGrazie a questa struttura, è possibile rappresentare numeri con una precisione di circa *15-17 cifre decimali*. Tuttavia, qualsiasi valore non esprimibile in formato binario entro questi limiti subisce un troncamento o un arrotondamento, generando piccole discrepanze rispetto al risultato teorico.\n:::\n\n### La media come centro di gravità dell'istogramma\n\nLa media aritmetica può essere interpretata come il centro di gravità o il punto di equilibrio della distribuzione dei dati. In termini fisici, il centro di gravità è il punto in cui la massa di un sistema è equilibrata o concentrata.\n\nIn termini statistici, possiamo considerare la media come il punto in cui la distribuzione dei dati è in equilibrio. Ogni valore dell'insieme di dati può essere visto come un punto materiale con una massa proporzionale al suo valore. Se immaginiamo questi punti disposti su una linea, con valori più grandi a destra e più piccoli a sinistra, la media corrisponderà esattamente al punto in cui la distribuzione sarebbe in equilibrio.\n\n::: {.callout-note collapse=\"true\" title=\"Principio dei minimi quadrati\"}\n\nIl *metodo dei minimi quadrati* afferma che la posizione della media minimizza la somma dei quadrati delle distanze dai dati. Matematicamente, ciò significa che la somma dei quadrati degli scarti tra ciascun valore osservato e la media è minima. Questo principio è alla base dell'analisi statistica della regressione e conferma il ruolo della media come *centro di gravità* della distribuzione dei dati.\n\n**Simulazione.** Utilizziamo una simulazione per verificare questo principio, calcolando la somma dei quadrati degli scarti per diversi valori e visualizzando il risultato con *ggplot2*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Definizione dell'intervallo di valori da testare\nnrep <- 10000\nM <- seq(20, 40, length.out = nrep)\nres <- rep(NA, nrep)\n\n# Calcolo della somma dei quadrati degli scarti per ciascun valore di M\nfor (i in 1:nrep) {\n  res[i] = sum((x - M[i])^2)\n}\n\n# Identificazione del valore minimo\nmin_index <- which.min(res)\nmin_M <- M[min_index]\n\n# Creazione del dataframe per ggplot\ndf <- data.frame(M, res)\n\ndf |> \n  ggplot(aes(x = M, y = res)) +\n  geom_line(color = \"blue\") +\n  geom_vline(xintercept = min_M, linetype = \"dashed\", color = \"red\") +\n  labs(\n    x = \"Valore di M\",\n    y = \"Somma dei quadrati degli scarti\"\n  ) \n```\n\n::: {.cell-output-display}\n![](06_loc_scale_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nStampiamo il minimo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmin_M\n#> [1] 32.6\n```\n:::\n\n\nConfronto con la media:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(x)\n#> [1] 32.6\n```\n:::\n\nOsserviamo che il valore di `M` che minimizza la somma dei quadrati degli scarti coincide con la media dei dati, confermando il principio dei minimi quadrati.\n:::\n\n### Le proporzioni sono medie\n\nSe un insieme di dati è composto esclusivamente da valori binari (0 o 1), allora la somma corrisponde al numero totale di unità presenti, mentre la media rappresenta la proporzione di unità sul totale.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzero_one <- c(1, 1, 1, 0)\nresult <- mean(zero_one)\nresult\n#> [1] 0.75\n```\n:::\n\nÈ possibile sostituire 1 con il valore booleano True e 0 con False:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(c(TRUE, TRUE, TRUE, FALSE))\n#> [1] 0.75\n```\n:::\n\n\n### Limiti della media aritmetica\n\nLa media aritmetica, tuttavia, ha alcune limitazioni: non sempre è l'indice più adeguato per descrivere accuratamente la tendenza centrale della distribuzione, specialmente quando si verificano asimmetrie o valori anomali (outlier). In queste situazioni, è più indicato utilizzare la mediana o la media spuntata (come spiegheremo successivamente).\n\n::: {.callout-note collapse=\"true\" title=\"Come descrivere la tendenza centrale in distribuzioni asimmetriche\"}\n\nQuando una distribuzione è *asimmetrica*, gli indici di tendenza centrale – moda, mediana e media – assumono valori diversi e trasmettono informazioni complementari. Per illustrare questo concetto, analizziamo i dati del Progetto Natsal (`sexual-partners.csv`), che riportano il numero di partner sessuali di sesso opposto dichiarati da uomini e donne di età compresa tra 35 e 44 anni.\n\n1. **Esplorazione iniziale dei dati**\n\nEstratto casuale di dieci righe dal dataset:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsexual_partners[sample(1:nrow(sexual_partners), 10), ]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"NumPartners\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Woman\",\"2\":\"1\",\"_rn_\":\"1012\"},{\"1\":\"Man\",\"2\":\"1\",\"_rn_\":\"15\"},{\"1\":\"Woman\",\"2\":\"6\",\"_rn_\":\"1452\"},{\"1\":\"Woman\",\"2\":\"20\",\"_rn_\":\"1896\"},{\"1\":\"Woman\",\"2\":\"2\",\"_rn_\":\"1089\"},{\"1\":\"Woman\",\"2\":\"4\",\"_rn_\":\"1242\"},{\"1\":\"Woman\",\"2\":\"4\",\"_rn_\":\"1290\"},{\"1\":\"Man\",\"2\":\"8\",\"_rn_\":\"392\"},{\"1\":\"Woman\",\"2\":\"3\",\"_rn_\":\"1219\"},{\"1\":\"Man\",\"2\":\"30\",\"_rn_\":\"708\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIl dataset contiene due variabili principali:\n* `Gender`: genere del rispondente\n* `NumPartners`: numero di partner sessuali dichiarati\n\nVerifichiamo la numerosità campionaria per gruppo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsexual_partners |> \n  group_by(Gender) |> \n  summarise(count = n())\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"count\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Man\",\"2\":\"796\"},{\"1\":\"Woman\",\"2\":\"1193\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIl numero massimo riportato è molto elevato (oltre 500), ma per una visualizzazione più chiara limiteremo l'analisi a **valori ≤ 50**:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsexual_partners |> \n  group_by(Gender) |> \n  summarise(maximum = max(NumPartners))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"maximum\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Man\",\"2\":\"501\"},{\"1\":\"Woman\",\"2\":\"550\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n2. **Visualizzazione delle distribuzioni**\n\nCalcoliamo e rappresentiamo la distribuzione dei partner (con valori limitati a ≤50) separatamente per genere:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsexual_partners_truncated <- sexual_partners |> \n  filter(NumPartners <= 50)\n\npercentage_data <- sexual_partners_truncated %>%\n  group_by(Gender, NumPartners) %>%\n  summarise(Count = n(), .groups = \"drop\") %>%\n  group_by(Gender) %>%\n  mutate(Percentage = Count / sum(Count) * 100)\n\ny_max <- max(percentage_data$Percentage)\n\ngender_labels <- c(\"Man\" = \"Uomini 35–44\", \"Woman\" = \"Donne 35–44\")\n\npercentage_data |>\n  ggplot(aes(NumPartners, Percentage, fill = Gender)) +\n  geom_col(position = \"dodge\", color = \"black\") +\n  facet_wrap(~Gender, labeller = labeller(Gender = gender_labels)) +\n  scale_y_continuous(limits = c(0, y_max)) +\n  labs(x = \"Numero di partner sessuali dichiarati\", y = \"Percentuale\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](06_loc_scale_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa distribuzione risulta **fortemente asimmetrica positiva**: la maggior parte dei soggetti dichiara un numero basso di partner, mentre una coda lunga a destra rappresenta pochi individui con valori molto elevati.\n\n3. **Calcolo degli indici di tendenza centrale**\n\nCalcoliamo media, mediana e moda per ciascun genere:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nget_mode <- function(x) {\n  tbl <- table(x)\n  as.numeric(names(tbl)[which.max(tbl)])\n}\n\nsexual_partners_truncated |> \n  group_by(Gender) |> \n  summarise(\n    media   = mean(NumPartners, na.rm = TRUE),\n    mediana = median(NumPartners, na.rm = TRUE),\n    moda    = get_mode(NumPartners)\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Gender\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"media\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mediana\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"moda\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Man\",\"2\":\"11.35\",\"3\":\"7\",\"4\":\"1\"},{\"1\":\"Woman\",\"2\":\"7.51\",\"3\":\"5\",\"4\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n4. **Interpretazione dei risultati**\n\n* **Media**: notevolmente più alta della mediana e della moda, poiché fortemente influenzata dalla coda destra della distribuzione.\n* **Mediana**: valore centrale della distribuzione, molto meno sensibile ai valori estremi. Rappresenta una misura più robusta della tendenza centrale.\n* **Moda**: corrisponde al valore più frequente (1 partner), ma in distribuzioni così sparse fornisce un'informazione limitata.\n\n5. **Conclusioni pratiche per l'analisi**\n\n* In presenza di distribuzioni **asimmetriche**, la **mediana** è generalmente l'indice di tendenza centrale più affidabile e informativo.\n* È comunque utile riportare sia la **media** che la **moda** per documentare l'entità dell'asimmetria e le caratteristiche della distribuzione.\n* La descrizione numerica deve essere sempre accompagnata da una **visualizzazione grafica** (istogrammi, boxplot) che permetta di apprezzare visivamente la forma della distribuzione e la presenza di valori estremi.\n* Una descrizione completa richiede anche l'utilizzo di **misure di dispersione**, che esploreremo nella sezione successiva.\n\n:::\n\n### La media come rappresentazione della psicologia umana: un'arma a doppio taglio?\n\nLa media è uno degli strumenti statistici più semplici e intuitivi che i ricercatori utilizzano per sintetizzare i dati. È un indice di tendenza centrale familiare e intuitivo: se chiediamo a un gruppo di persone la loro età e calcoliamo la media, otteniamo un valore che sintetizza in un'unica cifra l'informazione disponibile. Ma cosa significa, in realtà, \"riassumere\" i dati con la media? E soprattutto, questa operazione ha senso quando si studiano i processi psicologici e il comportamento umano?\n\nIn molte discipline scientifiche, il concetto di media è utile perché descrive fenomeni che tendono a essere stabili e uniformi. Per esempio, se misuriamo l’altezza di un gruppo di persone, possiamo aspettarci che la distribuzione sia approssimativamente normale e che la media offra una stima ragionevole di un valore tipico. Tuttavia, la mente umana e i processi psicologici non funzionano come il sistema cardiovascolare o i muscoli. Ogni persona ha esperienze uniche che plasmano le sue risposte, i suoi pensieri e le sue emozioni. \n\nUn problema centrale, sollevato da @speelman2013mean, riguarda l'implicita assunzione che ci sia un *vero valore* sottostante ai processi psicologici che possiamo stimare attraverso la media, come se il comportamento umano fosse determinato da meccanismi identici in ogni individuo, con le differenze attribuibili solo a \"rumore\" sperimentale. Questo approccio, tipico della psicologia sperimentale tradizionale, assume che testare un gruppo di persone e mediare i loro risultati ci permetta di rivelare la struttura comune della mente umana. Ma questa assunzione è davvero giustificata?\n\n### La fallacia ergodica e l’illusione dell’universalità {#sec-eda-ergodic-fallacy}\n\nUn errore metodologico frequente nella psicologia è la cosiddetta *fallacia ergodica*, ovvero l’errata convinzione che le caratteristiche medie di un gruppo possano essere automaticamente applicate ai singoli individui che lo compongono [@speelman2024most]. Questo equivoco nasce dall’idea che la media descriva un valore \"tipico\" valido per tutti, senza considerare le differenze individuali o le variazioni nel tempo.\n\nImmaginiamo di studiare la felicità di un gruppo di persone nel corso di una settimana e di calcolare la media dei loro punteggi di benessere giornalieri. Se lunedì una persona ha un punteggio di 2 (molto infelice), mercoledì 5 (moderatamente felice) e sabato 8 (molto felice), il suo punteggio medio sarà 5. Tuttavia, questo valore intermedio non rappresenta in alcun modo la realtà soggettiva vissuta da quella persona nei singoli giorni. Lo stesso problema si pone quando si usano le medie per descrivere abilità cognitive, tratti di personalità o stati emotivi: la media può nascondere fluttuazioni e differenze individuali fondamentali per comprendere la psicologia umana.\n\nIl rischio, come sottolineato da @molden2006finding, è che il nostro desiderio di trovare *universalità* nei processi cognitivi ci porti a enfatizzare somiglianze tra le persone, ignorando le variazioni individuali che possono essere altrettanto, se non più, informative. Per esempio, due studenti con lo stesso punteggio medio in un test di memoria potrebbero aver ottenuto quel risultato in modi completamente diversi: uno potrebbe aver avuto prestazioni costantemente nella media, mentre l’altro potrebbe aver avuto picchi di eccellenza alternati a difficoltà estreme.\n\n### La media: uno strumento da usare con cautela\n\nQuesti problemi non significano che la media sia inutile in psicologia. È un indicatore potente e spesso informativo, ma deve essere interpretato con cautela. In particolare, non può essere usata per fare inferenze sui singoli individui senza considerare altre misure, come la *varianza* e la *deviazione standard*, che ci dicono quanto i dati siano dispersi intorno alla media.\n\nIn psicologia, comprendere la variabilità è tanto importante quanto individuare una tendenza centrale. Se vogliamo davvero capire il comportamento umano, dobbiamo chiederci non solo *qual è il valore medio?* ma anche *quanto variano i dati?* e *cosa ci dice questa variabilità sulle differenze individuali?* Nella prossima sezione, esamineremo questi concetti e vedremo come la varianza e la deviazione standard ci aiutano a catturare le differenze che la media, da sola, non può rivelare.\n\n::: {.callout-note collapse=\"true\" title=\"La scelta della misura di tendenza centrale\"}\n\nLa selezione della misura di tendenza centrale più adeguata è un aspetto fondamentale dell'analisi statistica. Tale scelta deve basarsi sulla natura dei dati a disposizione, sulla loro distribuzione e sulla potenziale presenza di valori anomali o asimmetrie. Comprendere le caratteristiche distintive di ciascun indicatore è cruciale per una rappresentazione corretta e significativa dell’informazione.\n\n**La moda** trova la sua principale applicazione nei dati di tipo categoriale o nominale, dove rappresenta l'unica misura di tendenza centrale calcolabile. La sua utilità è massima nelle distribuzioni unimodali, ovvero quelle in cui un unico valore emerge con frequenza predominante. Al contrario, in presenza di distribuzioni multimodali, caratterizzate da più picchi di frequenza, la moda perde di significatività, poiché l’identificazione di un singolo valore rappresentativo diventa impossibile. Nei dati continui, infine, la moda può spesso non essere definita o risultare poco informativa.\n\n**La media aritmetica** è l’indicatore più comune e fornisce una stima eccellente della tendenza centrale per distribuzioni simmetriche e prive di valori anomali. Tuttavia, la media presenta una critica debolezza: la sua estrema sensibilità ai valori estremi. In distribuzioni asimmetriche o contaminata da outlier, la media subisce uno spostamento marcato verso la coda della distribuzione, finendo per non rappresentare più fedelmente la maggior parte dei dati.\n\n**La Media Spuntata** si propone come una valida alternativa alla media tradizionale quando si sospetta la presenza di valori anomali. Questo indicatore, calcolato escludendo una certa percentuale dei valori più estremi (ad esempio, il 5% per ogni coda), offre un compromesso vantaggioso. Rispetto alla media, è molto più robusta agli outlier; rispetto alla mediana, tiene conto di un maggior numero di osservazioni, preservando parte dell'informazione contenuta nei dati.\n\n**La mediana**, essendo definita come il valore centrale di una distribuzione ordinata, possiede una robustezza intrinseca ai valori anomali. La sua natura posizionale fa sì che essa non venga influenzata dall’entità numerica dei dati, ma solo dal loro rango. Questo la rende la misura d’elezione per distribuzioni fortemente asimmetriche o con outlier. Inoltre, è l’indicatore preferibile per i dati ordinali, dove le distanze tra le categorie non sono definite numericamente.\n\n**Linee guida per una scelta consapevole.**\n\nPer distribuzioni simmetriche e unimodali, la media aritmetica costituisce generalmente la scelta ottimale, in quanto ne coglie appieno il centro. Quando si affrontano distribuzioni asimmetriche o dataset contenenti valori anomali, la mediana è da preferire per la sua innata resistenza a tali distorsioni. La media spuntata rappresenta un'ottima opzione quando si desidera attenuare l’impatto di pochi outlier senza rinunciare completamente all’informazione che forniscono.\nPer i dati categoriali (nominali), la moda è l’unica misura applicabile, a patto che la distribuzione sia unimodale. In scenari complessi come le distribuzioni multimodali, nessuna singola misura è sufficiente a descrivere la tendenza centrale. In questi casi, è indispensabile affiancare agli indicatori statistici una visualizzazione grafica (ad esempio un istogramma) e una descrizione analitica dei diversi picchi presenti.\n\nIn sintesi, non esiste una misura migliore in assoluto. La media è potente per dati simmetrici, la mediana è lo strumento robusto per proteggersi dalle distorsioni, la media spuntata è un utile compromesso e la moda è essenziale per i dati categoriali. La scelta deve sempre essere guidata da una attenta valutazione preliminare della distribuzione dei dati.\n:::\n\n## La variabilità nei dati psicologici  \n\nNei fenomeni psicologici e comportamentali, *la variabilità è una caratteristica intrinseca*. Ad esempio, se misuriamo il livello di stress percepito da una persona più volte nella stessa giornata, è raro osservare lo stesso valore anche utilizzando strumenti identici. Allo stesso modo, un questionario standardizzato sull’autostima somministrato a un gruppo di studenti universitari restituirà punteggi differenti per ciascun partecipante. Anche registrando i tempi di reazione in un compito cognitivo, noteremo fluttuazioni sia tra individui diversi sia nelle prestazioni dello stesso individuo in prove ripetute.  \n\nQuesta *dispersione sistematica* non è un “rumore” da ignorare, ma un elemento informativo cruciale. L’analisi statistica in psicologia ha infatti uno scopo duplice: da un lato, quantificare la variabilità; dall’altro, identificarne le origini. Differenze individuali, contesto ambientale, errori di misurazione o interazioni tra fattori sono solo alcune delle possibili fonti che contribuiscono alla variazione osservata.  \n\nIn questa sezione esploreremo:  \n\n1. *la scomposizione della variabilità* in componenti spiegate (attribuibili a fattori noti, come un intervento sperimentale) e non spiegate (legate a elementi casuali o non controllati).  \n2. *strumenti per descriverla*, sia attraverso rappresentazioni grafiche (boxplot, istogrammi) sia mediante indici numerici (differenza interquartile, varianza, deviazione standard).  \n\nComprendere la variabilità non è un esercizio tecnico, ma un passo fondamentale per interpretare fenomeni complessi come le differenze di personalità, le oscillazioni emotive o l’efficacia di una terapia. Ogni modello psicologico, infatti, deve fare i conti con questa dimensione dinamica e multideterminata dei dati.  \n\n### Quantili\n\nAccanto alle misure di tendenza centrale, i *quantili* descrivono la posizione relativa di un'osservazione all'interno di una distribuzione. Mentre media, mediana e moda individuano un valore \"tipico\", i quantili rispondono a una domanda complementare: qual è il valore al di sotto del quale ricade una determinata proporzione dei dati?\n\n### Definizione formale\n\nIl quantile di ordine $p$ (con $0 < p < 1$) è il valore $q_p$ tale che una proporzione $p$ delle osservazioni è minore o uguale a $q_p$. Formalmente, dati $n$ valori ordinati $x_{(1)} \\leq x_{(2)} \\leq ... \\leq x_{(n)}$, il quantile di ordine $p$ si ottiene calcolando $k = \\lceil p \\cdot n \\rceil$, dove $\\lceil \\cdot \\rceil$ rappresenta la funzione di arrotondamento per eccesso. Il quantile corrisponde allora a $q_p = x_{(k)}$.\n\nQuando $p \\cdot n$ non è un intero, si ricorre in genere all'interpolazione lineare tra le due osservazioni più vicine, metodo implementato nella maggior parte dei software statistici.\n\nPer chiarire il calcolo, consideriamo un esempio semplice: dati ordinati {15, 20, 23, 25, 28, 30, 35, 40, 45, 50}. Il 30° percentile ($p=0.3$) si determina come $k = \\lceil 0.3 \\cdot 10 \\rceil = 3$, dunque $q_{0.3} = 23$.\n\n### Percentili e quartili: casi particolari\n\nUn caso speciale di quantili sono i *percentili*, che suddividono la distribuzione in cento parti uguali. Tra questi, assumono particolare rilievo i *quartili*:\n\n- **primo quartile (Q₁)**: 25° percentile;\n- **secondo quartile (Q₂)**: 50° percentile (corrisponde alla mediana);\n- **terzo quartile (Q₃)**: 75° percentile.\n\nI quartili delimitano la distribuzione in quattro segmenti di uguale numerosità, fornendo una sintesi robusta della sua posizione e dispersione.\n\n### Esempio applicativo\n\nPer illustrare l'uso pratico dei quantili, consideriamo nuovamente la variabile `NumPartners`, distintamente per genere. Calcoliamo il 10° e il 90° percentile:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Quantili per gli uomini\nquantile(\n  sexual_partners[sexual_partners$Gender == \"Man\", \"NumPartners\"], \n  probs = c(0.1, 0.9)\n  )\n#>  10%  90% \n#>  1.0 34.5\n\n# Quantili per le donne\nquantile(\n  sexual_partners[sexual_partners$Gender == \"Woman\", \"NumPartners\"], \n  probs = c(0.1, 0.9)\n  )\n#> 10% 90% \n#>   1  18\n```\n:::\n\n\nI risultati rivelano che:\n\n- **tra gli uomini**, il 10% dei soggetti ha dichiarato al massimo un partner, mentre il 10% con valori più elevati supera i 34 partner;\n- **tra le donne**, il 10° percentile corrisponde anch'esso a un partner, ma il 90° percentile non supera i 18 partner.\n\nQuesta differenza evidenzia come le due distribuzioni condividano una base simile nella parte inferiore (numerosi individui con pochi partner), ma divergano significativamente nella coda superiore: negli uomini, la presenza di alcuni valori estremi allunga la distribuzione verso destra, generando una maggiore asimmetria positiva.\n\n### Misure di dispersione basate sui quantili\n\nI quantili possono essere utilizzati anche per costruire indici di variabilità che non fanno ipotesi sulla forma della distribuzione. La misura più semplice è l’*intervallo di variazione*, pari alla differenza tra valore massimo e minimo. Questo indice è immediato da calcolare, ma dipende esclusivamente dagli estremi e risulta quindi molto sensibile agli outlier.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(12, 18, 20, 22, 25, 28, 30, 35)\nrange(x)\n#> [1] 12 35\ndiff(range(x))\n#> [1] 23\n```\n:::\n\n\nNell’esempio l’intervallo è 23, valore che descrive l’ampiezza complessiva dei dati ma non la loro distribuzione interna.\n\nUn indicatore più robusto è la *differenza interquartile (IQR)*, che misura la distanza fra il terzo e il primo quartile, racchiudendo così il 50% centrale dei dati.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nIQR(x)\n#> [1] 9\n```\n:::\n\n\nSe in un gruppo di studenti i quartili sono $Q_1 = 25$ e $Q_3 = 40$, l’IQR è pari a 15: significa che metà dei punteggi si colloca in un intervallo di 15 unità. Questo indice riduce l’influenza dei valori estremi, anche se non rappresenta l’intera dispersione della distribuzione.\n\nIn sintesi, l’intervallo di variazione e l’IQR offrono due prospettive complementari: il primo fornisce un’idea immediata dell’ampiezza totale dei dati, il secondo descrive la variabilità tipica della parte centrale della distribuzione. Entrambi hanno limiti che rendono necessario affiancarli a misure più complete, come la varianza e la deviazione standard, di cui parleremo nella sezione successiva.\n\n### La varianza\n\nLa *varianza* è una delle misure di dispersione più utilizzate in statistica perché tiene conto di *tutte* le osservazioni e descrive quanto i valori si discostano dalla loro media. Formalmente, se abbiamo $n$ osservazioni $x_1, x_2, \\dots, x_n$ e indichiamo con $\\bar{x} = \\frac{1}{n} \\sum_{i=1}^n x_i$ la loro media, la varianza (in versione *descrittiva*) si calcola così:\n\n$$\nS^2 = \\frac{1}{n} \\sum_{i=1}^n (x_i - \\bar{x})^2.\n$$ {#eq-var-descr}\n\nIn altre parole, per trovare la varianza:\n\n1. calcoliamo la media di tutti i valori ($\\bar{x}$),\n2. sottraiamo la media a ciascun valore, ottenendo così lo *scarto* $(x_i - \\bar{x})$,\n3. eleviamo ogni scarto al quadrato, per rendere positivi i valori ed enfatizzare gli scostamenti più grandi,\n4. infine, facciamo la *media* di questi quadrati.\n\nMaggiore è la varianza, maggiore è la variabilità (o dispersione) dei dati rispetto alla media. Al contrario, una varianza prossima allo zero indica che le osservazioni sono molto vicine tra loro e quasi coincidenti con la media.\n\n> **Nota su popolazione e campione.** Spesso, nell’analisi di dati campionari, la varianza viene calcolata usando $\\frac{1}{n-1}$ al denominatore al posto di $\\frac{1}{n}$. In questo modo otteniamo una stima corretta (non distorta) della varianza della popolazione. Nel contesto della formula sopra riportata, invece, stiamo calcolando la varianza *descrittiva* (o *popolazione completa*).\n\n::: {.callout-caution collapse=\"true\" title=\"Esempio\"}\n\nImmaginiamo di aver misurato il numero di *ore di studio* giornaliere di un piccolo gruppo di partecipanti a un esperimento di psicologia. I dati raccolti sono:\n\n$$\nx = \\{3,\\, 1,\\, 4,\\, 2\\}.\n$$\n\nPasso 1: Calcolo della media\n\n$$\n\\bar{x} = \\frac{3 + 1 + 4 + 2}{4} = \\frac{10}{4} = 2.5.\n$$\n\nPasso 2: Scarti dalla media\n\n- Per il primo valore ($x_1 = 3$): $3 - 2.5 = 0.5$.\n- Per il secondo valore ($x_2 = 1$): $1 - 2.5 = -1.5$.\n- Per il terzo valore ($x_3 = 4$): $4 - 2.5 = 1.5$.\n- Per il quarto valore ($x_4 = 2$): $2 - 2.5 = -0.5$.\n\nPasso 3: Quadrati degli scarti\n\n- $(0.5)^2 = 0.25$.\n- $(-1.5)^2 = 2.25$.\n- $(1.5)^2 = 2.25$.\n- $(-0.5)^2 = 0.25$.\n\nPasso 4: Calcolo della varianza\n\nFacciamo la media di questi valori:\n\n$$\nS^2 = \\frac{0.25 + 2.25 + 2.25 + 0.25}{4} = \\frac{5}{4} = 1.25.\n$$\n\nDunque la varianza è 1.25.\n:::\n\n### Interpretazione\n\nNel caso dell'esempio precedente relativo alle ore di studio giornaliere, una varianza pari a 1.25 indica che le ore di studio giornaliere si discostano, in media, di 1.25 unità quadrate dalla media di 2.5 ore. Per comprendere meglio l’ordine di grandezza di questa dispersione, solitamente si fa riferimento alla *deviazione standard*, che è la radice quadrata della varianza. In questo caso, $\\sqrt{1.25} \\approx 1.12$ ore.\n\n- Se la varianza (o la deviazione standard) fosse stata molto più grande, avremmo dedotto che gli studenti del campione presentano abitudini di studio molto diverse.\n- Al contrario, se la varianza fosse prossima a 0, significherebbe che quasi tutti studiano un numero di ore molto simile a 2.5.\n\n### Calcolo in R\n\nSe volessimo effettuare in R i calcoli relativi all'esempio sulle ore di studio, potremmo fare così:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Dati\nx <- c(3, 1, 4, 2)\n\n# Calcolo manuale della media\nmedia_x <- mean(x)\n\n# Calcolo manuale della varianza secondo la formula descrittiva\nvarianza_descr <- mean((x - media_x)^2)\nvarianza_descr\n#> [1] 1.25\n# [1] 1.25\n\n# Calcolo della varianza con la funzione var() di R\n# (Attenzione: per default var() usa n-1 al denominatore)\nvarianza_campionaria <- var(x)\nvarianza_campionaria\n#> [1] 1.67\n# [1] 1.666667\n```\n:::\n\nOsserviamo che `var(x)` dà un valore di circa 1.67 perché R, di default, calcola la *varianza campionaria* (con $n-1$ al denominatore). Se vogliamo la *varianza descrittiva* (come nella formula con $n$ al denominatore), usiamo la nostra `varianza_descr`.\n\nIn sintesi, la varianza fornisce un modo per quantificare quanto siano diverse tra loro le osservazioni. Nel caso dell’esempio sulle ore di studio, abbiamo visto che i valori, pur non essendo tutti identici, non mostrano una dispersione eccessiva (la varianza è 1.25). Se i comportamenti di studio fossero estremamente diversificati (per esempio, se qualcuno studiasse 0 ore al giorno e qualcun altro 10), la varianza sarebbe molto più elevata, indicando una marcata eterogeneità nel campione.\n\n### Stima della varianza della popolazione\n\nSi noti il denominatore della formula della varianza. Nell'@eq-var-descr, ho utilizzato $n$ come denominatore (l'ampiezza campionaria, ovvero il numero di osservazioni nel campione). In questo modo, otteniamo la varianza come *statistica descrittiva* del campione. Tuttavia, è possibile utilizzare $n-1$ come denominatore alternativo:\n\n$$\ns^2 = \\frac{1}{n-1} \\sum_{i=1}^n (x_i - \\bar{x})^2 .\n$$ {#eq-var-stimatore}\n\nIn questo secondo caso, otteniamo la varianza come *stimatore* della varianza della popolazione. Si può dimostrare che l'@eq-var-stimatore fornisce una stima corretta (ovvero, non distorta) della varianza della popolazione da cui abbiamo ottenuto il campione, mentre l'@eq-var-descr fornisce (in media) una stima troppo piccola della varianza della popolazione. Si presti attenzione alla notazione: $S^2$ rappresenta la varianza come statistica descrittiva, mentre $s^2$ rappresenta la varianza come stimatore.\n\n::: {.callout-note collapse=\"true\" title=\"Simulazione\"}\n\nPer illustrare questo punto, svolgiamo una simulazione. Consideriamo la distribuzione dei punteggi del quoziente di intelligenza (QI). I valori del QI seguono una particolare distribuzione chiamata *distribuzione normale* (v. @sec-eda-intro-gauss), con media 100 e deviazione standard 15. La forma di questa distribuzione è illustrata nella figura seguente.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Define parameters\nx <- seq(100 - 4 * 15, 100 + 4 * 15, by = 0.001)\nmu <- 100\nsigma <- 15\n\n# Compute the PDF\npdf <- dnorm(x, mean = mu, sd = sigma)\n\n# Plot using ggplot2\ndata <- tibble(x = x, pdf = pdf)\nggplot(data, aes(x = x, y = pdf)) +\n  geom_line() +\n  labs(\n    x = \"QI\", \n    y = \"Densità\"\n  ) \n```\n\n::: {.cell-output-display}\n![](06_loc_scale_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nSupponiamo di estrarre un campione casuale di 4 osservazioni dalla popolazione del quoziente di intelligenza -- in altre parole, supponiamo di misurare il quoziente di intelligenza di 4 persone prese a caso dalla popolazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123) \nx <- rnorm(4, mean = 100, sd = 15)\nprint(x)\n#> [1]  91.6  96.5 123.4 101.1\n```\n:::\n\n\nCalcoliamo la varianza usando $n$ al denominatore. Si noti che la vera varianza del quoziente di intelligenza è $15^2$ = 225.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar(x)\n#> [1] 197\n```\n:::\n\n\nConsideriamo ora 10 campioni casuali del QI, ciascuno di ampiezza 4.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu <- 100\nsigma <- 15\nsize <- 4\nniter <- 10\nrandom_samples <- list()\n\nset.seed(123) \n\nfor (i in 1:niter) {\n  one_sample <- rnorm(size, mean = mu, sd = sigma)\n  random_samples[[i]] <- one_sample\n}\n```\n:::\n\n\nIl primo campione è\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrandom_samples[1]\n#> [[1]]\n#> [1]  91.6  96.5 123.4 101.1\n```\n:::\n\n\nIl decimo campione è\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrandom_samples[10]\n#> [[1]]\n#> [1] 108.3  99.1  95.4  94.3\n```\n:::\n\n\nStampiamo i valori di tutti i 10 campioni.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrs <- do.call(rbind, random_samples)\nrs\n#>        [,1]  [,2]  [,3]  [,4]\n#>  [1,]  91.6  96.5 123.4 101.1\n#>  [2,] 101.9 125.7 106.9  81.0\n#>  [3,]  89.7  93.3 118.4 105.4\n#>  [4,] 106.0 101.7  91.7 126.8\n#>  [5,] 107.5  70.5 110.5  92.9\n#>  [6,]  84.0  96.7  84.6  89.1\n#>  [7,]  90.6  74.7 112.6 102.3\n#>  [8,]  82.9 118.8 106.4  95.6\n#>  [9,] 113.4 113.2 112.3 110.3\n#> [10,] 108.3  99.1  95.4  94.3\n```\n:::\n\n\nPer ciascun campione (ovvero, per ciascuna riga della matrice\nprecedente), calcoliamo la varianza usando la formula con $n$ al denominatore.\nOtteniamo così 10 stime della varianza della popolazione del QI.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx_var <- apply(rs, 1, var)  # Applica la funzione var su ciascuna riga\nprint(x_var)\n#>  [1] 196.94 337.54 168.55 218.68 333.48  34.52 264.38 234.08   1.97  40.47\n```\n:::\n\n\nNotiamo due cose: \n\n- le stime sono molto diverse tra loro; questo fenomeno è noto con il nome di *variabilità campionaria*;\n- in media le stime sono troppo piccole.\n\nPer aumentare la sicurezza riguardo al secondo punto menzionato in precedenza, ripeteremo la simulazione utilizzando un numero di iterazioni maggiore.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu <- 100\nsigma <- 15\nsize <- 4\nniter <- 10000\nrandom_samples <- list()\n\nset.seed(123) # Replace 123 with your desired seed for reproducibility\n\nfor (i in 1:niter) {\n  one_sample <- rnorm(size, mean = mu, sd = sigma)\n  random_samples[[i]] <- one_sample\n}\n\nrs <- do.call(rbind, random_samples)\nx_var <- apply(rs, 1, var) * (size - 1) / size  # Adjust for population variance (ddof = 0)\n```\n:::\n\n\nEsaminiamo la distribuzione dei valori ottenuti.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create a data frame for plotting\ndata <- data.frame(x_var = x_var)\n\n# Plot the histogram using ggplot2\nggplot(data, aes(x = x_var)) +\n  geom_histogram(fill = \"lightblue\", bins = 30, color = \"black\") +\n  scale_x_continuous(limits = c(0, 1500)) +\n  scale_y_continuous(limits = c(0, 2250)) +\n  labs(\n    x = \"Varianza\", \n    y = \"Frequenza\"\n  )\n```\n\n::: {.cell-output-display}\n![](06_loc_scale_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa stima più verosimile della varianza del QI è dato dalla media di\nquesta distribuzione. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(x_var)\n#> [1] 169\n```\n:::\n\n\nSi noti che il nostro spospetto è stato confermato: il valore medio della stima della varianza ottenuta con l'@eq-var-descr è troppo piccolo rispetto al valore corretto di $15^2 = 225$. \n\nRipetiamo ora la simulazione usando la formula della varianza con $n-1$ al denominatore.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123) \n\nmu <- 100\nsigma <- 15\nsize <- 4\nniter <- 10000\nrandom_samples <- list()\n\nfor (i in 1:niter) {\n  one_sample <- rnorm(size, mean = mu, sd = sigma)\n  random_samples[[i]] <- one_sample\n}\n\nrs <- do.call(rbind, random_samples)\nx_var <- apply(rs, 1, var)  # ddof = 1 is default for var in R\n```\n:::\n\n\nEsaminiamo la distribuzione dei valori ottenuti.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create a data frame for plotting\ndata <- data.frame(x_var = x_var)\n\n# Plot the histogram using ggplot2\nggplot(data, aes(x = x_var)) +\n  geom_histogram(fill = \"lightblue\", bins = 30, color = \"black\") +\n  scale_x_continuous(limits = c(0, 1500)) +\n  scale_y_continuous(limits = c(0, 2250)) +\n  labs(\n    x = \"Varianza Corretta\", \n    y = \"Frequenza\"\n  )\n```\n\n::: {.cell-output-display}\n![](06_loc_scale_files/figure-html/unnamed-chunk-39-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nNel secondo caso, se utilizziamo $n-1$ come denominatore per calcolare la stima della varianza, il valore atteso di questa stima è molto vicino al valore corretto di 225. Se il numero di campioni fosse infinito, i due valori sarebbero identici.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(x_var)\n#> [1] 225\n```\n:::\n\n\nIn conclusione, le due formule della varianza hanno scopi diversi. \n\n- La formula della varianza con $n$ al denominatore viene utilizzata come statistica descrittiva per descrivere la variabilità di un particolare campione di osservazioni.\n- D'altro canto, la formula della varianza con $n-1$ al denominatore viene utilizzata come stimatore per ottenere la migliore stima della varianza della popolazione da cui quel campione è stato estratto.\n:::\n\n### Deviazione standard\n\nPer interpretare la varianza in modo più intuitivo, si può calcolare la deviazione standard (o scarto quadratico medio o scarto tipo) prendendo la radice quadrata della varianza. La deviazione standard è espressa nell'unità di misura originaria dei dati, a differenza della varianza che è espressa nel quadrato dell'unità di misura dei dati. La deviazione standard fornisce una misura della dispersione dei dati attorno alla media, rendendo più facile la comprensione della variabilità dei dati.\n\nLa deviazione standard (o scarto quadratico medio, o scarto tipo) è definita come:\n\n$$\ns^2 = \\sqrt{(n-1)^{-1} \\sum_{i=1}^n (x_i - \\bar{x})^2}.\n$$ {#eq-sd-stimatore}\n\nQuando tutte le osservazioni sono uguali, $s = 0$, altrimenti $s > 0$.\n\n::: {.callout-note}\nIl termine *standard deviation* è stato introdotto in statistica da Pearson nel 1894 assieme alla lettera greca $\\sigma$ che lo rappresenta. Il termine italiano \"deviazione standard\" ne è la traduzione più utilizzata nel linguaggio comune; il termine dell’[Ente Nazionale Italiano di Unificazione](https://it.wikipedia.org/wiki/Ente_nazionale_italiano_di_unificazione) è tuttavia “scarto tipo”, definito come la radice quadrata positiva della varianza.\n:::\n\nLa deviazione standard $s$ dovrebbe essere utilizzata solo quando la media è una misura appropriata per descrivere il centro della distribuzione, ad esempio nel caso di distribuzioni simmetriche. Tuttavia, è importante tener conto che, come la media $\\bar{x}$, anche la deviazione standard è fortemente influenzata dalla presenza di dati anomali, ovvero pochi valori che si discostano notevolmente dalla media rispetto agli altri dati della distribuzione. In presenza di dati anomali, la deviazione standard può risultare ingannevole e non rappresentare accuratamente la variabilità complessiva della distribuzione. Pertanto, è fondamentale considerare attentamente il contesto e le caratteristiche dei dati prima di utilizzare la deviazione standard come misura di dispersione. In alcune situazioni, potrebbe essere più appropriato ricorrere a misure di dispersione robuste o ad altre statistiche descrittive per caratterizzare la variabilità dei dati in modo più accurato e affidabile.\n\n### Interpretazione\n\nLa deviazione standard misura la dispersione dei dati rispetto alla media aritmetica. In termini semplici, indica quanto, in media, ciascun valore osservato si discosta dalla media del campione. Anche se è simile allo scarto semplice medio campionario (la media dei valori assoluti degli scarti rispetto alla media), la deviazione standard utilizza lo scarto quadratico medio e produce un valore leggermente diverso.\n\n::: {#exm-}\nPer verificare l'interpretazione della deviazione standard, utilizziamo i punteggi relativi alle ore di studio di un piccolo numero di studenti.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(3, 1, 4, 2)\n\nstd_x <- sqrt(var(x) * 3 / 4)\nstd_x\n#> [1] 1.12\n```\n:::\n\n\nLa deviazione standard calcolata è 1.12. Questo valore ci dice che, in media, ciascun punteggio si discosta di circa 1.12 ore dalla media aritmetica delle ore di studio di questo gruppo di studenti.\n\n- Valore più alto: indica maggiore dispersione dei dati intorno alla media.\n- Valore più basso: i dati sono più concentrati vicino alla media.\n\nSe calcoliamo anche lo scarto semplice medio campionario per confronto, otteniamo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(abs(x - mean(x)))\n#> [1] 1\n```\n:::\n\n\nI due valori (deviazione standard e scarto semplice medio) sono simili ma non identici, a causa delle diverse definizioni matematiche.\n:::\n\n### Varianza spiegata e non spiegata\n\nLa varianza, come abbiamo visto, misura quanto i dati si disperdono attorno alla media. Un concetto fondamentale nei *modelli statistici lineari* è la distinzione tra *varianza spiegata* e *varianza non spiegata*, che ci permette di valutare quanto bene un modello teorico riesca a chiarire la variabilità osservata nei dati.\n\n### Decomposizione della varianza\n\nQuando osserviamo un fenomeno (ad esempio i risultati di un test), troviamo inevitabilmente differenze tra individui. Queste differenze possono essere suddivise in due componenti principali:\n\n- *varianza spiegata*: la parte di variabilità che può essere attribuita a fattori identificati e misurabili;\n- *varianza non spiegata*: la parte rimanente di variabilità che non è chiarita dai fattori considerati.\n\nFormalmente, questa decomposizione può essere espressa come:\n\n$$\n\\sum_{i=1}^{n}(Y_i - \\bar{Y})^2 = \\sum_{i=1}^{n}(\\hat{Y}_i - \\bar{Y})^2 + \\sum_{i=1}^{n}(Y_i - \\hat{Y}_i)^2 ,\n$$\ndove:\n\n- $Y_i$ sono i dati osservati,\n- $\\bar{Y}$ è la media dei dati osservati,\n- $\\hat{Y}_i$ sono i valori attesi (previsti) dal modello teorico.\n\nIntuitivamente:\n\n- la *varianza totale* (lato sinistro della formula) rappresenta la dispersione complessiva dei dati attorno alla loro media;\n- la *varianza spiegata* (primo termine a destra) indica quanto bene i valori previsti dal modello descrivono il comportamento dei dati;\n- la *varianza non spiegata* (secondo termine a destra) riflette ciò che il modello non riesce a prevedere.\n\n::: {.callout-note collapse=\"true\" title=\"Simulazione\"}\n\nSupponiamo di analizzare i punteggi di un esame universitario di \"Psicometria\" ottenuti da 200 studenti. La nostra teoria indica che i punteggi dipendano da:\n\n1. Ore settimanali dedicate allo studio;\n2. Presenza o assenza di \"paura della matematica\" (*math anxiety*) [@barroso2021meta].\n\nNello specifico, ipotizziamo:\n\n- una relazione positiva tra ore di studio e punteggio ottenuto;\n- una riduzione del 30% del punteggio per chi presenta paura della matematica rispetto agli altri studenti, a parità di ore di studio.\n\nEcco la simulazione in R:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Simuliamo i dati per 200 studenti\nn <- 200\nore_studio <- runif(n, min = 2, max = 15) |> round()\npaura_mat <- rbinom(n, 1, prob = 0.3)\n\nk <- 2  # Ogni ora di studio corrisponde a circa 2 punti\n\n# Calcoliamo i punteggi attesi, limitati a 30 punti massimo\npunteggio_atteso <- ore_studio * k * ifelse(paura_mat == 1, 0.7, 1) |> round()\npunteggio_atteso <- ifelse(punteggio_atteso > 30, 30, punteggio_atteso)\n\n# Generiamo punteggi reali aggiungendo casualità (tra 0 e 30 punti)\npunteggio_reale <- (punteggio_atteso + rnorm(n, mean = 0, sd = 3)) |> round()\npunteggio_reale <- pmin(pmax(punteggio_reale, 0), 30)\n\n# Creiamo il dataset finale\ndata <- data.frame(ore_studio, paura_mat, punteggio_atteso, punteggio_reale)\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"ore_studio\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"paura_mat\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"punteggio_atteso\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"punteggio_reale\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"6\",\"2\":\"0\",\"3\":\"12\",\"4\":\"19\",\"_rn_\":\"1\"},{\"1\":\"12\",\"2\":\"1\",\"3\":\"24\",\"4\":\"28\",\"_rn_\":\"2\"},{\"1\":\"7\",\"2\":\"0\",\"3\":\"14\",\"4\":\"13\",\"_rn_\":\"3\"},{\"1\":\"13\",\"2\":\"0\",\"3\":\"26\",\"4\":\"28\",\"_rn_\":\"4\"},{\"1\":\"14\",\"2\":\"0\",\"3\":\"28\",\"4\":\"27\",\"_rn_\":\"5\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"6\",\"4\":\"5\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nCalcoliamo ora la decomposizione della varianza usando le formule indicate:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Media dei punteggi reali\nmedia_reale <- mean(data$punteggio_reale)\n\n# Calcolo delle componenti della varianza\nvarianza_totale <- mean((data$punteggio_reale - media_reale)^2)\nvarianza_spiegata <- mean((data$punteggio_atteso - media_reale)^2)\nvarianza_non_spiegata <- mean((data$punteggio_reale - data$punteggio_atteso)^2)\n\n# Risultati\nc(varianza_totale, varianza_spiegata, varianza_non_spiegata)\n#> [1] 60.37 51.65  8.29\n```\n:::\n\n\nInterpretazione dei risultati:\n\n- la *varianza totale* indica quanto in generale i punteggi differiscono tra loro,\n- la *varianza spiegata* rappresenta quanto della variabilità totale può essere attribuita ai fattori teorici (ore di studio e paura della matematica),\n- la *varianza non spiegata* evidenzia la variabilità residua che il modello non riesce a cogliere.\n\nLa proporzione di varianza spiegata è data dal rapporto:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprop_spiegata <- varianza_spiegata / varianza_totale\nprop_spiegata\n#> [1] 0.856\n```\n:::\n\n\nQuesta proporzione è sempre compresa tra 0 e 1:\n\n- valori vicini a 1 indicano che il modello è efficace nel descrivere i dati;\n- valori vicini a 0 suggeriscono che il modello non cattura adeguatamente la realtà osservata.\n\nQuesta decomposizione della varianza è uno strumento cruciale per valutare l'efficacia delle teorie e dei modelli statistici. Approfondiremo ulteriormente questi aspetti nel capitolo dedicato ai *modelli di regressione* (v.  @sec-linear-models-biv-model-frequentist).\n:::\n\n### Deviazione mediana assoluta\n\nLa *deviazione mediana assoluta* (MAD) è una misura robusta di dispersione basata sulla mediana. È definita come la mediana dei valori assoluti delle deviazioni dei dati rispetto alla mediana:\n\n$$\n\\text{MAD} = \\text{median} \\left( |X_i - \\text{median}(X)| \\right) \n$$ {#eq-mad-def}\n\nLa MAD è particolarmente utile per analizzare dati contenenti outlier o distribuzioni asimmetriche, poiché è meno influenzata dai valori estremi rispetto alla deviazione standard.\n\n### Relazione tra MAD e deviazione standard in una distribuzione normale\n\nQuando i dati seguono una distribuzione normale (gaussiana), esiste una relazione approssimativa tra MAD e deviazione standard. La MAD può essere convertita in una stima della deviazione standard moltiplicandola per una costante di 1.4826:\n\n$$ \n\\sigma \\approx k \\times \\text{MAD},\n$$\ndove:\n\n- $\\sigma$ è la deviazione standard,\n- MAD è la Mediana della Deviazione Assoluta,\n- $k$ è una costante che, per una distribuzione normale, è tipicamente presa come circa 1.4826.\n\nQuesta costante deriva dalla proprietà della distribuzione normale, in cui circa il 50% dei valori si trova entro 0.6745 deviazioni standard dalla media.\n\nLa formula completa per convertire la MAD in una stima della deviazione standard in una distribuzione normale è:\n\n$$ \n\\sigma \\approx 1.4826 \\times \\text{MAD} .\n$$\nQuesta relazione è utile per stimare la deviazione standard in modo più robusto, specialmente quando si sospetta la presenza di outlier o si ha a che fare con campioni piccoli. Di conseguenza, molti software restituiscono il valore MAD moltiplicato per questa costante per fornire un'indicazione più intuitiva della variabilità dei dati. Tuttavia, è importante notare che questa relazione si mantiene accurata solo per le distribuzioni che sono effettivamente normali. In presenza di distribuzioni fortemente asimmetriche o con elevati outlier, la deviazione standard e la MAD possono fornire indicazioni molto diverse sulla variabilità dei dati.\n\n::: {.callout-note collapse=\"true\" title=\"Dimostrazione numerica\"}\n\nPer verificare questo principio, usiamo un campione di dati simulati dalla distribuzione del QI:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqi <- rnorm(200, 100, 15)\n1.4826 * median(abs(qi - median(qi)), na.rm = TRUE)\n#> [1] 14.1\n```\n:::\n\n\nOtteniamo un valore che è simile alla deviazione standard calcolata con:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsqrt(\n  var(qi) * (length(qi) - 1) / length(qi)\n)\n#> [1] 14.4\n```\n:::\n\n\nCiò conferma la relazione tra MAD e deviazione standard in distribuzioni gaussiane.\n\nSe invece usiamo dei dati non normali, l'approssimazione non è buona:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123) \ny <- rchisq(200, 1)\n1.4826 * median(abs(y - median(y)))\n#> [1] 0.474\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsqrt(\n  var(y) * (length(y) - 1) / length(y)\n)\n#> [1] 1.41\n```\n:::\n\n:::\n\n### Quando utilizzare deviazione standard e MAD\n\n**Deviazione standard**\nQuesta misura è ottimale quando si lavora con dati approssimativamente distribuiti in modo normale e quando si intende descrivere la dispersione dei valori attorno alla loro media aritmetica. La deviazione standard gode di proprietà matematiche utili in molti modelli statistici, ma presenta lo svantaggio di essere sensibile alla presenza di valori anomali.\n\n**Deviazione mediana assoluta (MAD)**\nQuesta misura risulta particolarmente adatta quando i dati presentano distribuzioni non normali, marcata asimmetria o quando sono presenti outlier. Il MAD è robusto poiché si basa sulla mediana, che è già di per sé una misura resistente ai valori estremi, e non sulla media. È quindi la scelta migliore quando si desidera una stima stabile della variabilità che non sia distorta da osservazioni eccezionali.\n\n### Indici di variabilità relativi\n\nA volte può essere necessario confrontare la variabilità di grandezze incommensurabili, ovvero di caratteri misurati con differenti unità di misura. In queste situazioni, le misure di variabilità descritte in precedenza diventano inadeguate poiché dipendono dall'unità di misura utilizzata. Per superare questo problema, si ricorre a specifici numeri adimensionali chiamati *indici relativi di variabilità*.\n\nIl più importante di questi indici è il *coefficiente di variazione* ($C_v$), definito come il rapporto tra la deviazione standard ($\\sigma$) e la media dei dati ($\\bar{x}$):\n\n$$\nC_v = \\frac{\\sigma}{\\bar{x}}.\n$$ {#eq-cv-def}\n\nIl coefficiente di variazione è un numero puro e permette di confrontare la variabilità di distribuzioni con unità di misura diverse.\n\nUn altro indice relativo di variabilità è la *differenza interquartile rapportata* a uno dei tre quartili (primo quartile, terzo quartile o mediana). Questo indice è definito come:\n\n$$\n\\frac{x_{0.75} - x_{0.25}}{x_{0.25}}, \\qquad \\frac{x_{0.75} - x_{0.25}}{x_{0.75}}, \\qquad \\frac{x_{0.75} - x_{0.25}}{x_{0.50}}.\n$$\n\nQuesti indici relativi di variabilità forniscono una misura adimensionale della dispersione dei dati, rendendo possibile il confronto tra grandezze con diverse unità di misura e facilitando l'analisi delle differenze di variabilità tra i dati.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLe statistiche descrittive forniscono strumenti essenziali per sintetizzare e interpretare i dati nelle scienze psicologiche e sociali. Gli indici di tendenza centrale (media, mediana e moda) individuano il valore tipico di una distribuzione e forniscono un punto di riferimento essenziale per la sintesi iniziale. Gli indici di dispersione (deviazione standard, varianza e intervallo interquartile) completano questo quadro, quantificando la variabilità dei dati rispetto al valore centrale e rivelando l'eterogeneità spesso presente nel fenomeno oggetto di studio.\n\nTuttavia, è essenziale considerare con attenzione le implicazioni teoriche e metodologiche associate all’uso di queste misure. Un nodo cruciale è rappresentato dal rischio della **fallacia ergodica**, ossia dall’erronea assunzione che le proprietà osservate a livello di gruppo possano essere trasferite automaticamente al livello del singolo individuo. In psicologia, infatti, i fenomeni di interesse sono caratterizzati da una marcata **variabilità intraindividuale e interindividuale**, che difficilmente può essere catturata in modo adeguato da indicatori puramente aggregati.\n\nDi conseguenza, le statistiche descrittive non dovrebbero essere intese come un punto di arrivo, ma piuttosto come una **fase preliminare dell’analisi**. La loro interpretazione acquista significato solo se integrata con approcci metodologici più sofisticati, quali i **modelli longitudinali** o le **analisi idiografiche**, capaci di rispettare la specificità dei singoli casi. Solo un impiego critico e consapevole di questi strumenti consente di evitare generalizzazioni spurie e di restituire una rappresentazione più accurata e sfumata dei processi psicologici e comportamentali.\n\n## Esercizi {.unnumbered .unlisted}\n\n::: {.callout-important title=\"Problemi\" collapse=\"true\"}\n\n*Parte 1: Domande Teoriche*\n\n1. *Definizione e comprensione dei concetti*\n\n   - Spiega la differenza tra media, mediana e moda.\n   - In quali situazioni la mediana fornisce una misura della tendenza centrale migliore rispetto alla media?\n   - Perché la media è sensibile ai valori estremi?\n   - Quali sono i vantaggi della deviazione mediana assoluta (MAD) rispetto alla deviazione standard?\n   \n2. *Interpretazione della variabilità*\n\n   - Spiega il concetto di varianza e la sua interpretazione.\n   - Qual è la differenza tra varianza e deviazione standard?\n   - Descrivi in quali casi l'utilizzo del coefficiente di variazione è più appropriato rispetto alla deviazione standard.\n   - Quali sono i limiti della moda come indice di tendenza centrale?\n   \n*Parte 2: Calcoli Manuali*\n\n3. *Calcolo della media, mediana e moda*\n\n   - Considera i seguenti punteggi totali della SWLS che sono stati raccolti in un campione di studenti. Calcola manualmente:\n   \n     - La media\n     - La mediana\n     - La moda\n     - Il range\n\n4. *Calcolo della varianza e della deviazione standard*\n\n   - Usando gli stessi dati dell'esercizio precedente, calcola:\n     - La varianza\n     - La deviazione standard\n     - La deviazione mediana assoluta (MAD)\n   \n*Parte 3: Esercizi con R*\n\n5. *Analisi descrittiva con R*\n\n   - Carica il dataset `swls_scores.csv` contenente i punteggi SWLS degli studenti.\n   - Calcola media, mediana e moda utilizzando R.\n   - Calcola la varianza e la deviazione standard utilizzando le funzioni appropriate in R.\n   \n   *Codice suggerito:*\n   \n   ```r\n   library(tidyverse)\n   library(rio)\n   \n   # Caricamento del dataset\n   df <- import(\"swls_scores.csv\")\n   \n   # Calcolo delle statistiche descrittive\n   mean(df$swls_total)\n   median(df$swls_total)\n   \n   # Moda (funzione personalizzata)\n   get_mode <- function(x) {\n     tbl <- table(x)\n     as.numeric(names(tbl)[which.max(tbl)])\n   }\n   get_mode(df$swls_total)\n   \n   # Varianza e deviazione standard\n   var(df$swls_total)\n   sd(df$swls_total)\n   \n   # Deviazione mediana assoluta\n   mad(df$swls_total)\n   ```\n   \n6. *Visualizzazione della distribuzione dei dati*\n\n   - Crea un istogramma dei punteggi totali della SWLS.\n   - Aggiungi una linea verticale che rappresenti la media e una che rappresenti la mediana.\n   \n   *Codice suggerito:*\n   \n   ```r\n   ggplot(df, aes(x = swls_total)) +\n     geom_histogram(binwidth = 2, fill = \"blue\", alpha = 0.5, color = \"black\") +\n     geom_vline(aes(xintercept = mean(swls_total)), color = \"red\", linetype = \"dashed\", size = 1) +\n     geom_vline(aes(xintercept = median(swls_total)), color = \"green\", linetype = \"dotted\", size = 1) +\n     labs(title = \"Distribuzione dei punteggi SWLS\", x = \"Punteggio SWLS\", y = \"Frequenza\")\n   ```\n   \n*Parte 4: Domande di Comprensione*\n\n7. *Analisi concettuale*\n\n   - Perché la media aritmetica può essere considerata il \"baricentro\" della distribuzione dei dati?\n   - Se aggiungiamo un valore estremo al dataset, quale delle misure di tendenza centrale subirà il maggior impatto?\n   - In quali situazioni la varianza campionaria è preferibile rispetto alla varianza della popolazione?\n   - Qual è la relazione tra la deviazione standard e la varianza?\n   - Fornisci un'interpretazione intuitiva della deviazione standard.\n   - Discuti le differenze e le somiglianze tra la deviazione standard e MAD. Usa queste informazioni per ridescrivere in maniera intuitiva il significato di deviazione standard.\n:::\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\nPoniamo che i valori SWLS siano [ 18, 22, 26, 19, 24, 30, 26, 22, 18, 28, 21 ].\n\n1. *Media:*\n   $$ \\bar{x} = \\frac{18 + 22 + 26 + 19 + 24 + 30 + 26 + 22 + 18 + 28 + 21}{11} = 23.36 $$\n   \n2. *Mediana:*\n   Ordinando i dati: [ 18, 18, 19, 21, 22, 22, 24, 26, 26, 28, 30 ]\n   La mediana è il valore centrale: $22$\n   \n3. *Moda:*\n   Il valore più frequente è *22* (appare due volte).\n   \n4. *Varianza:*\n   $$ s^2 = \\frac{\\sum (x_i - \\bar{x})^2}{n-1} = 13.96 $$\n   \n5. *Deviazione Standard:*\n   $$ s = \\sqrt{13.96} = 3.73 $$\n   \n6. *MAD:*\n   $$ \\text{MAD} = \\text{mediana}(|X_i - \\text{mediana}(X)|) = 4 $$\n   \n*Soluzioni con R*\n\nI risultati eseguendo il codice R:\n\n   - *Media:* 23.36\n   - *Mediana:* 22\n   - *Moda:* 22\n   - *Varianza:* 13.96\n   - *Deviazione standard:* 3.73\n   - *MAD:* 4\n\n*Soluzioni alle Domande di Comprensione*\n\n1. La media è il baricentro poiché minimizza la somma degli scarti quadrati.\n2. La media è più influenzata dai valori estremi rispetto alla mediana.\n3. La varianza campionaria corregge la sottostima della varianza popolazionale.\n4. La deviazione standard è la radice quadrata della varianza, consentendo un'interpretazione del risultato sulla scala dei dati grezzi.\n5. La deviazione standard è simile, ma non identica, al valore medio degli scarti assoluti tra ciascun valore della distribuzione e la media. In altre parole, rappresenta la \"distanza tipica\" media tra le osservazioni e il valore medio della distribuzione.\n6. La deviazione standard e il MAD (Median Absolute Deviation, o scarto medio assoluto) sono entrambi misure di variabilità che descrivono quanto i valori in un insieme di dati si discostino dal centro della distribuzione. Tuttavia, presentano alcune importanti differenze e somiglianze.\n\n  *Somiglianze*\n  \n  - Entrambe le misure quantificano la dispersione dei dati attorno a un punto centrale.\n  - Sia la deviazione standard che il MAD utilizzano lo scarto (la differenza tra ciascun valore e un punto centrale) per calcolare la variabilità.\n  \n  *Differenze*\n  \n  - *Punto centrale usato:* La deviazione standard si basa sulla media aritmetica, mentre il MAD si basa sulla mediana.\n  - *Trattamento degli scarti:* Nella deviazione standard, gli scarti vengono elevati al quadrato prima di essere mediati, quindi la radice quadrata viene applicata al risultato finale. Questo processo penalizza maggiormente gli scarti più grandi, rendendo la deviazione standard più sensibile agli outlier. Il MAD, invece, considera semplicemente il valore assoluto degli scarti, rendendolo meno influenzato dagli estremi.\n  - *Sensibilità agli outlier:* Poiché la deviazione standard dipende dai quadrati degli scarti, è più sensibile alle osservazioni estreme (outlier). Il MAD, essendo basato sulla mediana, è una misura più robusta e resiste meglio alla presenza di valori anomali.\n  \n  *Ridescrizione Intuitiva della Deviazione Standard*\n  \n  - La deviazione standard può essere vista come una misura della \"dispersione tipica\" dei dati attorno alla media, ma con un'enfasi particolare sugli scarti più grandi. Immagina di prendere ogni valore del dataset, calcolarne la distanza dalla media, amplificare queste distanze attraverso il quadrato, poi trovare una sorta di \"distanza media\" ponderata. Questo processo dà maggiore peso agli scarti più grandi, fornendo così una visione della variabilità che tiene conto sia delle fluttuazioni ordinarie sia di eventuali valori estremi. In sintesi, mentre il MAD offre una visione più resistente e diretta della variabilità centrata sulla mediana, la deviazione standard fornisce una misura più dettagliata e sensibile alla forma complessiva della distribuzione, inclusi i suoi possibili outliers.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.0 (2026-04-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] grid      stats     graphics  grDevices utils     datasets  methods  \n#> [8] base     \n#> \n#> other attached packages:\n#>  [1] vcd_1.4-13            viridis_0.6.5         viridisLite_0.4.3    \n#>  [4] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [7] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#> [10] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [13] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [16] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [19] brms_2.23.0           Rcpp_1.1.1-1.1        sessioninfo_1.2.4    \n#> [22] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [25] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [28] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3.1       inline_0.3.21         rlang_1.2.0          \n#>  [4] magrittr_2.0.5        snakecase_0.11.1      otel_0.2.0           \n#>  [7] compiler_4.6.0        vctrs_0.7.3           stringr_1.6.0        \n#> [10] pkgconfig_2.0.3       arrayhelpers_1.1-1    fastmap_1.2.0        \n#> [13] backports_1.5.1       labeling_0.4.3        rmarkdown_2.31       \n#> [16] purrr_1.2.2           xfun_0.59             cachem_1.1.0         \n#> [19] jsonlite_2.0.0        broom_1.0.13          parallel_4.6.0       \n#> [22] R6_2.6.1              stringi_1.8.7         RColorBrewer_1.1-3   \n#> [25] lmtest_0.9-40         lubridate_1.9.5       estimability_2.0.0   \n#> [28] knitr_1.51            zoo_1.8-15            R.utils_2.13.0       \n#> [31] pacman_0.5.1          Matrix_1.7-5          timechange_0.4.0     \n#> [34] tidyselect_1.2.1      abind_1.4-8           yaml_2.3.12          \n#> [37] codetools_0.2-20      curl_7.1.0            pkgbuild_1.4.8       \n#> [40] lattice_0.22-9        bridgesampling_1.2-1  S7_0.2.2             \n#> [43] coda_0.19-4.1         evaluate_1.0.5        RcppParallel_5.1.11-2\n#> [46] pillar_1.11.1         tensorA_0.36.2.1      checkmate_2.3.4      \n#> [49] stats4_4.6.0          distributional_0.8.1  generics_0.1.4       \n#> [52] rprojroot_2.1.1       rstantools_2.6.0      scales_1.4.0         \n#> [55] xtable_1.8-8          glue_1.8.1            emmeans_2.0.3        \n#> [58] tools_4.6.0           data.table_1.18.4     mvtnorm_1.4-1        \n#> [61] QuickJSR_1.10.0       colorspace_2.1-2      nlme_3.1-169         \n#> [64] cli_3.6.6             textshaping_1.0.5     svUnit_1.0.8         \n#> [67] Brobdingnag_1.2-9     V8_8.2.0              gtable_0.3.6         \n#> [70] R.methodsS3_1.8.2     digest_0.6.39         htmlwidgets_1.6.4    \n#> [73] farver_2.1.2          R.oo_1.27.1           memoise_2.0.1        \n#> [76] htmltools_0.5.9       lifecycle_1.0.5       MASS_7.3-65\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n\n",
    "supporting": [
      "06_loc_scale_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}