{
  "hash": "4e5099d8af92699037c01096264025d7",
  "result": {
    "engine": "knitr",
    "markdown": "# Introduzione alla distribuzione normale {#sec-eda-intro-gauss}\n\n::: {.callout-note appearance=\"minimal\"}\nLa distribuzione normale (o gaussiana) rappresenta il ponte concettuale tra la statistica descrittiva e quella inferenziale. In questo capitolo esploreremo perché questa distribuzione è così centrale in psicologia, come riconoscerla nei dati, e perché media e deviazione standard diventano particolarmente utili quando i dati seguono approssimativamente questa forma. Questo capitolo fornisce le basi intuitive necessarie per comprendere i test statistici e gli intervalli di confidenza che studieremo nei capitoli successivi. Gli aspetti formali della distribuzione normale verranno approfonditi nel companion sulla teoria della probabilità.\n:::\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- **Perché la normale è importante in psicologia**: Collegamenti con test, questionari e fenomeni naturali.\n- **Proprietà visive fondamentali**: La regola empirica 68-95-99.7 e il suo significato pratico.\n- **Z-scores e standardizzazione**: Come confrontare valori su scale diverse.\n- **Verifica della normalità**: QQ-plots come strumento diagnostico.\n- **Ponte verso l'inferenza**: Come la normale prepara ai concetti inferenziali.\n\n::: {.callout-tip collapse=\"true\"}\n## Prerequisiti\n\n- Leggere il capitolo [Exploring numerical data](https://openintro-ims.netlify.app/explore-numerical) di [Introduction to Modern Statistics (2e)](https://openintro-ims.netlify.app) di Mine Çetinkaya-Rundel e Johanna Hardin.\n- Leggere il capitolo *Distributions* di *Introduction to Data Science* [@irizarry2024introduction].\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Load packages\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(ggbeeswarm, dslabs, gridExtra, patchwork) \n```\n:::\n\n:::\n\n## Perché la distribuzione normale è fondamentale in psicologia {#sec-why-normal}\n\nPrima di approfondire le proprietà matematiche della distribuzione normale, è essenziale comprenderne il ruolo centrale nella ricerca psicologica e nei test standardizzati.\n\n### La distribuzione normale nella psicometria\n\nLa maggior parte dei test psicologici standardizzati è progettata per produrre punteggi che, nella popolazione di riferimento, seguano approssimativamente una distribuzione normale. Esempi includono:\n\n- **Test di intelligenza** (QI): strutturati con una media di 100 e una deviazione standard di 15.\n- **Test di personalità**: come le dimensioni del Big Five, che spesso mostrano distribuzioni approssimativamente normali.\n- **Questionari clinici**: ad esempio il BDI (Beck Depression Inventory) o lo STAI (State-Trait Anxiety Inventory).\n- **Batterie neuropsicologiche**: per la valutazione di memoria, attenzione e funzioni esecutive.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simuliamo la distribuzione del QI\nqi_data <- data.frame(\n  QI = seq(55, 145, length.out = 1000)\n) |>\n  mutate(densita = dnorm(QI, mean = 100, sd = 15))\n\nggplot(qi_data, aes(x = QI, y = densita)) +\n  geom_line(linewidth = 1.2, color = \"darkblue\") +\n  geom_area(fill = \"lightblue\", alpha = 0.5) +\n  geom_vline(xintercept = 100, linetype = \"dashed\", color = \"red\") +\n  annotate(\"text\", x = 100, y = 0.02, label = \"Media = 100\", \n           vjust = -0.5, color = \"red\") +\n  labs(title = \"Distribuzione dei punteggi di QI\",\n       subtitle = \"Media = 100, Deviazione Standard = 15\",\n       x = \"Punteggio QI\", \n       y = \"Densità\") \n```\n\n::: {.cell-output-display}\n![Distribuzione teorica dei punteggi di QI nella popolazione](07_introduction_normal_distribution_files/figure-html/fig-qi-distribution-1.png){#fig-qi-distribution fig-align='center' width=85%}\n:::\n:::\n\n\n### Fenomeni naturali e biologici\n\nMolte variabili biologiche e comportamentali tendono a seguire distribuzioni approssimativamente normali:\n\n- **Misure antropometriche**: altezza, peso, circonferenza cranica.\n- **Tempi di reazione**: in compiti cognitivi semplici.\n- **Errori di misurazione**: negli esperimenti di laboratorio.\n- **Variabilità interindividuale**: in numerosi processi psicologici di base.\n\nQuesta tendenza non è accidentale: quando una variabile è influenzata da molteplici fattori indipendenti (genetici, ambientali, casuali), ciascuno con un piccolo effetto, la distribuzione risultante tende a convergere verso la forma normale. Questo principio, formalizzato nel *Teorema del Limite Centrale*, costituisce il fondamento di molte tecniche statistiche inferenziali.\n\n### La distribuzione normale come modello fondamentale nella modellazione bayesiana\n\nAnche nell'inferenza bayesiana, la distribuzione normale gioca un ruolo centrale, sebbene con prospettive e applicazioni differenti rispetto all'approccio frequentista:\n\n- **Priors e likelihood**: la normale viene spesso utilizzata come *prior* coniugato per parametri di interesse, e come *likelihood* per modellare dati continui, facilitando il calcolo analitico delle posteriori.\n- **Regolarizzazione bayesiana**: i *prior* normali (come in regressione ridge bayesiana) forniscono una naturale regolarizzazione degli effetti, prevenendo il sovradattamento.\n- **Modelli gerarchici**: la normale è fondamentale per modellare la variazione tra gruppi (effetti casuali) in strutture gerarchiche.\n- **Approssimazioni della posterior**: metodi come la Variational Bayes o la Laplace approximation spesso assumono che la distribuzione a posteriori sia approssimativamente normale.\n\nComprendere le proprietà della distribuzione normale è quindi essenziale per costruire modelli bayesiani robusti, interpretare i *prior* coniugati e implementare algoritmi di inferenza efficienti. Nel contesto bayesiano, la normale non è tanto un'\"assunzione da verificare\" quanto una scelta di modellazione flessibile e matematicamente conveniente.\n\n::: {.callout-important}\n## La normale come modello, non come legge assoluta\n\nÈ cruciale ricordare che **i dati reali raramente seguono perfettamente una distribuzione normale**. La distribuzione normale rappresenta un *modello matematico* che approssima in modo utile molti fenomeni reali. L'obiettivo non è quindi trovare dati \"perfettamente normali\", ma valutare se l'approssimazione normale è sufficientemente buona per gli scopi specifici della nostra analisi.\n:::\n\n## La distribuzione normale: definizione e proprietà {#sec-normal-distribution}\n\nLa distribuzione normale, nota anche come distribuzione gaussiana o curva a campana, è una distribuzione di probabilità continua, perfettamente simmetrica e unimodale. È completamente caratterizzata da due parametri:\n\n- **$\\mu$ (mu)**: la **media**, che definisce il centro della distribuzione;\n- **$\\sigma$ (sigma)**: la **deviazione standard**, che determina la dispersione dei valori attorno alla media.\n\n### Rappresentazione visiva\n\nEcco come appare la distribuzione normale con diversi valori di $\\mu$ e $\\sigma$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Diverse medie, stessa sd\np1 <- tibble(x = seq(-5, 15, 0.1)) |>\n  mutate(\n    mu0 = dnorm(x, 0, 2),\n    mu5 = dnorm(x, 5, 2),\n    mu8 = dnorm(x, 8, 2)\n  ) |>\n  pivot_longer(-x, names_to = \"distribuzione\", values_to = \"densita\") |>\n  mutate(distribuzione = factor(distribuzione, \n                                 levels = c(\"mu0\", \"mu5\", \"mu8\"),\n                                 labels = c(\"μ=0, σ=2\", \"μ=5, σ=2\", \"μ=8, σ=2\"))) |>\n  ggplot(aes(x = x, y = densita, color = distribuzione)) +\n  geom_line(linewidth = 1) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +\n  labs(title = \"Effetto della media (μ)\",\n       subtitle = \"Diverse medie, stessa deviazione standard\",\n       x = \"x\", y = \"Densità\",\n       color = NULL) +\n  theme(legend.position = \"bottom\")\n\n# Stessa media, diverse sd\np2 <- tibble(x = seq(-10, 10, 0.1)) |>\n  mutate(\n    sd1 = dnorm(x, 0, 1),\n    sd2 = dnorm(x, 0, 2),\n    sd4 = dnorm(x, 0, 4)\n  ) |>\n  pivot_longer(-x, names_to = \"distribuzione\", values_to = \"densita\") |>\n  mutate(distribuzione = factor(distribuzione,\n                                 levels = c(\"sd1\", \"sd2\", \"sd4\"),\n                                 labels = c(\"μ=0, σ=1\", \"μ=0, σ=2\", \"μ=0, σ=4\"))) |>\n  ggplot(aes(x = x, y = densita, color = distribuzione)) +\n  geom_line(linewidth = 1) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +\n  labs(title = \"Effetto della deviazione standard (σ)\",\n       subtitle = \"Stessa media, diverse deviazioni standard\",\n       x = \"x\", y = \"Densità\",\n       color = NULL) +\n  theme(legend.position = \"bottom\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1\n```\n\n::: {.cell-output-display}\n![](07_introduction_normal_distribution_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np2\n```\n\n::: {.cell-output-display}\n![Effetto dei parametri μ e σ sulla forma della distribuzione normale](07_introduction_normal_distribution_files/figure-html/fig-normal-params-1-1.png){#fig-normal-params-1 fig-align='center' width=85%}\n:::\n:::\n\n\nCome si può osservare:\n\n- **la media $\\mu$** sposta la curva a destra o a sinistra lungo l'asse $x$;\n- **la deviazione standard $\\sigma$** controlla quanto la curva è \"allargata\": \n  - $\\sigma$ piccolo → curva alta e stretta (dati concentrati vicino alla media)\n  - $\\sigma$ grande → curva bassa e larga (dati più dispersi).\n\n### Proprietà fondamentali\n\n1. **Simmetria**: la distribuzione è perfettamente simmetrica rispetto alla media.\n2. **Unimodale**: ha un solo picco, corrispondente alla media.\n3. **Asintoti**: le code si estendono all'infinito senza mai toccare l'asse $x$.\n4. **Media = Mediana = Moda**: in una distribuzione normale, tutti e tre coincidono.\n\n::: {.callout-note}\n## Nota matematica\n\nLa forma precisa della distribuzione normale è definita da una funzione matematica (la funzione di densità) che coinvolge $\\mu$, $\\sigma$, e alcune costanti matematiche (π, e). I dettagli di questa funzione e le sue proprietà formali saranno approfonditi nel companion sulla teoria della probabilità. Per ora, è sufficiente sapere che $\\mu$ e $\\sigma$ determinano completamente la forma della distribuzione.\n:::\n\n## La regola empirica 68-95-99.7 {#sec-empirical-rule}\n\nUna delle proprietà più utili e memorabili della distribuzione normale è la **regola empirica** (o regola 68-95-99.7), che descrive la concentrazione dei dati attorno alla media in termini di deviazioni standard.\n\n### La regola in numeri\n\nPer qualsiasi distribuzione normale, indipendentemente dai valori specifici di $\\mu$ e $\\sigma$:\n\n- circa **68%** dei valori si trova entro **1 deviazione standard** dalla media: $[\\mu - \\sigma, \\mu + \\sigma]$;\n- circa **95%** dei valori si trova entro **2 deviazioni standard** dalla media: $[\\mu - 2\\sigma, \\mu + 2\\sigma]$;\n- circa **99.7%** dei valori si trova entro **3 deviazioni standard** dalla media: $[\\mu - 3\\sigma, \\mu + 3\\sigma]$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creiamo una distribuzione normale standard\nx <- seq(-4, 4, length.out = 1000)\ny <- dnorm(x)\ndf <- data.frame(x = x, y = y)\n\np <- ggplot(df, aes(x = x, y = y)) +\n  geom_line(linewidth = 1.2) +\n  labs(x = \"Deviazioni standard dalla media\",\n       y = \"Densità\",\n       title = \"La regola empirica 68-95-99.7\",\n       subtitle = \"Percentuale di dati entro 1, 2 e 3 deviazioni standard\") +\n  # Aree\n  geom_area(data = subset(df, x >= -3 & x <= 3), fill = \"lightblue\", alpha = 0.3) +\n  geom_area(data = subset(df, x >= -2 & x <= 2), fill = \"lightblue\", alpha = 0.3) +\n  geom_area(data = subset(df, x >= -1 & x <= 1), fill = \"lightblue\", alpha = 0.4) +\n  # Linee verticali\n  geom_vline(xintercept = c(-3, -2, -1, 0, 1, 2, 3),\n             linetype = \"dashed\", alpha = 0.5) +\n  # Annotazioni (spostate in x per non sovrapporsi)\n  annotate(\"text\", x = 0,  y = 0.15, label = \"68%\",\n           size = 5, fontface = \"bold\", color = \"darkblue\") +\n  annotate(\"text\", x = -1.6, y = 0.06, label = \"95%\",\n           size = 5, fontface = \"bold\", color = \"darkblue\") +\n  annotate(\"text\", x = 2.2, y = 0.02, label = \"99.7%\",\n           size = 5, fontface = \"bold\", color = \"darkblue\") +\n  scale_x_continuous(breaks = -3:3,\n                     labels = c(\"-3σ\", \"-2σ\", \"-1σ\", \"μ\", \"+1σ\", \"+2σ\", \"+3σ\"))\n\np\n```\n\n::: {.cell-output-display}\n![La regola empirica 68-95-99.7 per la distribuzione normale](07_introduction_normal_distribution_files/figure-html/fig-empirical-rule-1.png){#fig-empirical-rule fig-align='center' width=85%}\n:::\n:::\n\n\n### Applicazione pratica: Test del QI\n\nRiprendiamo l'esempio dei punteggi di QI (media = 100, deviazione standard = 15). Applicando la regola empirica:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu_qi <- 100\nsd_qi <- 15\n\n# Calcoliamo gli intervalli\nintervalli <- data.frame(\n  Intervallo = c(\"μ ± 1σ\", \"μ ± 2σ\", \"μ ± 3σ\"),\n  Limiti = c(\n    paste(mu_qi - sd_qi, \"-\", mu_qi + sd_qi),\n    paste(mu_qi - 2*sd_qi, \"-\", mu_qi + 2*sd_qi),\n    paste(mu_qi - 3*sd_qi, \"-\", mu_qi + 3*sd_qi)\n  ),\n  Percentuale = c(\"68%\", \"95%\", \"99.7%\"),\n  Interpretazione = c(\n    \"La maggior parte delle persone\",\n    \"Quasi tutte le persone\",\n    \"Praticamente tutta la popolazione\"\n  )\n)\n\nknitr::kable(intervalli, \n             caption = \"Applicazione della regola empirica ai punteggi di QI\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Applicazione della regola empirica ai punteggi di QI\n\n|Intervallo |Limiti   |Percentuale |Interpretazione                   |\n|:----------|:--------|:-----------|:---------------------------------|\n|μ ± 1σ     |85 - 115 |68%         |La maggior parte delle persone    |\n|μ ± 2σ     |70 - 130 |95%         |Quasi tutte le persone            |\n|μ ± 3σ     |55 - 145 |99.7%       |Praticamente tutta la popolazione |\n\n\n:::\n:::\n\n\nQuesto significa che:\n\n- circa il 68% della popolazione ha un QI tra 85 e 115;\n- circa il 95% della popolazione ha un QI tra 70 e 130;\n- solo circa il 2.5% ha un QI superiore a 130 (superdotati);\n- solo circa il 2.5% ha un QI inferiore a 70 (difficoltà cognitive).\n\n### Verifica empirica con dati reali\n\nVediamo se la regola empirica si applica effettivamente a un dataset reale. Useremo ancora le altezze maschili dal dataset `heights`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estraiamo le altezze maschili\nindex <- dslabs::heights$sex == \"Male\"\nx <- dslabs::heights$height[index]\n\n# Calcoliamo media e deviazione standard\nm <- mean(x)\ns <- sd(x)\n\ncat(\"Media:\", round(m, 2), \"cm\\n\")\n#> Media: 69.3 cm\ncat(\"Deviazione standard:\", round(s, 2), \"cm\\n\\n\")\n#> Deviazione standard: 3.61 cm\n\n# Verifichiamo la regola empirica\nprop_1sd <- mean(abs(x - m) <= 1*s)\nprop_2sd <- mean(abs(x - m) <= 2*s)\nprop_3sd <- mean(abs(x - m) <= 3*s)\n\nrisultati_empirici <- data.frame(\n  Intervallo = c(\"μ ± 1σ\", \"μ ± 2σ\", \"μ ± 3σ\"),\n  Teorico = c(\"68%\", \"95%\", \"99.7%\"),\n  Osservato = paste0(round(c(prop_1sd, prop_2sd, prop_3sd) * 100, 1), \"%\")\n)\n\nknitr::kable(risultati_empirici,\n             caption = \"Confronto tra proporzioni teoriche e osservate\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Confronto tra proporzioni teoriche e osservate\n\n|Intervallo |Teorico |Osservato |\n|:----------|:-------|:---------|\n|μ ± 1σ     |68%     |76%       |\n|μ ± 2σ     |95%     |95%       |\n|μ ± 3σ     |99.7%   |99.1%     |\n\n\n:::\n:::\n\n\nCome si può vedere, le proporzioni osservate sono molto vicine a quelle teoriche, confermando che l'altezza maschile segue approssimativamente una distribuzione normale.\n\n::: {.callout-tip}\n## Implicazione pratica\n\nLa regola empirica ci permette di interpretare rapidamente la deviazione standard: essa rappresenta approssimativamente la distanza dalla media entro cui si trova circa il 68% dei dati. Questo rende la deviazione standard molto più interpretabile di quanto possa sembrare dalla sua formula!\n:::\n\n## Un esempio pratico completo: altezza maschile {#sec-height-example}\n\nMettiamo insieme tutti i concetti visti finora con un esempio pratico. Vogliamo descrivere la distribuzione delle altezze maschili usando la distribuzione normale.\n\n### Stima dei parametri\n\nEstraiamo i dati e calcoliamo media e deviazione standard:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nindex <- dslabs::heights$sex == \"Male\"\nx <- dslabs::heights$height[index]\n\nm <- mean(x)\ns <- sd(x)\n\ncat(\"Media:\", round(m, 2), \"cm\\n\")\n#> Media: 69.3 cm\ncat(\"Deviazione standard:\", round(s, 2), \"cm\\n\")\n#> Deviazione standard: 3.61 cm\n```\n:::\n\n\n::: {.callout-warning}\n**Nota tecnica**: La funzione `sd(x)` effettua una divisione per $n - 1$ invece che per $n$ (dove $n$ è il numero di osservazioni). Questa correzione, chiamata *correzione di Bessel*, serve per ottenere una stima non distorta della deviazione standard della popolazione. Quando il numero di osservazioni è elevato, la differenza tra dividere per $n$ o per $n-1$ è trascurabile. Approfondiremo questo aspetto quando studieremo la stima dei parametri.\n:::\n\n### Confronto visivo\n\nPossiamo ora confrontare la distribuzione osservata (in blu) con la distribuzione normale teorica (in nero):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnorm_dist <- tibble(\n  x = seq(m - 4*s, m + 4*s, length.out = 100)) |> \n  mutate(density = dnorm(x, m, s))\n\ndslabs::heights |> \n  dplyr::filter(sex == \"Male\") |> \n  ggplot(aes(height)) +\n  geom_density(fill = \"lightblue\", alpha = 0.7) +\n  geom_line(aes(x, density), linewidth = 1.5, \n            data = norm_dist, color = \"black\") +\n  labs(title = \"Distribuzione delle altezze maschili\",\n       subtitle = \"Densità osservata (blu) vs. normale teorica (nero)\",\n       x = \"Altezza (cm)\", \n       y = \"Densità\") \n```\n\n::: {.cell-output-display}\n![Confronto tra distribuzione osservata delle altezze maschili e distribuzione normale teorica](07_introduction_normal_distribution_files/figure-html/fig-altezza-normale-1.png){#fig-altezza-normale fig-align='center' width=85%}\n:::\n:::\n\n\nLa curva normale fornisce una buona approssimazione. Questo significa che possiamo descrivere efficacemente la distribuzione usando solo due numeri: media (69.3 cm) e deviazione standard (3.6 cm).\n\n## Z-scores: standardizzazione e confronti {#sec-z-scores}\n\nQuando si lavora con variabili misurate su scale differenti (ad esempio, altezza in centimetri e peso in chilogrammi, oppure punteggi di test diversi), confrontarle direttamente risulta problematico. I **punteggi standardizzati** (o *z-scores*) offrono una soluzione a questo problema.\n\n### Definizione e calcolo\n\nUno z-score rappresenta il numero di deviazioni standard di cui un dato valore si discosta dalla media della distribuzione:\n\n$$\nz = \\frac{x - \\mu}{\\sigma}\n$$\ndove:\n\n- $x$ è il valore osservato;\n- $\\mu$ è la media della distribuzione;\n- $\\sigma$ è la deviazione standard.\n\nIn R, gli z-scores possono essere calcolati facilmente utilizzando la funzione `scale()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Z-scores delle altezze maschili\nz <- scale(x) |> as.numeric()\n\ncat(\"Primi 10 z-scores:\\n\")\n#> Primi 10 z-scores:\nhead(z, 10) |> round(2)\n#>  [1]  1.57  0.19 -0.36  1.30 -2.30 -0.64  0.74  0.74 -0.09 -0.36\n\n# Verifichiamo le proprietà\ncat(\"\\nMedia degli z-scores:\", round(mean(z), 10), \"\\n\")\n#> \n#> Media degli z-scores: 0\ncat(\"Deviazione standard degli z-scores:\", round(sd(z), 10), \"\\n\")\n#> Deviazione standard degli z-scores: 1\n```\n:::\n\n\n**Proprietà fondamentali degli z-scores:**\n\n1. la media degli z-scores è sempre 0;\n2. la deviazione standard degli z-scores è sempre 1;\n3. gli z-scores preservano la forma della distribuzione originale.\n\n### Interpretazione pratica\n\n- **z = 0**: il valore coincide con la media.\n- **z = 1**: il valore è 1 deviazione standard *sopra* la media.\n- **z = -1**: il valore è 1 deviazione standard *sotto* la media.\n- **z = 2**: il valore è 2 deviazioni standard sopra la media (nel 2.5% superiore se distribuzione normale).\n- **z = -2**: il valore è 2 deviazioni standard sotto la media (nel 2.5% inferiore se distribuzione normale).\n\n### Esempio: confronto tra test diversi\n\nSupponiamo che uno studente abbia ottenuto:\n\n- QI = 115 (media popolazione = 100, sd = 15);\n- punteggio in un test di memoria = 65 (media test = 50, sd = 10).\n\nIn quale test ha performato meglio relativamente alla popolazione?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcoliamo gli z-scores\nz_qi <- (115 - 100) / 15\nz_memoria <- (65 - 50) / 10\n\ncat(\"Z-score QI:\", round(z_qi, 2), \"\\n\")\n#> Z-score QI: 1\ncat(\"Z-score Memoria:\", round(z_memoria, 2), \"\\n\")\n#> Z-score Memoria: 1.5\n\nif (z_memoria > z_qi) {\n  cat(\"\\nLo studente ha performato relativamente meglio nel test di memoria\\n\")\n} else {\n  cat(\"\\nLo studente ha performato relativamente meglio nel test di QI\\n\")\n}\n#> \n#> Lo studente ha performato relativamente meglio nel test di memoria\n```\n:::\n\n\nAnche se i punteggi grezzi (115 vs 65) non sono direttamente confrontabili, gli z-scores rivelano che la performance relativa è stata migliore nel test di memoria.\n\n### La distribuzione normale standard\n\nQuando calcoliamo gli z-scores di una distribuzione normale con media $\\mu$ e deviazione standard $\\sigma$, otteniamo una **distribuzione normale standard** con media 0 e deviazione standard 1. Questa è indicata come $N(0, 1)$ o semplicemente $Z$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Dati originali e standardizzati\nplot_data <- data.frame(\n  originale = x,\n  standardizzato = z\n)\n\np1 <- ggplot(plot_data, aes(x = originale)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30,\n                 fill = \"lightblue\", alpha = 0.7) +\n  stat_function(fun = dnorm, args = list(mean = m, sd = s),\n                linewidth = 1, color = \"black\") +\n  labs(title = \"Distribuzione originale\",\n       subtitle = paste0(\"μ = \", round(m, 1), \", σ = \", round(s, 1)),\n       x = \"Altezza (cm)\", y = \"Densità\") +\n  theme(plot.margin = margin(t = 12, r = 5, b = 5, l = 5))\n\np2 <- ggplot(plot_data, aes(x = standardizzato)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30,\n                 fill = \"lightgreen\", alpha = 0.7) +\n  stat_function(fun = dnorm, args = list(mean = 0, sd = 1),\n                linewidth = 1, color = \"black\") +\n  labs(title = \"Dopo standardizzazione\",\n       subtitle = \"μ = 0, σ = 1\",\n       x = \"Z-score\", y = \"Densità\") +\n  theme(plot.margin = margin(t = 12, r = 5, b = 5, l = 5))\n\ngrid.arrange(p1, p2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Standardizzazione: da distribuzione normale a normale standard](07_introduction_normal_distribution_files/figure-html/fig-standardization-1.png){#fig-standardization fig-align='center' width=85%}\n:::\n:::\n\n\n::: {.callout-important}\n## Collegamento con l'inferenza\n\nGli z-scores sono fondamentali per l'inferenza statistica:\n\n- i test z utilizzano la distribuzione normale standard per calcolare probabilità;\n- i valori-$p$ sono spesso calcolati convertendo statistiche test in z-scores;\n- gli intervalli di confidenza si basano sulla distribuzione degli z-scores.\n\nComprendere gli z-scores ora faciliterà la comprensione dei concetti inferenziali successivi.\n:::\n\n## Verificare la normalità: QQ-plots {#sec-qq-plots}\n\nUn metodo sistematico per valutare se i dati seguono approssimativamente una distribuzione normale è il **QQ-plot** (*Quantile-Quantile plot*), che confronta i quantili empirici dei dati con i quantili teorici di una distribuzione normale di riferimento.\n\n### Principio di funzionamento del QQ-plot\n\nIl QQ-plot si costruisce seguendo questi passaggi:\n\n1. si ordinano i dati in senso crescente;\n2. per ogni osservazione, si calcola la sua posizione percentile empirica;\n3. si determinano i corrispondenti quantili teorici di una distribuzione normale standard;\n4. si rappresentano in un grafico i punti (quantile teorico, quantile osservato).\n\n**Se i dati seguono una distribuzione normale**, i punti si disporranno approssimativamente lungo una retta diagonale.\n\n### Creazione di un QQ-plot in R\n\nCon `ggplot2`, un QQ-plot può essere generato nel modo seguente:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndslabs::heights |> \n  dplyr::filter(sex == \"Male\") |> \n  ggplot(aes(sample = height)) +\n  geom_qq() +\n  geom_qq_line(color = \"red\", linewidth = 1) +\n  labs(title = \"QQ-plot: altezze maschili\",\n       x = \"Quantili teorici (normale)\",\n       y = \"Quantili osservati (dati)\") \n```\n\n::: {.cell-output-display}\n![QQ-plot per le altezze maschili](07_introduction_normal_distribution_files/figure-html/fig-qqplot-altezze-1.png){#fig-qqplot-altezze fig-align='center' width=85%}\n:::\n:::\n\n\nIn questo caso, i punti si allineano bene lungo la linea rossa, confermando che la distribuzione delle altezze maschili è approssimativamente normale.\n\n### Interpretare deviazioni dalla normalità\n\nIl QQ-plot rivela diversi tipi di non-normalità:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Generiamo diverse distribuzioni\nn <- 500\ndati_normale <- rnorm(n, 0, 1)\ndati_asim_dx <- exp(rnorm(n, 0, 0.5))  # Asimmetria positiva\ndati_asim_sx <- -exp(rnorm(n, 0, 0.5))  # Asimmetria negativa\ndati_code_pesanti <- rt(n, df = 3)  # Code pesanti (t-student)\n\n# Creiamo i QQ-plots\np1 <- ggplot(data.frame(x = dati_normale), aes(sample = x)) +\n  geom_qq() + geom_qq_line(color = \"red\") +\n  labs(title = \"Distribuzione normale\",\n       subtitle = \"Punti allineati = normalità\") \n\np2 <- ggplot(data.frame(x = dati_asim_dx), aes(sample = x)) +\n  geom_qq() + geom_qq_line(color = \"red\") +\n  labs(title = \"Asimmetria positiva\",\n       subtitle = \"Curva verso l'alto a destra\") \n\np3 <- ggplot(data.frame(x = dati_asim_sx), aes(sample = x)) +\n  geom_qq() + geom_qq_line(color = \"red\") +\n  labs(title = \"Asimmetria negativa\",\n       subtitle = \"Curva verso il basso a sinistra\") \n\np4 <- ggplot(data.frame(x = dati_code_pesanti), aes(sample = x)) +\n  geom_qq() + geom_qq_line(color = \"red\") +\n  labs(title = \"Code pesanti\",\n       subtitle = \"Punti si allontanano agli estremi\") \n\ngrid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)\n```\n\n::: {.cell-output-display}\n![Patterns comuni nei QQ-plots e la loro interpretazione](07_introduction_normal_distribution_files/figure-html/fig-qqplot-patterns-1.png){#fig-qqplot-patterns fig-align='center' width=85%}\n:::\n:::\n\n\n**Come interpretare i pattern:**\n\n- **Punti sulla linea**: distribuzione normale ✓\n- **Curva a S**: asimmetria (skewness)\n- **Punti che si allontanano agli estremi**: code pesanti (più outlier del previsto)\n- **Punti che si avvicinano agli estremi**: code leggere (meno variabilità del previsto)\n\n### Test formali di normalità\n\nOltre ai QQ-plots, esistono test statistici formali per verificare la normalità. Il più comune è il **test di Shapiro-Wilk**:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Test di Shapiro-Wilk\nshapiro_test <- shapiro.test(x)\ncat(\"Test di Shapiro-Wilk\\n\")\n#> Test di Shapiro-Wilk\ncat(\"Statistica W:\", round(shapiro_test$statistic, 4), \"\\n\")\n#> Statistica W: 0.964\ncat(\"P-value:\", round(shapiro_test$p.value, 4), \"\\n\\n\")\n#> P-value: 0\n\nif (shapiro_test$p.value > 0.05) {\n  cat(\"Interpretazione: I dati non mostrano deviazioni significative dalla normalità\\n\")\n} else {\n  cat(\"Interpretazione: I dati mostrano deviazioni significative dalla normalità\\n\")\n}\n#> Interpretazione: I dati mostrano deviazioni significative dalla normalità\n```\n:::\n\n\n::: {.callout-warning}\n## Attenzione ai test di normalità\n\nI test formali di normalità (come Shapiro-Wilk) hanno due limitazioni:\n\n1. **Con campioni piccoli**: hanno poco potere, quindi anche deviazioni importanti potrebbero non essere rilevate.\n2. **Con campioni grandi**: diventano troppo sensibili, rilevando deviazioni minime che non hanno importanza pratica\n\nPer questo motivo, la valutazione visiva tramite QQ-plot è spesso più utile del test formale.\n:::\n\n## Ponte verso la modellazione bayesiana {#sec-bridge-to-inference}\n\nI concetti presentati in questo capitolo costituiscono i mattoni fondamentali per la costruzione e l’interpretazione dei modelli bayesiani che incontreremo successivamente. Riassumiamo le connessioni più rilevanti:\n\n### 1. Dalle distribuzioni ai prior coniugati\n\nAbbiamo visto come la distribuzione normale sia descritta da due parametri ($\\mu$, $\\sigma$). Nel Bayesianesimo:\n\n- questa stessa distribuzione può essere utilizzata come **prior** su parametri continui, come un coefficiente di regressione o un effetto di trattamento;\n- l’uso di *prior* coniugati (come una normale per un parametro di interesse, combinata con una normale/likelihood) semplifica il calcolo della **distribuzione a posteriori**, che a sua volta sarà normale;\n- i *posterior* rappresentano la nostra conoscenza aggiornata dopo aver osservato i dati, e i loro intervalli di credibilità (ad esempio, il 95% HDI) possono essere interpretati direttamente come la regione più plausibile del parametro.\n\n### 2. Dalla normalità ai modelli gerarchici\n\nLa normale non è solo una distribuzione per i dati (*likelihood*), ma è uno strumento flessibile per modellare la variabilità:\n\n- nei **modelli gerarchici**, possiamo imporre un *prior* normale su effetti specifici (ad esempio, gli effetti di diversi gruppi o soggetti), che sono a loro volta vincolati da un iperparametro comune;\n- questo permette di bilanciare il *pooling* delle informazioni tra gruppi e la stima di effetti individuali, una forma di regolarizzazione nativa nell'approccio bayesiano.\n\n### 3. Standardizzazione e interpretazione degli effetti\n\nGli z-scores forniscono un’intuizione chiave:\n\n- la standardizzazione facilita la specificazione di **prior informativi** (es. \"ritengo che l'effetto sia piccolo, cioè entro ±0.5 deviazioni standard\").\n- nei modelli di regressione, spesso converrà standardizzare le variabili per assegnare *prior* più interpretabili e per rendere i coefficienti confrontabili su scale comuni.\n\n### 4. Verifica dei modelli e diagnostica\n\nIl QQ-plot e la valutazione della normalità sono un primo passo verso la più ampia **diagnostica bayesiana**:\n\n- Mentre un’assunzione di normalità può essere incorporata nella *likelihood* del modello, i residui *posteriori* vanno comunque esaminati per valutare l’adeguatezza del modello.\n- La diagnostica bayesiana va oltre: useremo **posterior predictive checks** per verificare se il nostro modello, nel suo insieme (prior + likelihood), è in grado di generare dati simili a quelli osservati. In questo senso, la verifica di una distribuzione specifica (come la normale) è solo un caso particolare di una domanda più generale: il modello si adatta bene ai dati?\n\nQuesti collegamenti mostrano come i concetti di distribuzione, parametro e adeguatezza del modello, introdotti in questo capitolo, non siano solo \"descrittivi\", ma siano il punto di partenza per una modellazione esplicita e probabilisticamente coerente dei fenomeni psicologici.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIn questo capitolo abbiamo utilizzato la distribuzione normale come **lente descrittiva** e come primo esempio di **modello probabilistico**: un modo compatto per riassumere dati continui e ragionare sulla loro variabilità.\n\nAbbiamo visto che:\n\n* quando la distribuzione normale è una buona approssimazione, la **media** e la **deviazione standard** diventano parametri informativi che descrivono la posizione e la dispersione dei dati e permettono confronti immediati tra gruppi e condizioni;\n* la **standardizzazione** (z-score) non è un “trucco di calcolo”, ma un passaggio concettuale utile: porta le variabili su una scala comune, rende più interpretabili i confronti e le grandezze d'effetto e prepara alla specificazione delle scelte di modellazione (ad esempio nella regressione);\n* la **valutazione della normalità** è soprattutto una questione diagnostica: il QQ-plot aiuta a riconoscere asimmetrie, code pesanti e outlier, caratteristiche che spesso suggeriscono la necessità di trasformazioni, modelli alternativi o verosimiglianze più robuste.\n\nIl punto chiave è che la distribuzione normale non deve essere considerata una \"legge\" dei dati, ma una **scelta di modellazione**: è utile quando funziona, ma può essere sostituita quando non descrive adeguatamente ciò che osserviamo. Questa prospettiva è centrale nell'analisi esplorativa e diventerà ancora più importante quando inizieremo a costruire modelli completi e a verificarne l'adeguatezza, confrontando ciò che il modello implica con ciò che i dati mostrano\n\n::: {.callout-tip}\n\n## Cosa ci aspetta\n\nNei prossimi capitoli vedremo come:\n\n* il **Teorema del Limite Centrale** spiega perché, in molte situazioni, le *medie campionarie* presentano una distribuzione approssimativamente normale, anche quando i dati individuali non lo sono;\n* questa regolarità rende la distribuzione normale una descrizione utile del comportamento aggregato dei dati, soprattutto quando il campione è sufficientemente ampio;\n* la distribuzione normale emerge così come un **oggetto centrale della modellazione statistica**, sia nei metodi classici sia in quelli bayesiani, fungendo da approssimazione, modello o componente di modelli più generali.\n\nL’obiettivo non è giustificare automaticamente l’uso di test standard, ma comprendere **perché** e **in quali condizioni** la normalità diventa una rappresentazione informativa dei dati.\n:::\n\n\n## Esercizi {.unnumbered .unlisted}\n\n::: {.callout-caution collapse=\"true\" title=\"Esercizi\"}\n\n### Parte 1: Comprensione concettuale {.unnumbered .unlisted}\n\n**1. Perché la distribuzione normale è importante?**\n\na. Perché la distribuzione normale è così ampiamente usata in psicologia? Fornisci almeno tre motivi specifici.\n\nb. In quali situazioni reali in psicologia possiamo aspettarci che una variabile segua approssimativamente una distribuzione normale?\n\nc. Cosa significa dire che la normale è un \"modello\" e non una \"legge\"?\n\n**2. La regola empirica**\n\na. Spiega con parole tue la regola 68-95-99.7.\n\nb. Un test di ansia ha media 50 e deviazione standard 10 nella popolazione. Usando la regola empirica, determina:\n\n   - Entro quale intervallo cade circa il 68% dei punteggi?\n   - Quale percentuale della popolazione ha un punteggio superiore a 70?\n   - Un punteggio di 25 è considerato estremo? Perché?\n\nc. Perché la regola empirica rende la deviazione standard più interpretabile?\n\n**3. Z-scores e standardizzazione**\n\na. Cos'è uno z-score e come si calcola?\n\nb. Uno studente ottiene QI = 110 (media = 100, sd = 15) e un punteggio di memoria = 58 (media = 50, sd = 8). In quale test ha performato relativamente meglio? Mostra i calcoli.\n\nc. Dopo la standardizzazione, quali saranno la media e la deviazione standard? Perché questo è utile?\n\n**4. QQ-plots**\n\na. Spiega la logica di base di un QQ-plot.\n\nb. Descrivi come apparirebbe un QQ-plot per ciascuna delle seguenti situazioni:\n\n   - Dati perfettamente normali\n   - Dati con asimmetria positiva\n   - Dati con code pesanti (più outlier del previsto)\n\nc. Perché i QQ-plots sono spesso più utili dei test formali di normalità?\n\n\n### Parte 2: Applicazioni pratiche {.unnumbered .unlisted}\n\n**5. Analisi di punteggi SWLS**\n\nConsidera i seguenti punteggi SWLS (Satisfaction With Life Scale):\n\n```\n18, 22, 25, 21, 26, 19, 20, 23, 24, 17, 22, 27, 28, 21, 19\n```\n\na. Calcola media e deviazione standard manualmente (o con R).\n\nb. Usando la regola empirica, determina l'intervallo entro cui dovrebbe cadere circa il 95% dei punteggi in una popolazione normale con questi parametri.\n\nc. Calcola gli z-scores per i punteggi 17 e 28. Quale è più estremo?\n\n**6. Analisi con R**\n\nUsa il seguente codice per generare e analizzare dati:\n\n```r\nset.seed(42)\n# Genera dati approssimativamente normali\ndati_normali <- rnorm(100, mean = 50, sd = 10)\n\n# Genera dati asimmetrici\ndati_asimmetrici <- exp(rnorm(100, mean = 3, sd = 0.5))\n\n# Crea QQ-plots per entrambi\nlibrary(ggplot2)\nggplot(data.frame(x = dati_normali), aes(sample = x)) +\n  geom_qq() + geom_qq_line() + ggtitle(\"Dati normali\")\n\nggplot(data.frame(x = dati_asimmetrici), aes(sample = x)) +\n  geom_qq() + geom_qq_line() + ggtitle(\"Dati asimmetrici\")\n\n# Verifica la regola empirica per dati_normali\nmean(abs(scale(dati_normali)) <= 1)  # Dovrebbe essere ~68%\nmean(abs(scale(dati_normali)) <= 2)  # Dovrebbe essere ~95%\n\n# Test di Shapiro-Wilk\nshapiro.test(dati_normali)\nshapiro.test(dati_asimmetrici)\n```\n\na. Esegui il codice e interpreta i QQ-plots: quali dati sembrano più normali?\n\nb. Le proporzioni osservate per i `dati_normali` sono vicine ai valori teorici (68%, 95%)?\n\nc. Cosa indicano i risultati dei test di Shapiro-Wilk?\n\n**7. Confronto tra test standardizzati**\n\nUna studentessa ottiene i seguenti risultati:\n\n- Test A: punteggio = 75, con media popolazione = 60 e sd = 10\n- Test B: punteggio = 115, con media popolazione = 100 e sd = 20\n\na. Calcola gli z-scores per entrambi i test.\n\nb. In quale test la studentessa ha performato meglio relativamente agli altri?\n\nc. Se entrambi i test seguono distribuzioni normali, in quale percentile approssimativo si trova la studentessa in ciascun test? (Usa la regola empirica)\n\n\n### Parte 3: Riflessione e collegamenti {.unnumbered .unlisted}\n\n**8. Verso l'inferenza**\n\na. Spiega come la regola empirica prepara alla costruzione di intervalli di confidenza.\n\nb. Perché gli z-scores sono importanti per i test statistici che studieremo?\n\nc. Se i dati non sono perfettamente normali, possiamo comunque usare metodi statistici basati sulla normalità? Quando sì e quando no?\n\n**9. Caso applicato: sviluppo di un test**\n\nImmagina di sviluppare un nuovo questionario per misurare l'autoefficacia accademica:\n\na. Perché potrebbe essere desiderabile che i punteggi seguano approssimativamente una distribuzione normale?\n\nb. Come useresti QQ-plots durante lo sviluppo del test?\n\nc. Dopo aver raccolto dati su 500 studenti, il test di Shapiro-Wilk risulta significativo (p < 0.001). Cosa fai? Perché?\n\n:::\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\n\n### Soluzioni Parte 1 {.unnumbered .unlisted}\n\n**1b.** Situazioni in cui aspettarci normalità in psicologia:\n\n- Punteggi di test standardizzati (QI, personalità)\n- Misure fisiche (altezza, tempo di reazione)\n- Errori di misurazione in esperimenti\n- Variabili influenzate da molti fattori indipendenti\n\n**2b.** Per media=50, sd=10:\n\n- 68% cade in 40-60\n- Solo ~2.5% sopra 70 (oltre 2 sd)\n- Un punteggio di 25 è 2.5 sd sotto la media, molto estremo (< 0.5% della popolazione)\n\n**3b.** \n\n- Z-score QI: (110-100)/15 = 0.67\n- Z-score memoria: (58-50)/8 = 1.00\n- Performance migliore in memoria (z più alto)\n\n**3c.** Dopo standardizzazione: media=0, sd=1 sempre.\n\n### Soluzioni Parte 2 {.unnumbered .unlisted}\n\n**5.** Per i dati SWLS forniti:\n```r\nswls <- c(18, 22, 25, 21, 26, 19, 20, 23, 24, 17, 22, 27, 28, 21, 19)\nmean(swls)  # 22.13\nsd(swls)    # 3.42\n\n# 95% dovrebbe cadere in: 22.13 ± 2*3.42 = [15.29, 28.97]\n\n# Z-scores\n(17 - 22.13)/3.42  # -1.50\n(28 - 22.13)/3.42  # 1.72\n# Il punteggio 28 è leggermente più estremo (in valore assoluto)\n```\n\n**7.**\n```r\n# Test A\nz_a <- (75 - 60) / 10  # 1.5\n\n# Test B  \nz_b <- (115 - 100) / 20  # 0.75\n\n# La studentessa ha performato meglio nel Test A (z più alto)\n# Nel Test A è circa nel 93° percentile (oltre 1 sd)\n# Nel Test B è circa nell'77° percentile (tra media e +1 sd)\n```\n\n### Soluzioni Parte 3 {.unnumbered .unlisted}\n\n**8a.** La regola empirica mostra che il 95% dei valori cade entro ±2 sd dalla media. Gli intervalli di confidenza usano questo principio: se conosciamo la distribuzione campionaria di una statistica, possiamo costruire un intervallo che \"cattura\" il parametro il 95% delle volte.\n\n**9c.** Con n=500, il test di Shapiro-Wilk è molto sensibile e può rilevare deviazioni minime dalla normalità che non hanno importanza pratica. Azioni consigliate:\n\n1. Esaminare il QQ-plot (più informativo)\n2. Se il QQ-plot mostra solo piccole deviazioni agli estremi, non preoccuparsi\n3. Ricordare che molti metodi statistici sono robusti a piccole violazioni della normalità\n4. Se le deviazioni sono sostanziali, considerare trasformazioni o metodi non parametrici\n\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.2\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] gridExtra_2.3         dslabs_0.9.1          ggbeeswarm_0.7.3     \n#>  [4] ragg_1.5.0            tinytable_0.15.2      withr_3.0.2          \n#>  [7] systemfonts_1.3.1     patchwork_1.3.2       ggdist_3.3.3         \n#> [10] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.1        \n#> [13] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.6.1      \n#> [16] loo_2.9.0             rstan_2.32.7          StanHeaders_2.32.10  \n#> [19] brms_2.23.0           Rcpp_1.1.0            sessioninfo_1.2.3    \n#> [22] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [25] modelr_0.1.11         tibble_3.3.0          dplyr_1.1.4          \n#> [28] tidyr_1.3.2           rio_1.2.4             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] inline_0.3.21         sandwich_3.1-1        rlang_1.1.6          \n#>  [4] magrittr_2.0.4        multcomp_1.4-29       snakecase_0.11.1     \n#>  [7] otel_0.2.0            compiler_4.5.2        vctrs_0.6.5          \n#> [10] stringr_1.6.0         pkgconfig_2.0.3       arrayhelpers_1.1-0   \n#> [13] fastmap_1.2.0         backports_1.5.0       labeling_0.4.3       \n#> [16] rmarkdown_2.30        purrr_1.2.0           xfun_0.55            \n#> [19] cachem_1.1.0          jsonlite_2.0.0        broom_1.0.11         \n#> [22] parallel_4.5.2        R6_2.6.1              stringi_1.8.7        \n#> [25] RColorBrewer_1.1-3    lubridate_1.9.4       estimability_1.5.1   \n#> [28] knitr_1.51            zoo_1.8-15            pacman_0.5.1         \n#> [31] Matrix_1.7-4          splines_4.5.2         timechange_0.3.0     \n#> [34] tidyselect_1.2.1      abind_1.4-8           yaml_2.3.12          \n#> [37] codetools_0.2-20      curl_7.0.0            pkgbuild_1.4.8       \n#> [40] lattice_0.22-7        bridgesampling_1.2-1  S7_0.2.1             \n#> [43] coda_0.19-4.1         evaluate_1.0.5        survival_3.8-3       \n#> [46] RcppParallel_5.1.11-1 pillar_1.11.1         tensorA_0.36.2.1     \n#> [49] checkmate_2.3.3       stats4_4.5.2          distributional_0.5.0 \n#> [52] generics_0.1.4        rprojroot_2.1.1       rstantools_2.5.0     \n#> [55] scales_1.4.0          xtable_1.8-4          glue_1.8.0           \n#> [58] emmeans_2.0.1         tools_4.5.2           mvtnorm_1.3-3        \n#> [61] grid_4.5.2            QuickJSR_1.8.1        colorspace_2.1-2     \n#> [64] nlme_3.1-168          beeswarm_0.4.0        vipor_0.4.7          \n#> [67] cli_3.6.5             textshaping_1.0.4     svUnit_1.0.8         \n#> [70] Brobdingnag_1.2-9     V8_8.0.1              gtable_0.3.6         \n#> [73] digest_0.6.39         TH.data_1.1-5         htmlwidgets_1.6.4    \n#> [76] farver_2.1.2          memoise_2.0.1         htmltools_0.5.9      \n#> [79] lifecycle_1.0.5       MASS_7.3-65\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "07_introduction_normal_distribution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}