{
  "hash": "35b1b0747dccd6403571e3e7cc48c4f1",
  "result": {
    "engine": "knitr",
    "markdown": "# Dal file alla tabella controllata {#sec-r-programming}\n\n::: {.callout-note title=\"In sintesi\"}\n**Da sapere**  Importare un file significa trasformarlo in un oggetto che R può usare. Non significa ancora avere dati pronti per l'analisi. Prima di procedere dobbiamo confrontare la tabella ottenuta con ciò che sappiamo dello studio: numero e significato delle righe, variabili attese, tipi, categorie, intervalli plausibili e valori mancanti.\n\n**Da saper fare**  Descrivere l'importazione come una sequenza di controlli; verificare il percorso prima di leggere il file; ispezionare struttura e contenuto della tabella; riconoscere segnali d'allarme; formulare all'AI una richiesta che includa aspettative e verifiche, non soltanto il comando di importazione.\n:::\n\n## Introduzione {.unnumbered .unlisted}\n\nNel capitolo precedente abbiamo organizzato il lavoro come un progetto riproducibile. Sappiamo ora dove devono trovarsi i dati originali, perché i percorsi devono essere relativi e perché ogni trasformazione deve poter essere ricostruita.\n\nIl passo successivo consiste nel portare un file dentro R. L'operazione tecnica è spesso semplice. Il passaggio scientificamente importante viene subito dopo: stabilire se l'oggetto importato corrisponde davvero ai dati che pensiamo di avere.\n\nUn file può essere letto senza errori e produrre comunque una tabella sbagliata. Il separatore può non essere riconosciuto; una colonna numerica può diventare testo; codici come `999` possono essere scambiati per valori reali; categorie equivalenti possono comparire con grafie diverse; alcune variabili attese possono mancare.\n\nPer questo motivo il capitolo non presenta un catalogo di funzioni di importazione. Introduce una routine generale:\n\n$$\n\\text{localizzare}\n\\longrightarrow\n\\text{importare}\n\\longrightarrow\n\\text{ispezionare}\n\\longrightarrow\n\\text{confrontare con le attese}\n\\longrightarrow\n\\text{decidere}.\n$$\n\nL'AI può scrivere la sintassi di ogni passaggio. Le aspettative con cui confrontare il risultato devono però provenire dal ricercatore, dal disegno e dalla documentazione dello studio.\n\n::: {.callout-tip title=\"Prerequisiti\"}\nÈ utile avere letto @sec-r e @sec-r-environment. Il primo introduce input, trasformazioni, output e controlli; il secondo stabilisce come organizzare file e percorsi in un progetto riproducibile.\n:::\n\n## Panoramica del capitolo {.unnumbered .unlisted}\n\nPartiremo da una descrizione esplicita della tabella attesa. Verificheremo poi l'esistenza del file, lo importeremo con un percorso relativo e controlleremo dimensioni, nomi, tipi, valori mancanti e contenuti plausibili. Infine vedremo come trasformare questi controlli in una richiesta efficace all'AI e come distinguere un problema tecnico da un problema metodologico.\n\n::: {.callout-note title=\"Preparazione del notebook\"}\nGli esempi usano un file ipotetico chiamato `stress_sonno_originale.csv`, collocato in `data/raw/`. I blocchi di importazione sono mostrati come codice da adattare e non vengono eseguiti durante il rendering del capitolo.\n\nPer i file CSV useremo `readr::read_csv()`. Se i dati sono in formato Excel, SPSS o in un altro formato, la logica dei controlli rimane identica; cambierà soltanto la funzione che traduce il file in una tabella.\n:::\n\n## Prima dell'importazione: che cosa ci aspettiamo?\n\nUn controllo è possibile soltanto se abbiamo un'aspettativa.\n\nSupponiamo che lo studio riguardi 120 studenti e che ogni partecipante debba comparire una sola volta. Il file dovrebbe contenere almeno un identificatore, un punteggio di stress, una misura della qualità del sonno e una variabile relativa al gruppo o al genere. Potremmo inoltre sapere che lo stress varia da 0 a 40 e la qualità del sonno da 1 a 10.\n\nQueste informazioni costituiscono una descrizione minima della tabella attesa:\n\n| Aspetto | Attesa |\n|---|---|\n| Unità di analisi | Uno studente per riga |\n| Numerosità approssimativa | Circa 120 righe |\n| Variabili indispensabili | `id`, `stress`, `qualita_sonno`, `genere` |\n| Intervallo di `stress` | Da 0 a 40 |\n| Intervallo di `qualita_sonno` | Da 1 a 10 |\n| Codici mancanti nel file originale | Vuoto oppure `999`, secondo il codebook |\n\nLa tabella non deve necessariamente coincidere perfettamente con queste attese. Una differenza indica però qualcosa da comprendere prima dell'analisi.\n\nSenza aspettative, comandi come `str()` e `summary()` producono informazioni ma non consentono di decidere se il risultato sia corretto.\n\n::: {.callout-important title=\"Il controllo è un confronto\"}\nNon basta osservare che il dataset contiene 118 righe. Dobbiamo sapere se 118 è il numero previsto, se due partecipanti non hanno completato lo studio oppure se due righe sono andate perdute durante l'importazione.\n:::\n\n## Verificare il percorso prima di leggere\n\nDefiniamo il percorso relativo una sola volta:\n\n```r\npercorso_input <-\n  \"data/raw/stress_sonno_originale.csv\"\n```\n\nPossiamo quindi controllare se il file esiste:\n\n```r\nfile.exists(percorso_input)\n```\n\nSe il risultato è `FALSE`, non serve modificare subito la funzione di importazione. Il problema si trova prima: il nome, la cartella o la radice del progetto non corrispondono a ciò che abbiamo indicato.\n\nPossiamo fermare esplicitamente la procedura:\n\n```r\nif (!file.exists(percorso_input)) {\n  stop(\n    \"File non trovato: \",\n    percorso_input\n  )\n}\n```\n\nIl significato algoritmico è generale:\n\n> Prima di eseguire un'operazione, verifica che una condizione necessaria sia soddisfatta. Se non lo è, interrompi la procedura con un messaggio comprensibile.\n\nQuesto principio è più importante della specifica sintassi di `if` e `stop()`.\n\n## Importare significa creare un oggetto\n\nPer un file CSV possiamo usare:\n\n```r\ndati <- readr::read_csv(\n  percorso_input,\n  show_col_types = FALSE\n)\n```\n\nLa procedura si legge:\n\n> Leggi il file indicato da `percorso_input`, trasformalo in una tabella R e salva il risultato nell'oggetto `dati`.\n\nÈ utile mantenere separati il percorso e l'oggetto. Il primo identifica l'input esterno; il secondo contiene la rappresentazione importata.\n\n`readr::read_csv()` è soltanto una delle possibili funzioni. Per un file Excel potremmo usare `readxl::read_excel()`; per un file SPSS, `haven::read_sav()`. Non occorre memorizzare tutte queste varianti. È sufficiente saper indicare all'AI il formato reale e chiedere una funzione appropriata, senza modificare il resto della procedura di controllo.\n\n::: {.callout-warning title=\"Il successo dell'importazione non convalida i dati\"}\nSe il comando termina senza errori, sappiamo soltanto che R ha prodotto un oggetto. Non sappiamo ancora se le colonne siano state separate correttamente, se i tipi siano appropriati o se i valori abbiano il significato previsto.\n:::\n\n## Primo controllo: forma e identità della tabella\n\nI primi comandi devono rispondere a domande semplici: quante righe e colonne sono state importate, come si chiamano le variabili e che cosa appare nelle prime osservazioni?\n\n```r\ndim(dati)\nnames(dati)\nhead(dati)\n```\n\n`dim()` restituisce il numero di righe e colonne. `names()` mostra i nomi delle variabili. `head()` presenta le prime righe.\n\nQuesti controlli sono complementari. Un dataset con 120 righe e una sola colonna è sospetto se il questionario conteneva venti variabili. I nomi possono rivelare che il file importato appartiene a un'altra fase dello studio. Le prime righe possono mostrare che l'intestazione è stata interpretata come un'osservazione oppure che la prima colonna contiene numeri di riga esportati per errore.\n\nLa domanda non è soltanto «che cosa vedo?», ma:\n\n> Ciò che vedo è compatibile con il file e con il disegno che mi aspetto?\n\n`View(dati)` può essere utile per un'ispezione manuale. Non sostituisce però i controlli scritti, perché un'altra persona non può riprodurre ciò che abbiamo notato guardando lo schermo.\n\n## Secondo controllo: struttura e tipi\n\nR assegna un tipo informatico a ogni colonna. Possiamo esaminarlo con:\n\n```r\nstr(dati)\n```\n\nSe `stress` deve contenere un punteggio numerico ma compare come testo, dobbiamo individuarne la causa prima di convertirlo. Potrebbero esserci valori come `\"non risponde\"`, separatori decimali inattesi o annotazioni inserite nel file.\n\nSe `genere` è registrato con i numeri `1`, `2` e `3`, R può considerarlo numerico. Dal punto di vista scientifico, però, quei numeri potrebbero essere codici nominali.\n\nIl tipo assegnato da R e il livello di misura sono quindi due domande differenti:\n\n> Come è stata memorizzata la colonna?\n\n> Che cosa rappresentano i suoi valori?\n\nLa prima domanda riguarda il software. La seconda riguarda il codebook e il capitolo sulla misurazione.\n\n## Terzo controllo: le variabili indispensabili esistono?\n\nPossiamo dichiarare i nomi necessari:\n\n```r\nvariabili_richieste <- c(\n  \"id\",\n  \"stress\",\n  \"qualita_sonno\",\n  \"genere\"\n)\n```\n\nPoi possiamo cercare quelle mancanti:\n\n```r\nsetdiff(\n  variabili_richieste,\n  names(dati)\n)\n```\n\nSe il risultato è `character(0)`, tutte le variabili richieste sono presenti. Se compaiono uno o più nomi, il dataset non corrisponde alla struttura attesa oppure i nomi differiscono.\n\nIl significato dell'operazione è:\n\n> Confronta l'insieme delle variabili necessarie con l'insieme delle colonne presenti e restituisci ciò che manca.\n\nQuesta è un'idea algoritmica molto generale. Prima di eseguire una procedura, si verifica che gli input richiesti siano disponibili.\n\nPossiamo trasformare il controllo in una condizione che interrompe l'analisi:\n\n```r\nvariabili_mancanti <- setdiff(\n  variabili_richieste,\n  names(dati)\n)\n\nif (length(variabili_mancanti) > 0) {\n  stop(\n    \"Variabili mancanti: \",\n    paste(\n      variabili_mancanti,\n      collapse = \", \"\n    )\n  )\n}\n```\n\nNon è necessario memorizzare subito `paste()` o `collapse`. È sufficiente riconoscere che il codice costruisce un messaggio con i nomi mancanti.\n\n## Quarto controllo: valori mancanti e codici speciali\n\nIn R un valore mancante riconosciuto è rappresentato da `NA`. Possiamo contare i mancanti in ogni colonna con:\n\n```r\ncolSums(is.na(dati))\n```\n\nPer una singola variabile:\n\n```r\nsum(is.na(dati$qualita_sonno))\nmean(is.na(dati$qualita_sonno))\n```\n\nLa prima istruzione conta i mancanti; la seconda ne calcola la proporzione.\n\nQuesti risultati non spiegano perché i valori manchino. Inoltre, un file può usare codici come `999`, `-99`, `\"missing\"` o `\"non risponde\"`. Finché non vengono dichiarati come mancanti durante l'importazione o trasformati esplicitamente, R li considera valori osservati.\n\nPrima di ricodificare dobbiamo consultare il codebook o la documentazione dello studio. Un valore `999` potrebbe essere un codice mancante, ma potrebbe anche essere un valore legittimo in un'altra variabile.\n\n::: {.callout-important title=\"Non indovinare i codici mancanti\"}\nL'AI può riconoscere che `999` sembra sospetto, ma non può stabilirne il significato senza documentazione. Chiedile di mostrare dove compare e come ricodificarlo soltanto dopo che ne hai verificato il significato.\n:::\n\n## Quinto controllo: categorie e intervalli plausibili\n\nPer una variabile categorica possiamo vedere i valori presenti e le loro frequenze:\n\n```r\ntable(\n  dati$genere,\n  useNA = \"ifany\"\n)\n```\n\nIl risultato può mostrare categorie come `\"F\"`, `\"f\"`, `\"Femmina\"` e `\"female\"`. R le considera differenti. La loro eventuale unificazione richiede una decisione esplicita.\n\nPer una variabile numerica possiamo iniziare con:\n\n```r\nsummary(dati$stress)\nsummary(dati$qualita_sonno)\n```\n\n`summary()` mostra minimo, quartili, mediana, media, massimo ed eventuali mancanti. Se `stress` dovrebbe variare tra 0 e 40, un massimo pari a 999 segnala un problema da approfondire.\n\nPossiamo rendere esplicito il controllo dell'intervallo:\n\n```r\ndati$stress < 0 |\n  dati$stress > 40\n```\n\nL'espressione produce `TRUE` per i valori fuori dall'intervallo atteso. Per contarli:\n\n```r\nsum(\n  dati$stress < 0 |\n    dati$stress > 40,\n  na.rm = TRUE\n)\n```\n\nAncora una volta, il codice non decide che cosa fare di questi valori. Li rende visibili. Potrebbero essere errori, codici speciali o osservazioni che richiedono una verifica nel materiale originale.\n\n## L'identificatore e l'unità di analisi\n\nSe ogni riga dovrebbe rappresentare una persona, l'identificatore dovrebbe essere presente e normalmente non dovrebbe ripetersi.\n\n```r\nanyDuplicated(dati$id)\n```\n\nUn risultato pari a `0` indica che non sono state trovate duplicazioni. Un valore maggiore di zero segnala la posizione della prima ripetizione.\n\nUna duplicazione non è automaticamente un errore. In uno studio longitudinale o entro partecipanti, la stessa persona deve comparire in più righe. Il controllo serve quindi a collegare la tabella al disegno:\n\n> Una riga rappresenta una persona, una misurazione, una prova oppure una combinazione di persona e momento?\n\nQuesto è un esempio importante di limite dell'automazione. L'AI può trovare identificatori ripetuti; soltanto la documentazione dello studio permette di stabilire se siano corretti.\n\n## Dai controlli alla decisione\n\nAl termine dell'ispezione, non dobbiamo avere necessariamente una tabella perfetta. Dobbiamo avere una diagnosi.\n\nPossiamo scoprire che il file è quello giusto ma contiene due categorie scritte in modo incoerente. Possiamo trovare codici mancanti che devono essere ricodificati. Possiamo accorgerci che una variabile attesa non è stata esportata o che il numero di righe non coincide con il registro dei partecipanti.\n\nLa decisione successiva dipende dal problema. Alcune trasformazioni possono essere documentate nel codice. Altre richiedono di recuperare il file corretto, consultare il codebook o contattare chi ha raccolto i dati.\n\nL'algoritmo generale è:\n\n$$\n\\text{osservare una discrepanza}\n\\longrightarrow\n\\text{formulare una spiegazione}\n\\longrightarrow\n\\text{cercare evidenza}\n\\longrightarrow\n\\text{correggere o documentare}.\n$$\n\nNon bisogna trasformare automaticamente ogni valore insolito in `NA` né uniformare categorie soltanto perché sembrano simili.\n\n## Salvare una versione trasformata\n\nI controlli che non modificano il dataset non richiedono un nuovo file. Se invece ricodifichiamo valori, rinominiamo colonne o costruiamo nuove variabili, possiamo salvare una versione elaborata in una posizione distinta:\n\n```r\npercorso_output <-\n  \"data/processed/stress_sonno_controllato.csv\"\n\nreadr::write_csv(\n  dati_controllati,\n  percorso_output\n)\n```\n\nIl file originale rimane in `data/raw/`. Il codice documenta come viene creato `dati_controllati`, mentre `data/processed/` contiene un output rigenerabile.\n\nSalvare una copia non sostituisce il codice. Senza la procedura che la produce, la versione elaborata è soltanto un secondo file di origine incerta.\n\n## Chiedere all'AI una procedura controllabile\n\nUna richiesta poco informativa è:\n\n> Importa e pulisci questo dataset.\n\nLa parola *pulisci* può includere decisioni molto diverse. L'AI potrebbe rinominare colonne, eliminare righe, convertire tipi o sostituire mancanti senza rendere chiare le assunzioni.\n\nUna richiesta migliore separa importazione, controlli e trasformazioni:\n\n::: {.callout-tip title=\"Un prompt per importare e controllare\"}\n> Sto lavorando in un progetto R. Il file CSV si trova in `data/raw/stress_sonno_originale.csv` e ogni riga dovrebbe rappresentare uno studente. Le variabili indispensabili sono `id`, `stress`, `qualita_sonno` e `genere`. `stress` dovrebbe variare da 0 a 40 e `qualita_sonno` da 1 a 10. Il codebook usa `999` come valore mancante soltanto per queste due scale.\n>\n> Scrivi codice R semplice che:\n>\n> 1. verifichi l'esistenza del file;\n> 2. lo importi con `readr::read_csv()` senza modificare l'originale;\n> 3. mostri dimensioni, nomi e struttura;\n> 4. segnali variabili mancanti, identificatori duplicati, valori mancanti e valori fuori intervallo;\n> 5. non corregga o elimini nulla automaticamente.\n>\n> Spiega ogni controllo in linguaggio naturale e separa chiaramente i problemi osservati dalle trasformazioni eventualmente consigliate.\n:::\n\nLa richiesta fornisce ciò che l'AI non può ricavare dalla sintassi: unità di analisi, variabili attese, intervalli plausibili e significato del codice speciale.\n\nSe l'assistente propone di correggere il dataset, possiamo chiedere una seconda fase:\n\n> Ora proponi trasformazioni esplicite soltanto per i problemi confermati. Conserva l'oggetto originale, crea `dati_controllati` e mostra dopo ogni passaggio un controllo che documenti l'effetto.\n\n## Un controllo minimo completo\n\nIl seguente blocco riassume la procedura per il file ipotetico:\n\n```r\npercorso_input <-\n  \"data/raw/stress_sonno_originale.csv\"\n\nif (!file.exists(percorso_input)) {\n  stop(\n    \"File non trovato: \",\n    percorso_input\n  )\n}\n\ndati <- readr::read_csv(\n  percorso_input,\n  show_col_types = FALSE\n)\n\ndim(dati)\nnames(dati)\nhead(dati)\nstr(dati)\n\nvariabili_richieste <- c(\n  \"id\",\n  \"stress\",\n  \"qualita_sonno\",\n  \"genere\"\n)\n\nsetdiff(\n  variabili_richieste,\n  names(dati)\n)\n\ncolSums(is.na(dati))\n\ntable(\n  dati$genere,\n  useNA = \"ifany\"\n)\n\nsummary(dati$stress)\nsummary(dati$qualita_sonno)\n\nanyDuplicated(dati$id)\n```\n\nNon è necessario imparare il blocco a memoria. Dobbiamo saperne ricostruire la logica:\n\n> Trova il file. Interrompi se non esiste. Importalo. Controlla forma, nomi e struttura. Confronta le colonne con quelle necessarie. Esamina mancanti, categorie, intervalli e identificatori.\n\nLa sequenza può essere adattata a qualunque dataset modificando le aspettative.\n\n## Errori frequenti e diagnosi\n\nSe il dataset contiene una sola colonna, il file potrebbe usare un separatore diverso da quello atteso. La risposta corretta non è procedere con l'analisi, ma esaminare il file e scegliere la funzione o gli argomenti appropriati.\n\nSe una variabile numerica viene letta come testo, occorre cercare valori non numerici, separatori decimali o codici speciali. Convertirla immediatamente può trasformare informazioni problematiche in nuovi mancanti senza spiegazione.\n\nSe una categoria attesa non compare, le possibili spiegazioni includono un filtro precedente, un errore di esportazione o un campione differente da quello previsto. Aggiungere manualmente la categoria non risolve il problema.\n\nSe il numero di righe è inatteso, dobbiamo confrontarlo con il registro dello studio e verificare duplicazioni, mancate importazioni o righe aggiuntive.\n\nIn tutti questi casi, il messaggio generale è lo stesso:\n\n> Prima di correggere, identifica quale aspettativa è stata violata e cerca la causa della discrepanza.\n\n## Che cosa non serve ancora\n\nNon è necessario costruire un sistema completo di validazione automatica, imparare espressioni regolari o usare pacchetti specializzati per il controllo dei dati. Questi strumenti diventano utili nei progetti più grandi.\n\nPer questo modulo sono sufficienti pochi controlli leggibili, scelti in base al disegno e al codebook. La semplicità è un vantaggio se rende chiaro che cosa viene verificato.\n\nNel capitolo successivo useremo `dplyr` per selezionare righe e colonne, creare variabili e produrre riepiloghi. Quelle trasformazioni saranno affidabili soltanto se la tabella iniziale è stata compresa e controllata.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nImportare un file significa tradurlo in un oggetto R. Il passaggio decisivo consiste nel verificare che quella traduzione conservi la struttura e il significato attesi.\n\nI controlli iniziali riguardano forma, nomi, tipi, variabili indispensabili, valori mancanti, categorie, intervalli plausibili e unità di analisi. Nessuno di questi controlli è puramente meccanico: ciascuno richiede un confronto con il disegno, la misurazione e la documentazione dello studio.\n\nL'AI può generare una procedura efficace soltanto se le forniamo queste aspettative. Chiederle di «pulire i dati» senza specificarle significa delegare decisioni che potrebbero modificare il campione e il significato delle variabili. È preferibile chiedere prima una diagnosi, poi autorizzare trasformazioni esplicite e controllate.\n\nLa mentalità da conservare è semplice: non fidarsi del fatto che il file sia stato letto; produrre evidenza che la tabella corrisponda a ciò che dovrebbe rappresentare.\n\n## Esercizi {.unnumbered .unlisted}\n\n1. Un file dovrebbe contenere 250 partecipanti e 30 variabili. Dopo l'importazione, `dim(dati)` restituisce `250 1`. Quale aspettativa è stata violata e quale possibile causa controlleresti per prima?\n\n2. Spiega la differenza tra queste due domande: «R ha memorizzato `genere` come numero?» e «I numeri presenti in `genere` rappresentano una quantità?».\n\n3. Il comando seguente restituisce `\"qualita_sonno\"`:\n\n   ```r\n   setdiff(\n     c(\"id\", \"stress\", \"qualita_sonno\"),\n     names(dati)\n   )\n   ```\n\n   Che cosa significa? Perché non dovresti creare automaticamente una colonna vuota con quel nome?\n\n4. Una scala dovrebbe variare da 0 a 40 e contiene il valore `999`. Quali spiegazioni considereresti prima di trasformarlo in `NA`?\n\n5. `anyDuplicated(dati$id)` restituisce un valore maggiore di zero. Perché questo risultato può indicare un errore in uno studio trasversale ma essere previsto in uno studio longitudinale?\n\n6. Formula un prompt per l'AI che chieda di importare un file e diagnosticare i problemi senza modificare o eliminare automaticamente alcuna osservazione.\n\n7. L'AI propone di convertire direttamente una colonna testuale in numerica. Quali controlli dovrebbe mostrare prima della conversione?\n\n8. Descrivi in linguaggio naturale un algoritmo che parta da un percorso e termini con una decisione documentata sulla possibilità di usare la tabella per l'analisi.\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\n1. È stata violata l'aspettativa sul numero di colonne. Una causa probabile è il mancato riconoscimento del separatore del file. Bisogna esaminare il formato e la prima riga prima di proseguire.\n\n2. La prima domanda riguarda il tipo informatico assegnato da R. La seconda riguarda il significato scientifico dei valori. Codici numerici possono rappresentare categorie nominali e non quantità.\n\n3. La variabile richiesta non è presente nella tabella. Potrebbe esserci un errore nel nome, nel file esportato o nella documentazione. Creare una colonna vuota nasconderebbe il problema senza recuperare i dati mancanti.\n\n4. `999` potrebbe essere un codice di mancata risposta, un errore di inserimento, un codice proveniente da un altro sistema oppure un valore appartenente a una colonna importata male. Il codebook e il file originale devono stabilirne il significato.\n\n5. Se ogni riga dovrebbe rappresentare una persona, un identificatore ripetuto è incoerente con l'unità di analisi. Se ogni persona produce più misure, la ripetizione è necessaria e deve essere accompagnata da una variabile che distingua tempi o condizioni.\n\n6. Il prompt dovrebbe specificare percorso, formato, unità di analisi, variabili attese, intervalli e codici mancanti. Dovrebbe chiedere controlli e un rapporto delle discrepanze, vietando trasformazioni automatiche.\n\n7. Dovrebbe mostrare i valori distinti o almeno quelli non convertibili, verificare separatori decimali e codici speciali, contare quanti valori diventerebbero mancanti e confrontare il risultato con il codebook.\n\n8. Verificare l'esistenza del file; importarlo in un nuovo oggetto; controllare dimensioni, nomi e tipi; confrontare le colonne con quelle attese; esaminare mancanti, categorie, intervalli e identificatori; documentare le discrepanze; correggere soltanto problemi confermati oppure interrompere l'analisi.\n:::\n\n::: {.callout-note title=\"Punti chiave\" collapse=\"true\"}\n- Un file importato non è automaticamente pronto per l'analisi.\n- Ogni controllo confronta i dati osservati con un'aspettativa dichiarata.\n- Il percorso deve essere verificato prima dell'importazione.\n- Il successo del comando indica soltanto che R ha creato un oggetto.\n- Forma, nomi, tipi e contenuti della tabella devono essere controllati separatamente.\n- I codici numerici non sono necessariamente quantità.\n- I valori mancanti e quelli fuori intervallo richiedono documentazione, non correzioni automatiche.\n- La presenza di identificatori duplicati va interpretata alla luce dell'unità di analisi.\n- L'AI deve ricevere struttura attesa, codebook e vincoli sulle trasformazioni.\n- È preferibile chiedere prima una diagnosi e poi una correzione documentata.\n:::\n\n::: {.callout-note title=\"Ambiente di sviluppo\" collapse=\"true\"}\nGli esempi di importazione usano il pacchetto `readr`. Le informazioni sulla sessione possono essere ottenute con:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.5.2\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n\ntime zone: Europe/Zagreb\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nloaded via a namespace (and not attached):\n [1] htmlwidgets_1.6.4 compiler_4.6.1    fastmap_1.2.0     cli_3.6.6        \n [5] tools_4.6.1       htmltools_0.5.9   otel_0.2.0        yaml_2.3.12      \n [9] rmarkdown_2.31    knitr_1.51        jsonlite_2.0.0    xfun_0.60        \n[13] digest_0.6.39     rlang_1.3.0       evaluate_1.0.5   \n```\n\n\n:::\n:::\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}